const path = require("path");
const fs = require("fs");
const settings = require("../config/settings");

const divider = "━━━━━━━━━━━━━━━━━━━━";
const readMoreSeparator = "\u200e".repeat(4000);
const luckPercentages = [0, 1, 2, 5, 10, 20, 25, 50, 99, 100];
const luckOpeners = [
  "Fufu~ Fuuka cek hokinya dulu yaa (≧∇≦)/",
  "Ehehe, tes kehokian dimulaii~ (๑˃̵ᴗ˂̵)",
  "Yuk yuk, Fuuka intip aura hokinya yaa~ (≧ω≦)",
  "Jeng jeng~ Fuuka mau lihat hoki hari ini nih~ (o^▽^o)",
  "Hehe, Fuuka putar roda keberuntungan dulu yaa~ (≧◡≦)",
  "Okeee, Fuuka cek nasib manisnya dulu~ (๑˃ᴗ˂)ﻭ"
];
const dynamicGreetings = [
  [
    "Yahhoo~ Fuuka datang yaa, hehee~ (≧∇≦)/",
    "Kalau ada yang dicari, bilang pelan-pelan ke Fuuka yaa~"
  ],
  [
    "Ehehe, Fuuka siap bantu nih~ (≧ω≦)",
    "Sini sini, Fuuka jelasin dengan manis yaa~"
  ],
  [
    "Uwaa, Fuuka di sini lhoo~ (๑˃̵ᴗ˂̵)",
    "Biar Fuuka yang kasih tau pelan-pelan yaa~"
  ],
  [
    "Fuuka muncul duluan nih~ (≧▽≦)",
    "Yuk yuk, kita lihat bareng sama Fuuka yaa~"
  ]
];
const cuteFooterQuestions = [
  "Nee nee, Fuuka imouto yang imut kan, onii-chan? (≧ω≦)",
  "Ehehe... Fuuka jelasinya gampang dimengerti kan? puji Fuuka dong~ (๑˃̵ᴗ˂̵)",
  "Fuuka udah bantuin onii-chan dengan manis kan? (〃▽〃)",
  "Kalau masih bingung, panggil Fuuka lagi yaa, onii-chan~ (o^▽^o)",
  "Fuuka kecil begini tetep bisa diandelin kan? (≧∇≦)",
  "Ano... Fuuka kawaii banget kan hari ini? hehe~ (˶ᵔ ᵕ ᵔ˶)"
];
const hokiResponses = {
  0: [
    "Yahh... 0% nih onii-chan, aura hokinya lagi tidur total~ bleee :p",
    "Ehehe... 0% dong, bahkan keberuntunganmu malu buat muncul~ (￣▽￣*)ゞ",
    "Fuuka cek lagi... tetep 0%. Aduh, ini mah zonk imut~ (´ . .̫ . `)",
    "0% yaa... dompet gacha kamu harus diselametin dulu deh~ (≧▽≦)",
    "Astaga, 0% beneran. Hoki onii-chan kabur entah ke mana~ :3",
    "Fuuka nggak bohong yaa... hasilnya 0%. Sedih tapi lucu~ (˶ᵔ ᵕ ᵔ˶)",
    "0% nih! Bahkan semangetnya Fuuka lebih tinggi dari hokimu hari ini~ (≧ω≦)",
    "Onii-chan dapat 0%... peluk dulu sini, jangan nangis yaa~ (｡•́︿•̀｡)"
  ],
  1: [
    "1% yaa~ tipis banget, tapi masih ada sisa harapan kecil imut~ (๑•̀ㅂ•́)و",
    "Fuuka lihat ada 1% hoki... kecil banget sampe hampir ilang~ :p",
    "1% doang, onii-chan. Kedip dikit juga lewat~ (￣y▽￣)╭",
    "Ehehe, 1%~ minimal nggak 0% yaa, syukuri dulu~ (˶ᵔ ᵕ ᵔ˶)",
    "1% nih. Hoki kamu lagi malu-malu munculnya~ (〃▽〃)",
    "Fuuka kasih laporan: 1%. Masih mending daripada zonk total~ (´꒳`)",
    "1% yaa... ini keberuntungan versi cicilan kayaknya~ (≧▽≦)",
    "Tipis-tipis 1%, onii-chan. Jangan dipake gacha dulu deh~ :3"
  ],
  2: [
    "2% yaa~ hokinya mulai bangun, tapi masih ngulet dulu~ (￣o￣) zzZ",
    "Fuuka hitung-hitung... hasilnya 2%. Masih mini banget~ (≧ω≦)",
    "2% dong, sedikit lebih baik tapi tetap rawan ditikung nasib~ :p",
    "Ehehe, 2% itu lucu sih... kecil, tapi ada~ (˶ᵔ ᵕ ᵔ˶)",
    "Hasil tesnya 2%! Hoki onii-chan udah muncul setitik~ (๑˃ᴗ˂)ﻭ",
    "2% yaa, semoga nanti naik... sekarang sih masih mode hemat~ (´ . .̫ . `)",
    "Fuuka bilang 2% nih. Jangan sombong dulu yaa~ (￣▽￣*)ゞ",
    "2% hoki terdeteksi! Masih kategori receh tapi manis~ (o^▽^o)"
  ],
  5: [
    "5% yaa~ lumayan buat senyum tipis dulu, onii-chan~ (´꒳`)",
    "Hokinya 5%! Masih kecil, tapi udah bisa pamer dikit~ (≧▽≦)",
    "Fuuka cek hasilnya 5% yaa, lumayan buat modal pede~ (๑•̀ㅂ•́)و",
    "5% nih! Belum wah banget, tapi nggak malu-maluin~ (￣▽￣)",
    "Ehehe, 5% itu hoki mini yang lucu yaa~ (o^▽^o)",
    "Fuuka umumkan: 5%! Mulai ada cahaya keberuntungan~ (≧ω≦)",
    "5% yaa, cukup buat bilang 'masih ada harapan'~ (˶ᵔ ᵕ ᵔ˶)",
    "Hasilnya 5%! Tipis, tapi udah nggak bikin Fuuka khawatir~ (๑˃̵ᴗ˂̵)"
  ],
  10: [
    "10% yaa~ nah, ini baru mulai enak dilihat~ (´꒳`)",
    "Fuuka kasih nilai hoki 10%! Sudah lumayan manis nih~ (o^▽^o)",
    "10% dong, onii-chan. Ada bakat beruntung dikit~ (≧ω≦)",
    "Ehehe, 10% itu udah bisa bikin Fuuka angguk-angguk puas~ (˶ᵔ ᵕ ᵔ˶)",
    "Hoki kamu 10%! Masih santai, tapi udah aman~ (๑•̀ㅂ•́)و",
    "Fuuka deteksi 10% yaa~ keberuntunganmu mulai rajin masuk kerja~ (≧▽≦)",
    "10% nih, cukup buat bikin hari onii-chan agak cerah~ (๑˃̵ᴗ˂̵)",
    "Lumayan~ 10%! Bukan sultan hoki, tapi nggak apes juga~ (￣▽￣)"
  ],
  20: [
    "20% yaa~ wah, onii-chan mulai wangi hoki nih~ (≧▽≦)",
    "Fuuka senyum dulu... hasilnya 20%! Lumayan cakep~ (´꒳`)",
    "20% dong! Hoki kamu mulai bisa diajak kerja sama~ (๑•̀ㅂ•́)و",
    "Ehehe, 20% itu udah masuk kategori lumayan banget yaa~ (o^▽^o)",
    "Hasil tes kehokian: 20%! Fuuka setuju ini cukup bagus~ (๑˃̵ᴗ˂̵)",
    "20% yaa, udah boleh agak pede dikit~ (￣▽￣)",
    "Fuuka lihat aura hijau-hijau... eh ternyata 20% hoki~ (≧ω≦)",
    "20% nih! Keberuntunganmu mulai ngelirik balik, onii-chan~ (〃▽〃)"
  ],
  25: [
    "25% yaa~ seperempat sultan hoki nih, ehehe~ (≧ω≦)",
    "Fuuka kasih hasil 25%! Udah lumayan ganteng hokinya~ (๑•̀ㅂ•́)و",
    "25% dong, onii-chan. Keberuntunganmu mulai serius~ (￣▽￣)",
    "Ehehe, 25% itu enak yaa... nggak kebanyakan, nggak kurang~ (˶ᵔ ᵕ ᵔ˶)",
    "Hoki kamu 25%! Fuuka approve hasil ini~ (o^▽^o)",
    "25% nih, sudah masuk level 'boleh dicoba'~ (๑˃̵ᴗ˂̵)",
    "Fuuka deteksi 25%! Aura beruntungmu lagi naik pelan-pelan~ (≧▽≦)",
    "25% yaa~ lucu juga, hokinya pas di tengah-tengah manis~ (´꒳`)"
  ],
  50: [
    "50% yaa~ wah, setengah dewa hoki nih onii-chan~ (≧▽≦)",
    "Fuuka tepuk tangan dulu! 50% itu cakep banget~ (๑˃ᴗ˂)ﻭ",
    "Hasilnya 50%! Kalau gagal, berarti nasib aja yang iseng~ :p",
    "Ehehe, 50% itu udah bikin Fuuka ikut semangat~ (≧ω≦)",
    "50% dong! Hoki kamu lagi separuh full power~ (o^▽^o)",
    "Fuuka umumkan: 50%! Ini udah level mantap yaa~ (๑˃̵ᴗ˂̵)",
    "50% nih, separuh dunia lagi dukung onii-chan~ (´꒳`)",
    "Wahh 50%! Udah boleh senyum lebar tuh~ (〃▽〃)"
  ],
  99: [
    "99% yaa?! Onii-chan lagi dicium dewi hoki nih kayaknya~ (≧▽≦)",
    "Fuuka kaget! 99% itu hampir sempurna, manis banget~ (๑˃ᴗ˂)ﻭ",
    "99% dong! Tinggal 1% lagi jadi monster keberuntungan~ (≧ω≦)",
    "Ehehe, 99% ini udah bikin Fuuka ikut iri dikit~ (〃▽〃)",
    "Hokinya 99%! Onii-chan hari ini bahaya banget kalau digacha-in~ (o^▽^o)",
    "Fuuka kasih stempel: 99%! Ini level sultan hoki premium~ (￣▽￣)",
    "99% yaa, keberuntunganmu hari ini nyaris nggak masuk akal~ (´꒳`)",
    "Aaaa 99%! Fuuka curiga onii-chan nyimpen lucky charm rahasia~ (๑˃̵ᴗ˂̵)"
  ],
  100: [
    "100%!!! Onii-chan resmi jadi sepuh hoki hari iniii~ (≧▽≦)",
    "Fuuka teriak dulu: 100%! Ini mah hoki max level! (≧∇≦)/",
    "100% dong?! Bahkan nasib pun nurut sama onii-chan hari ini~ (๑˃ᴗ˂)ﻭ",
    "Ehehe... 100% itu bukan beruntung lagi, itu curang manis~ (≧ω≦)",
    "Fuuka kasih mahkota imut: 100%! Raja hoki muncul~ (￣▽￣)",
    "100% yaa! Kalau masih gagal juga, itu semesta yang salah~ (o^▽^o)",
    "Aaaa 100%! Fuuka sampai pengen numpang hoki dikit dong~ (｡•́︿•̀｡)",
    "Fix 100%! Aura hokimu nyala terang banget hari ini~ (๑˃̵ᴗ˂̵)"
  ]
};

const topicHeaderIntros = {
  menu: [
    "Ini menu yang Fuuka siapin buat onii-chan yaa~",
    "Pilih yang mau dilihat yaa, nanti Fuuka temenin~",
    "Fuuka siap nunjukkin yang onii-chan butuhin~"
  ],
  default: [
    "Fuuka jelasin yang ini yaa, pelan-pelan~",
    "Yang ini penting juga, jadi lihat baik-baik yaa~",
    "Coba lihat yang ini yaa, Fuuka udah siapin~"
  ],
  "#0": [
    "Fuuka kenalin guild-nya dulu yaa~",
    "Mulai dari sini yaa, biar nggak bingung~"
  ],
  "#1": [
    "Fuuka ceritain sejarah awalnya yaa~",
    "Ini kisah awal mulanya, dengerin yaa~"
  ],
  "#2": [
    "Bagian ini Fuuka bukain dulu yaa~",
    "Fuuka bantu jelasin yang ini pelan-pelan yaa~"
  ],
  "#3": [
    "Ini arti guild-nya yaa, lucu juga buat dibahas~",
    "Fuuka bantu jelasin makna guild-nya yaa~"
  ],
  "#4": [
    "Kalau soal reward, Fuuka kasih tau yang ini yaa~",
    "Bagian hadiah guild ada di sini yaa, lihat pelan-pelan~"
  ],
  "#5": [
    "Ehehe, ini list birthday guild yaa~",
    "Kalau mau cek ulang tahun member, Fuuka siapin di sini yaa~"
  ],
  "#6": [
    "Ini soal xtall yaa, Fuuka kasih tau pelan-pelan~",
    "Bagian ini ada aturannya, jadi Fuuka jelasin yaa~"
  ],
  "#7": [
    "Kalau cari xtall event, Fuuka susunin list-nya di sini yaa~",
    "Ini daftar xtall event yang Fuuka siapin buat onii-chan yaa~"
  ],
  "#8": [
    "Ini bahan MQ yaa, Fuuka rapihin per bab biar gampang dilihat~",
    "Kalau lagi cari bahan MQ, cek per bab di sini yaa~"
  ],
  "#9": [
    "Ini bahan perluas tas yaa, panjang tapi Fuuka udah rapihin~",
    "Kalau mau upgrade tas, Fuuka bantu urutin bahannya di sini yaa~"
  ],
  "#10": [
    "Refine-nya begini yaa, jangan panik dulu~",
    "Fuuka urutin tips refine-nya biar enak dibaca~"
  ],
  "#11": [
    "Ini list buff yang Fuuka siapin yaa~",
    "Kalau lagi cari buff, cek yang ini yaa~"
  ],
  "#12": [
    "Ini jalur leveling yang rapi yaa~",
    "Fuuka bantu urutin levelnya biar gampang~"
  ],
  "#13": [
    "Ini bagian tempa yaa, Fuuka bukain dulu~",
    "Kalau mau naik kemahiran tempa, cek ini yaa~"
  ],
  "#14": [
    "Ini buat kemahiran padu yaa~",
    "Fuuka susunin step-nya biar gampang diikutin~"
  ],
  "#15": [
    "Ini soal pet yaa, lucu juga topiknya~",
    "Fuuka kasih tips singkatnya dulu yaa~"
  ],
  "#16": [
    "Ini pengaruh status yaa, suka bikin bingung soalnya~",
    "Fuuka bantu bacain stat-nya satu-satu yaa~"
  ],
  "#17": [
    "Ini ailment sama interrupt yaa~",
    "Fuuka bantu bedain efek-efeknya biar nggak ketuker~"
  ],
  "#18": [
    "Ini potential equipment yaa~",
    "Fuuka kasih tau poin pentingnya dengan rapi yaa~"
  ],
  "#19": [
    "Ini tips raid yaa, baca baik-baik yaa~",
    "Fuuka bantu kasih catatan raid-nya di sini~"
  ],
  "#20": [
    "Ini panduan newbie yaa, santai aja bacanya~",
    "Fuuka temenin belajarnya pelan-pelan yaa~"
  ],
  "#98": [
    "Sepuh mode aktif yaa~",
    "Yang ini spesial banget, Fuuka kasih langsung yaa~"
  ],
  "#99": [
    "Hehe, Fuuka mau ngetes hokinya dulu yaa~",
    "Siap yaa, Fuuka cek keberuntungan onii-chan dulu~"
  ]
};

function getRandomCuteFooter() {
  return cuteFooterQuestions[Math.floor(Math.random() * cuteFooterQuestions.length)];
}

function getRandomGreetingLines() {
  return dynamicGreetings[Math.floor(Math.random() * dynamicGreetings.length)];
}

function getRandomIntro(topicKey) {
  const intros = topicHeaderIntros[topicKey] || topicHeaderIntros.default;
  return intros[Math.floor(Math.random() * intros.length)];
}

function getRandomLuckResult() {
  const percentage = luckPercentages[Math.floor(Math.random() * luckPercentages.length)];
  const responses = hokiResponses[percentage];
  const response = responses[Math.floor(Math.random() * responses.length)];
  const opener = luckOpeners[Math.floor(Math.random() * luckOpeners.length)];

  return {
    percentage,
    response,
    opener
  };
}

function isLegacyDivider(line) {
  const trimmed = line.trim();

  if (!trimmed) {
    return false;
  }

  if (/^[\-‐—_]{8,}$/.test(trimmed)) {
    return true;
  }

  if (/^[━─]{8,}$/.test(trimmed)) {
    return true;
  }

  if (/^[󠇖\s]+$/.test(trimmed)) {
    return true;
  }

  return false;
}

function isLegacyHeaderOrFooter(line) {
  const trimmed = line.trim();
  const normalized = trimmed.toLowerCase();

  if (!trimmed) {
    return false;
  }

  if (
    normalized === "fuuka-chan" ||
    normalized === `${settings.botName.toLowerCase()}-chan` ||
    normalized === "bot master-a" ||
    normalized === "ely - by arasea"
  ) {
    return true;
  }

  if (
    normalized.includes("fuuka imut") ||
    normalized.includes("fuuka kawaii") ||
    normalized.includes("fuuka dieum") ||
    normalized.includes("fuuka imoet") ||
    normalized.includes("fuuka imot") ||
    normalized.includes("fuuka imut selalu di hati") ||
    normalized.includes("nge-fans yaa sama fuuka") ||
    normalized.includes("semangat mq nya") ||
    normalized.includes("by: master-a") ||
    normalized.includes("by master-a")
  ) {
    return true;
  }

  return false;
}

function normalizeSpacing(text) {
  const lines = String(text)
    .split("\n")
    .map((line) => line.trimEnd())
    .filter((line) => !isLegacyDivider(line))
    .filter((line) => !isLegacyHeaderOrFooter(line));

  const compactLines = [];

  for (const line of lines) {
    const previousLine = compactLines[compactLines.length - 1];

    if (line === "" && previousLine === "") {
      continue;
    }

    compactLines.push(line);
  }

  return compactLines.join("\n").trim();
}

function formatHelpMessage(content, topicKey = "default") {
  const body = normalizeSpacing(content);
  const [greetingLine, supportLine] = getRandomGreetingLines();
  const introLine = getRandomIntro(topicKey);
  const bodyLines = body.split("\n");
  const visibleTitle = bodyLines[0] || "";
  const hiddenBody = bodyLines.slice(1).join("\n").trim();

  return [
    greetingLine,
    supportLine,
    `${introLine}`,
    "",
    divider,
    visibleTitle,
    divider,
    hiddenBody ? readMoreSeparator : "",
    hiddenBody ? "" : "",
    hiddenBody,
    hiddenBody ? divider : "",
    "",
    getRandomCuteFooter()
  ].filter((line, index, array) => {
    if (line !== "") {
      return true;
    }

    return array[index - 1] !== "";
  }).join("\n");
}

const helpMenuText = [
  "#0   > Rules",
  "#1   > Sejarah Pendirian Guild",
  "#2   > Arti Guild",
  "#3   > Buff Guild",
  "#4   > Reward Guild",
  "#5   > List Birthday Guild",
  "",
  "#6   > Xtall Master",
  "",
  "#7   > List Xtall Event",
  "#8   > Bahan MQ",
  "#9   > Perluas Tas",
  "#10 > Tips Refine",
  "#11 > Kode Buff Player Toram",
  "#12 > Leveling Char",
  "#13 > Leveling Prof / Kemahiran Tempa",
  "#14 > Leveling Prof / Kemahiran Padu",
  "#15 > Info Seputar Pet",
  "#16 > Pengaruh Status Pada Karakter",
  "#17 > Detail Ailment & Interupt",
  "#18 > Potensial Equipment",
  "#19 > Tips Raid",
  "#20 > Panduan Newbie",
  "",
  "#98 > Kata Mutiara Sepuh",
  "#99 > Tes Kehokian"
].join("\n");

const topicReplies = {
  "#0": [
    "Welcome to Force Knight",
    "",
    "Berdiri Sejak: 21-02-2021",
    "",
    "Info Seputar Force Knight:",
    "https://linktr.ee/ForceKnightGuild",
    "",
    "Link Discord:",
    "https://discord.gg/nQf63nprKW",
    "",
    "Link drive guild untuk melihat Dokumentasi:",
    "https://drive.google.com/drive/folders/1lsaHilMM-MNmwQ-7gPmZGOX0jTTyAoCM",
    "",
    "Youtube untuk Guide:",
    "https://youtube.com/@forceknightguild?si=ZcPzEem9TqVfOPIR",
    "",
    'Ketik "Help" untuk menggunakan bot guild',
    "",
    "Seragam: Baju Pesta Dirgahayu III A5B5C54",
    "Gathering: Setiap Tgl 21, 20.30 wib",
    "Raid Guild: Setiap Hari Sabtu, 20.30 wib (kondisional)",
    "Peminjaman Up Xtall: Lapor di Discord,",
    "Batas pengembalian H+1 peminjaman Xtall, jam 23.59 WIB, Telat denda 250k/hari per 1 xtall",
    "",
    "RULES",
    "1. Jika member guild sudah full (89/89), maka ada batas off maksimal 15 hari.",
    "2. Bagi yang on toram harap mengikuti acara guild (seperti gathering & raid).",
    "3. Syarat new member mendapatkan seragam guild: 1) ikut gath 1x untuk mendapatkan seragam guild tanpa dye (belum diwarnai). 2) ikut gath 2x untuk penukaran seragam ber dye A5B5C54.",
    "4. Bagi yang telah diberikan seragam beserta Dye: Apabila ketika gathering tidak mengenakan seragam tersebut (dikarenakan hilang atau lainnya), maka buatlah sendiri seragam yang serupa."
  ].join("\n"),
  "#1": [
    "Fuuka-chan",
    "",
    "TimeLine Berdirinya Guild",
    "━━━━━━━━━━━━━━━━━━",
    "",
    "Juli 2020",
    "Petualang bernama Master-A masuk ke dunia Toram.",
    "",
    "Oktober 2020",
    "Master-A bertekad untuk membentuk guild.",
    "",
    "November 2020",
    "Pembuatan nama guild Force Knight.",
    "",
    "21 Februari 2021",
    "Pendirian Guild Force Knight bersamaan dengan Perayaan ulangtahun Master-A",
    "",
    "21 Oktober 2021",
    "Peresmian dan perombakan susunan pengurus guild",
    "",
    "Guild Force Knight didirikan pada tanggal 21 Februari 2021 oleh Master-A selaku Guild Master (GM) dengan dibantu oleh 7 rekan pendiri terdahulu. Beberapa kali guild ini mengalami perombakan posisi Vice Guild Master (VGM). Saat ini terdapat 4 VGM sebagai berikut: Moxielly, Revzeniy, Atma Harsa, Squeshy",
    "━━━━━━━━━━━━━━━━━━",
    "Fuuka imut Fuuka dieum"
  ].join("\n"),
  "#3": [
    "Fuuka-chan",
    "",
    "Arti Guild",
    "━━━━━━━━━━━━━━━━━━",
    "",
    "Nama Guild",
    "Force Knight artinya kekuatan ksatria",
    "",
    "Logo Guild",
    "Maknanya menggambarkan beragam job. Pada logo guild terdapat ksatria yang dibelakangnya dua pedang (kekuatan fisik jarak dekat), dua tongkat (kekuatan sihir), dan satu panah (kekuatan fisik jarak jauh). Kesimpulannya bisa semua jenis job",
    "",
    "Bot Guild",
    "Nama Fuuka terdapat Huruf F & K merupakan awal huruf dari Force & Knight"
  ].join("\n"),
  "#4": [
    "Fuuka-chan",
    "",
    "Reward Guild",
    "Kondisional yaa, bisa ada maupun tidak ada",
    "━━━━━━━━━━━━━━━━━━",
    "",
    "1. Ikut Gathering",
    "Ayo Ramaikan Tanggal 21 setiap bulan nya, akan diadakan games/giveaway",
    "Reward: Menyesuaikan",
    "",
    "2. Raider",
    "Ikut dalam setiap raid yang akan diselenggarakan tiap Hari Sabtu (Kondisional).",
    "Reward: Partisipan 1M Spina, Tank & Support & Attacker +1M Spina",
    "",
    "*Harap lakukan guild quest untuk mengumpulkan medal, jika quest tidak terpenuhi > kurang medal > gabisa raid",
    "",
    "3. Guild Quester",
    "Ngerjain sendiri: 100k per 1 quest",
    "Bahan disiapin: 50k per 1 quest",
    "",
    "4. Kontri Booster",
    "Request ke Pengurus untuk mengaktifkan booster +2 (jika Point Kontri cukup)",
    "━━━━━━━━━━━━━━━━━━",
    "Fuuka Imut Kannn"
  ].join("\n"),
  "#5": [
    "Fuuka-chan",
    "",
    "List Birthday",
    "━━━━━━━━━━━━━━━━━━",
    "Januari",
    "",
    "Februari",
    "13 = Revzeniy",
    "21 = Master-A",
    "",
    "Maret",
    "",
    "April",
    "",
    "Mei",
    "",
    "Juni",
    "07 = Shiroyuuki",
    "21 = AesirMc",
    "",
    "Juli",
    "",
    "Agustus",
    "",
    "September",
    "",
    "Oktober",
    "",
    "November",
    "",
    "Desember",
    "",
    "━━━━━━━━━━━━━━━━━━",
    "Happy Birthday Kalian Semua"
  ].join("\n"),
  "#6": [
    "Fuuka-chan",
    "",
    "Xtall Master",
    "━━━━━━━━━━━━━━━━━━",
    "Peminjaman Up Xtall: Lapor di Discord.",
    "Waktu Peminjaman: Menyesuaikan waktu luang Master-A",
    "━━━━━━━━━━━━━━━━━━",
    "🔴 Xtall Weap",
    "- Megiston Sang Juara - VII -> (Megiston Sang Juara VIII)",
    "- Armasit -> (Kadal Bunga)",
    "- Zahhak Machina - Penyihir Besi Bercakar -> (Ratu Rosemee)",
    "- Ganglef -> (Kepiting Bulan Besar)",
    "- Dango Iblis -> (Fubbit)",
    "- Armasit -> (Diark)",
    "- Putri Natal Berbaju Hitam -> (Gusti Ilusi Melodi)",
    "- Zega - IX -> (Zega X)",
    "- Metasrigala - Cakar Kucing Kissatpam -> (Neo Magi Filecia)",
    "- Zolban - Repthon - Naga Trompet Reguita -> (Doreminador)",
    "- Pedang Neo Maton -> (Pedrio)",
    "- Mbah Dukun Usasama -> (Mbah Dukun Usasama II)",
    "- Potum pahlawan - III -> (Potum Pahlawan IV)",
    "- Pomie Chan - II -> (Pomie Chan III)",
    "---",
    "- Ksatria Buruk Dusta - Gwaimol - Hexter -> (Don Profundo)",
    "- Ganglef - Machina Tiran - Vulture - Mimyugon -> (Bakuzan)",
    "- Golem Pillar - Machina Ultima - Vlam si Naga Api -> (Supreme Evil Crystal Beast)",
    "- Iblis kristal jahanam - Shampy - Irestida -> (Vatudo)",
    "- Pedang Sihir Iblis -> (Kristal berlumur Darah)",
    "- Imitacia - Finstern - Oculasignio -> (Menti)",
    "- Imitator - Mardula - Velum -> (Deformis)",
    "---",
    "- Gerbang Iblis > Mozto Machina > Pisteus - Naga Jahat Fazzino -> (Rondine)",
    "- Arbogazella -> (Doridodi)",
    "- Zahhak Machina - Penyihir Besi Bercakar -> (Naga Meraung Bovinari)",
    "- Zolban - Repthon - Naga Trompet Reguita -> (Goudvis)",
    "- Golem Galian - Builder Golem -> (Meduso)",
    "- Dukun Lapin -> (Momok Gelembung)",
    "",
    "🟢 Xtall Armor",
    "- Pilz Erosi -> (Tulin Max)",
    "- Gopherga -> (Yuveria)",
    "- Usakichi - Usami -> (Usamochi)",
    "- Sibylares -> (Bemoz)",
    "- Noeliel - Noeliel si Patung Es Suci - Kucing Yule -> (Gegner)",
    "- Sosok Jahat - Velly Hitam -> (Glocke)",
    "- Kruztor -> (Kruztor II)",
    "- Cerabes - Mimesia - Sakura Merah Jelita - Baavgai -> (Bajinja / Ninja Persik Hitam)",
    "- Permaisuri Besi -> (Merzehal)",
    "- Dr. Leonardo -> (Dr. Leonardo II)",
    "- DX Fighter -> (DX Fighter II)",
    "---",
    "- Arachnidemon - Zapo -> (Puiet)",
    "- Cerberus - Pyxtica - Gemma -> (Meteora)",
    "- Pilz Erosi -> (Filrocas)",
    "- Nemopirania -> (Skelerow)",
    "---",
    "- Bos roga - iconos - ornlarf - roga safir - Ferzen -> (Walican)",
    "- Ifrid - Mama Fluck - Gordel -> (Biskyva)",
    "- Forestia -> (Glaucius)",
    "- Quassar Jahanam -> (Mata Jahanam)",
    "- Tortuga - Daddy Finpen - Capo Profundo -> (Landak Penggali Gelap)",
    "- Golem Preman -> (Naga Langkisau)",
    "- Colon Komandan -> (Goleps)",
    "- Elang Zamrud - Jamur Super Mampus -> (Dandolion)",
    "",
    "🟡 Xtall Add",
    "- Naga Sabana Yelb - Roda Kelana -> (Roda Kelana Neo)",
    "- Adaro -> (Monster Dasar Laut)",
    "- Tengkorak Emas - Solopy -> (Potum Hiu)",
    "- Pumpking - Jeila - Zoe - Zarth - Neewollah -> (Eripmav)",
    "- Naga Senja - Baphomela -> (Bayangan Biru Tafakur)",
    "- Potum Surya -> (Potum Bintang Top)",
    "- Biskuit Buatan Tangan - Alfenix -> (Zucotto Goblin)",
    "- Eidenliebe -> (Garnache)",
    "- Candela - II -> (Amargon)",
    "- Chocolate Ooze & II -> (Soldner)",
    "- Iconos Emas - Kodok Riang - Gem Mas -> (Goldian)",
    "- Gespenst II -> (Stellar Ooze)",
    "- Ratu Kuno -> (Ratu Kuno II)",
    "- Raja Kerbau - Paduka Raja Kerbau -> (Paduka Raja Kerbau II)",
    "- Raja Kerbau - (Pillow Kitagawa) -> (Pillow Kitagawa II)",
    "- Jibril - II -> (Jibril III)",
    "- Ayah Yashiro Azuki -> (Raja Kegelapan)",
    "- Narumi Hina -> (Ibu Yashiro Azuki II)",
    "---",
    "- Naga Sabana Yelb - Roda Kelana -> (Gordo)",
    "- Dusk Machina -> (Trocostida)",
    "- Zyvio -> (Gula)",
    "- Altoblepas -> (Jiva)",
    "---",
    "- Grylle - Fantica -> (Obsia)",
    "- Celeng Raksasa -> (Mega Alpoca)",
    "- Warmonger - Proto Leon - Raja Piton -> (Naga Membara Igneus)",
    "- Seltirio -> (Tardigrademon)",
    "- Kapten Karatan -> (Exdocus)",
    "",
    "🟣 Xtall Ring",
    "- Kristal jahat -> (Kristal Misterius)",
    "- Violangkara -> (Violangkara G)",
    "- Zeagrysta -> (Monster Kristal Abisal)",
    "- Seele Zauga -> (Seele Zauga II)",
    "- Dark Mushroom -> (Teertocrit)",
    "- Viscum - Deniala - Amalgam - Crysmort -> (Breeta)",
    "- Kristal Jahat - Tapir - Patissia -> (Sicanokami)",
    "- Volgagon -> (Etoise)",
    "- Potumotter -> (Potumotter)",
    "---",
    "- Ooze - Lalvada -> (Dominaredor)",
    "- Venena - II -> (Humida)",
    "- Bexiz - Zelbuse -> (Naga Milisi Turba)",
    "---",
    "- Tentara Batu -> (Memecoleous)",
    "- Baron Bling-Bling -> (Roh Orang Mati)",
    "- Violaccoon - Ketua Bandit Gurun -> (Arpoon)",
    "",
    "🔵 Xtall Umum",
    "- Bos Colon -> (Kijimu Agung)",
    "- Goblin Bos -> (Colon Bos)",
    "- Lobalawar - Melancia -> (Chiromina)",
    "- Lynx Mithurna -> (Kuffania)",
    "- Shawle -> (Dutannen)",
    "- Nurethoth -> (Nuthoreth)",
    "- Potum Raja - Potum Platina -> (Potum Kue)",
    "- Gerumi -> (Gerumi Kuat)",
    "---",
    "- Metal Stinger - Kapten Lyark Spesialis - Ageladanios -> (Wiltileaf)",
    "- Odelon Machina - Pret -> (Lilicarolla)",
    "- Gravicep - Naga Abu Merah Rudis -> (Gioco)",
    "- Minotaur - Rhinosaurus -> (Wild Beast Lixi)",
    "- Naga Beringas Decel - York - Tuscog - Bayangan Hitam -> (Torexesa)",
    "- Nurethoth - Guignol - Golem Satpam -> (Piscruva)",
    "- Coryn Besar - Seraph Machina -> (Limacina)",
    "- Flare Volg -> (Charugon)",
    "---",
    "- Gespenst - Salamander -> (Bullamius)",
    "- Ksatriaja - Volotur -> (Brassozard)",
    "- Crimsosh -> (Amoeba Machina)",
    "- Aranea - Blazingur -> (Brahma)",
    "- Bos Petapa Kadal -> (Orictoceras)",
    "- Caspy -> (Vevela)",
    "━━━━━━━━━━━━━━━━━━",
    "Fuuka Imut Fuuka Dieum"
  ].join("\n"),
  "#7": [
    "Fuuka-chan",
    "Bot Master-A",
    "",
    "List Xtall Event",
    "━━━━━━━━━━━━━━━━━━",
    "Xtall Event Anniv",
    "1. Sang juara megiston - VIII",
    "2. Roda kelana neo",
    "3. Kadal bunga",
    "4. Kristal misterius",
    "5. Violangkara G",
    "6. Ratu Rosemee",
    "7. Tulin Max",
    "8. Kijimu Agung",
    "9. Colon Boss",
    "10. Potum Ultra",
    "---",
    "Xtall Event Summer",
    "1. Titeres",
    "2. Gopherga > Yuveria",
    "3. Adaro > Monster Dasar Laut",
    "4. Kapten Amiya",
    "5. Gurita Raksasa",
    "6. Semangat Musim Panas",
    "7. Fallburrow",
    "8. Zegrysta > Monster Kristal Abisal",
    "9. Stormun",
    "10. Potum Hiu",
    "---",
    "Xtall Event Otsukimi",
    "1. Usakichi > Usami > Usamochi",
    "2. Kepiting Bulan",
    "3. Dango iblis > Fubbit",
    "---",
    "Xtall Event Persimmon coryn",
    "1. Auvio",
    "2. Auberkasa",
    "---",
    "Xtall Event Halloween",
    "1. Pumpking > Jeila > Zoe > Zarth > Neewollah > Eripmav",
    "2. Penyihir Naga",
    "3. Gagak Penyihir Hebat",
    "4. Badut Tukang Sandiwara",
    "5. Phantom Wisp",
    "6. Tikus Kecil Ajaib",
    "7. Serigala Merah Mata Satu",
    "8. Teertocrit",
    "9. Sibylares > Bemoz",
    "10. Syaman Hitam Hutan Hantu",
    "11. Melancia > Chiromina",
    "12. Sinar Rembulan Purba",
    "13. Kuffania",
    "14. Jejak Bayang Nan Jauh",
    "15. Olobaid",
    "16. Bayangan Iblis Mayat Ksatria",
    "---",
    "Xtall Event Natal",
    "1. Naga Senja > Baphomela > Bayangan Biru Tafakur > Shawle Terlarang",
    "2. Noeliel > Noeliel si Patung Es Suci > Kucing Yule > Gegner",
    "3. Shawle > Dutannen",
    "4. Sosok jahat > Velly Hitam > Glocke",
    "5. Putri Natal Berbaju Hitam > Gusti Ilusi Melodi",
    "6. Iluminator",
    "7. Bayangan Jeritan",
    "8. Diark",
    "9. Granpromus",
    "10. Potum Bintang Top",
    "---",
    "Xtall Event Megiston Road",
    "1. Zega - IX",
    "2. Felien > Neo Lefina Jahat",
    "3. Metasrigala > Cakar Kucing Kissatpam > Neo Magi Filecia",
    "4. Kapten Sihir & si B",
    "5. Doreminador",
    "6. Seele Zauga II",
    "7. Dango Sakura",
    "8. Sakura Musim Semi",
    "---",
    "Xtall Event Otoshidama",
    "1. Grand Pojo (Ayam)",
    "2. Perro (Anjing)",
    "3. Kohaku Lil Boar (Babi)",
    "4. Omochi (Tikus)",
    "5. Bovinio (Kerbau)",
    "6. Purro (Macan)",
    "7. Lunadore (Kelinci)",
    "8. Dratone (Naga)",
    "9. Ophy (Ular)",
    "10. Ponier (Kuda)",
    "---",
    "Xtall Event Valentine",
    "1. Chocolate Ooze - II > Soldner",
    "2. Eidenliebe > Garnache > Erkuch",
    "3. Jeandoux",
    "4. Mieli",
    "5. Goblin Makelar > Velcaroy",
    "6. Amargon",
    "7. Sicanokami",
    "8. Pelulu Raksasa",
    "---",
    "Xtall Event White Day",
    "1. Candela - II",
    "2. Biskuit Buatan Tangan > Alfenix > Zucotto Goblin",
    "3. Mercy",
    "4. Kruztor - II",
    "5. Lefina Jahat > Sanburmon",
    "6. Magi Filecia",
    "7. Bangrudom",
    "---",
    "Xtall Event Hanami",
    "1. Viscum > Deniala > Amalgam > Crysmort > Breeta",
    "2. Marchitar",
    "3. Super Night Mushroom",
    "4. Cerabes > Mimesia > Sakura Merah Jelita > Baavgai > Bajinja / Ninja Persik Hitam",
    "---",
    "Xtall Event Golden Week",
    "1. Iconos Emas > Kodok Riang > Gem Mas > Goldian",
    "---",
    "Xtall Event Hdb",
    "1. Raja Kerbau > Paduka Raja Kerbau - II",
    "2. Raja Kerbau > Pillow Kitagawa - II",
    "3. P. Ava",
    "4. Ratu Kuno II",
    "5. Permaisuri Besi > Merzehal",
    "6. Gespenst II > Stellar Ooze",
    "7. Pedang Neo Maton > Pedrio",
    "8. Patissia",
    "9. Volgagon > Etoise",
    "10. Altadar",
    "11. Castilia",
    "12. Mbah Dukun Usasama - II",
    "13. Stellar Ooze II",
    "---",
    "Xtall Event Download",
    "1. Potum Pahlawan - IV",
    "2. Potum Platina > Potum Kue",
    "3. Pomie-chan - III",
    "4. Doktor Pom Pom",
    "5. Potumotter - III",
    "---",
    "Xtall Collab",
    "1. Gerumi > Gerumi Kuat",
    "2. Yashiro Azuki",
    "3. Ibu Yashiro Azuki",
    "4. Ayah Yashiro Azuki > Raja Kegelapan",
    "5. Narumi Hina > Ibu Yashiro Azuki II",
    "6. Dr. Leonardo - II",
    "7. Dx Fighter - II",
    "8. Jibril - III",
    "9. Dewa Mesin Maple",
    "━━━━━━━━━━━━━━━━━━",
    "Fuuka Imoet Fuuka Kawaii"
  ].join("\n"),
  "#8": [
    "BAHAN MQ",
    "",
    "BAB 1 :",
    "- Daun Colon (Colon Leaf) x5",
    "- Sisik Naga (Hard Dragon Skin) x2",
    "- Daging Domba (Lamb Meat) x1",
    "- Sulur (Vine) x3",
    "- Paruh Tebal (Thick Beak) x3",
    "- Sayap Peri (Fairy Feather) x3",
    "",
    "BAB 2 :",
    "- Koin Ksatria (Swordsman Stone Coin) x20",
    "",
    "BAB 3 :",
    "- Daging Tikus Pasir (Sand Mole Meat) x1",
    "- Cakar binatang buas (Beast Claw) 3x",
    "- Kulit Kodok Pasir (Sand Frog skin) x5",
    "- Taring Bergerigi (Jagged Fang) x10",
    "- Kristal Saham (Saham Crystal) x5",
    "- Permata Jiwa (Spiritual Gemstone) x1",
    "",
    "BAB 8 :",
    "- Anggur Rokoko (Rokoko Grape) x5",
    "",
    "BAB 9 :",
    "- Kayu Labilans (Labilans Wood) x10",
    "",
    "BAB 11 :",
    "- Tanduk Patah ( Broken horn) x20",
    "",
    "BAB 12 :",
    "- Biji Berkembang (growing ore ) x5",
    "- Batu Jabali (jabali stone) x5",
    "",
    "BAB 14 :",
    "- Kulit Tebal Berlendir (Slimy Thick Skin) x20",
    "- Akar Melilit (Tangled Roots) x10",
    "- Kayu Menabra (Menabra Wood) x10",
    "",
    "BAB 15 :",
    "- pupuk keruh (stagnant fertilizer)x10"
  ].join("\n"),
  "#9": [
    "Fuuka-chan",
    "",
    "List Bahan Untuk Upgrade Slot Tas by guild Force Knight",
    "━━━━━━━━━━━━━━━━━━",
    "◻️*50-51*",
    "- Kulit Colon x1 (Colon; Tanah Pembangunan) = ±1.000",
    "",
    "◻️*51-52*",
    "- Kulit Berkualitas x1 (Lavarca; Dataran Rakau) = ±3.500",
    "",
    "◻️*52-53*",
    "- Spina x1.000",
    "",
    "◻️*53-54*",
    "- Kulit Minotaur x1 (Minotaur; Kuil Runtuh: Area Terlarang) = ±12.000",
    "- Pecahan Kristal Jingga x1 (Cobre; Danau Icule) = ±6.000",
    "",
    "◻️*54-55*",
    "- Kulit Anjing Hutan x1 (Anjing Hutan; Hutan Marbabo: Bagian Dalam) = ±5.000",
    "- Lencana Goblin x1 (Boss Goblin; Gua Ribisco: Bagian Dalam) = ±7.500",
    "",
    "◻️*55-56*",
    "- Spina x2.000",
    "",
    "◻️*56-57*",
    "- Bulu Mochelo x1 (Mochelo; Lereng Merapi A3) = ±12.000",
    "- Kain Linen x10 (Crow Killer; Dusun Douce) = ±60.000",
    "",
    "◻️*57-58*",
    "- Bulu Naga Giok x1 (Forestia; Tanah Kaos) = ±20.000",
    "- Tanduk Berkualitas x10 (Bandot; Tanah Tinggi Yorl) = ±300.000",
    "",
    "◻️*58-59*",
    "- Sabuk Bos Roga x1 (Boss Roga; Gua Bawah Tanah Saham: Ujung) = ±15.000",
    "- Kain Beledu x10 (Orc Petarung; Gua Bawah Tanah Saham) = ±57.000",
    "",
    "◻️*59-60*",
    "- Spina x4.000",
    "",
    "◻️*60-61*",
    "- Cakar Beruang x2 (Violaccoon; Padang Darkanon) = ±90.000",
    "- Sheeting Fabric x20 (Cassy; Makam Ratu Kuno: Area 2) = ±6.000",
    "",
    "◻️*61-62*",
    "- Rantai Kukuh x2 (Pendekar Bertopeng; Tanah Tinggi Pertanian) = ±6.000",
    "- Kain Polister x20 (Boneka Pengembara; Kota Hilang) = ±70.000",
    "",
    "◻️*62-63*",
    "- Sisik Naga Sabana x2 (Naga Sabana Yelb; Desa Albatif) = ±5.000",
    "- Kulit Serigala Alien x20 (Serigala Luar; Gerbang Dunia Lain: Area 1) = ±450.000",
    "",
    "◻️*63-64*",
    "- Spina x8.000",
    "",
    "◻️*64-65*",
    "- Jubah Sobek x2 (Goovua; Gurun Akaku: Bukit) = ±60.000",
    "- Kulit Tupai x20 (Rodentail; Maia Diela) = ±130.000",
    "",
    "◻️*65-66*",
    "- Tanduk Elang Zamrud x2 (Elang Zamrud; Teras Kerikil) = ±22.000",
    "- Bulu Kambing x20 (Koza; Jurang Dunkel) = ±170.000",
    "",
    "◻️*66-67*",
    "- Sayap Naga Senja x2 (Naga Senja; Benteng Solfini: Atap) = ±270.000",
    "- Bulu Halus x20 (Little Snow Boar; Lembah Es Polde) = ±20.000",
    "",
    "◻️*67-68*",
    "- Spina x16.000",
    "",
    "◻️*68-69*",
    "- Rantai Penyucian x2 (Cerberus; Mata Air Kelahiran: Puncak) = ±4.000",
    "- Kain Goyah x20 (Jewel Eye; Mata Air Kelahiran: Tengah) = ±130.000",
    "",
    "◻️*69-70*",
    "- Benang Aranea x2 (Aranea; Taman Sublimasi: Pusat) = ±120.000",
    "- Benang Laba-Laba Kecil x20 (Aramia; Taman Sublimasi: Area 2) = ±120.000",
    "",
    "◻️*70-71*",
    "- Kain Dewi Tiruan x3 (Imitacia; Istana Gelap: Aula Besar) = ±22.000",
    "- Kain Apung x10 (Flying Executioner; Buaian Prajurit) = ±220.000",
    "- Tapak Lembut x20 (Bunny Summoner; Sungai Kegelapan) = ±28.000",
    "",
    "◻️*71-72*",
    "- Surai Hewan Iblis x3 (Memecoleous; Istana Gelap: Area2) = ±825.000",
    "- Bantalan Tapak Keras x10 (Manticore; Istana Gelap: Area1) = ±100.000",
    "- Bulu Bayangan Hitam x20 (Shadow Fly; Istana Gelap: Area1) = ±233.000",
    "",
    "◻️*72-73*",
    "- Spina 32.000",
    "",
    "◻️*73-74*",
    "- Bulu Tapir x3 (Tapir; Graben Membara: Permukaan) = ±19.000",
    "- Bulu Kaku x10 (Wooly; Graben Membara: Permukaan) = ±100.000",
    "- Minyak Anti Karat x20 (Ornis Demi Machina; Garis Pertahanan Artileri Otomatis) = ±217.000",
    "",
    "◻️*74-75*",
    "- Kain Kuno x3 (Proto Leon; Reruntuhan Singolaire: Lantai 3) = ±309.000",
    "- Kulit Pohon Lunak x10 (Floral Bee; Situs Simcracker) = ±50.000",
    "- Rambut Potum Kotor x20 (Slum Potum; Klaspe Kumuh) = ±100.000",
    "",
    "◻️*75-76*",
    "- Tulang Raksasa Merah x3 (Dusk Machina; Pabrik Demi Machina Kecil: Area 2) = ±1.067.000",
    "- Mantel Hitam Sobek x10 (Rugos Demi Machina; Pabrik Demi Machina Kecil: Area 2) = ±40.000",
    "- Rantai Putus x20 (Machina Penyiksa; Pabrik Demi Machina Kecil: Area 2) = ±45.000",
    "",
    "◻️*76-77*",
    "- Sisik Chimera x3 (Mozto Machina; Pabrik Demi Machina Besar: Bagian Terdalam) = ±123.000",
    "- Benda Pendar Aneh x10 (Horn Machina; Pabrik Demi Machina Besar) = ±120.000",
    "- Tentakel Tangguh x20 (Ledon Machina; Pabrik Demi Machina Besar) = ±158.000",
    "",
    "◻️*77-78*",
    "- Spina x64.000",
    "",
    "◻️*78-79*",
    "- Jubah Roh Hutan x3 (Lalvada; Hutan Monster: Bagian Dalam) = ±116.000",
    "- Taring Tanaman x10 (Nepenthe; Hutan Monster) = ±4.500",
    "- Kain Felt x20 (Naga Boneka; Mansion Lufenas) = ±455.000",
    "",
    "◻️*79-80*",
    "- Aloi Lyark x3 (Gwaimol; Penjara Cuervo: Atap) = ±190.000",
    "- Baju Penjaga Robek x10 (Sipir Lyark; Penjara Cuervo: Lantai 2) = ±51.000",
    "- Kain Lembu x20 (Lyark Spesialis; Laboratorium Brahe: Area 2) = ±15.000",
    "",
    "◻️*80-81*",
    "- Kain Bercahaya x4 (Seraph Machina: Menara Penembus Bumi: Sisi Dalam) = ±155.000",
    "- Kulit Sintetis Rusak x20 (Lyark Brawler: Sekitar Alun-Alun Droma) = ±38.000",
    "- Cawat Pengeksekusi x20 (Volo: Sekitar Alun-Alun Droma Area 2) = ±68.000",
    "",
    "◻️*81-82*",
    "- Potongan Baju K. Kecil x4 (Venena: Istana Ultimea: Takhta) = ±98.000",
    "- Pecahan Zirah Keras x20 (High Tigris: Istana Ultimea Gudang Demi Machina) = ±100.000",
    "- Kulit Ular x20 (Ular Kolam: Reservoir Copia) = ±110.000",
    "",
    "◻️*82-83*",
    "- Spina x100.000",
    "",
    "◻️*83-84*",
    "- Kulit Mama Fluck x4 (Mama Fluck: Gua Pelupa) = ±36.000",
    "- Daun Besar Colon x20 (Leedle Colon: Dataran Rokoko) = ±31.000",
    "- Bulu Garis Vertikal x20 (Rakun Tambun: Hutan Curonne) = ±146.000",
    "",
    "◻️*84-85*",
    "- Kain Rohani Mardula x4 (Mardula: Serambi Dewa Berkah) = ±180.000",
    "- Kain Berkilau Misterius x20 (Malaikat Gelembung: Koridor Heresi/Kuil Para Dewa/Serambi Dewa Pembangunan/Serambi Dewa Istimewa) = ±9.000",
    "- Bulu Kelabu x20 (Haliabubo: Reruntuhan G. Mithurna: Koridor Atas) = 107.000",
    "",
    "◻️*85-86*",
    "- Mantel Carbuncle x4 (Carbuncle: Serambi Dewa Pembangunan) = ±61.000",
    "- Kain Rajut x20 (Malaikat Gelembung: Koridor Heresi/Kuil Para Dewa/Serambi Dewa Pembangunan/Serambi Dewa Istimewa) = ±51.000",
    "- Ekor Beruang Berkantong x20 (Oddy: Kuil Para Dewa: Area 4/Serambi Dewa Pembangunan) = ±41.000",
    "",
    "◻️*86-87*",
    "- Bulu Raja Piton x4 (Raja Piton: Pegunungan Elf: Kuil) = ±988.000",
    "- Bulu Putih Lebat x20 (Bandot: Taman Es &Salju) = ±203.000",
    "- Bulu Abu Kaku x20 (Silveria: Pegunungan Elf) = ±51.000",
    "",
    "◻️*87-88*",
    "- Ingot Kuno x4 (Golem Preman: Kuil Naga Kegelapan: Tengah) = ±28.000",
    "- Taring Serigala Es x20 (Corloup: Pegunungan Elf) = ±300.000",
    "- Kain Gelap x20 (Soul Reaper: Kuil Naga Kegelapan) = ±101.000",
    "",
    "◻️*88-89*",
    "- Spina x200.000",
    "",
    "◻️*89-90*",
    "- Taring Tuscog x4 (Tuscog: Jalan Eryldan: Sekitar Hutan Ein) = ±350.000",
    "- Sutra Ulat x20 (Tikus Lumut: Hutan Ein) = ±278.000",
    "- Bulu Manusia Serigala x20 (Wolfret: Jalan Eryldan) = ±185.000",
    "",
    "◻️*90-91*",
    "- Serpihan Kayu Kuzto x5 (Kuzto; Distrik Labilans: Alun-Alun) = ±10.000",
    "- Bulu Cerpelai x20 (Satwal; Distrik Fabriska) = ±223.000",
    "- Sabuk Pinggang Misterius x30 (Moculus; Distrik Fractum: Area 1) = ±270.000",
    "",
    "◻️*91-92*",
    "- Kantong Kristal x5 (Nemopirania; Distrik Racetacula: Area 1) = ±309.000",
    "- Ekor Lembut x20 (Alpoca; Distrik Labilans) = ±100.000",
    "- Papula Kuat x30 (Toksinaria; Distrik Racetacula: Area 1) = ±105.000",
    "",
    "◻️*92-93*",
    "- Sayap Repthon x5 (Repthon; Zona Riset Delzton: Area Terdalam) = 1.545.000",
    "- Kancing Polong x20 (Colon Marquis; Reruntuhan Mansion Lufenas Tua) = ±108.000",
    "- Kain Perca Jas Panjang x30 (Gulingkar; Zona Riset Delzton: Area 1) = ±154.000",
    "",
    "◻️*93-94*",
    "- Rambut Kaisar Siluman x5 (Venena Metacoenubia; Neo Plastida) = ±488.000",
    "- Kain Merah Sobek x20 (Potum Bandit Gurun; Gurun Pasir Geist: Area 1) = ±80.000",
    "- Kulit Karatan x30 (Jasman; Reruntuhan Elban Urban) = ±34.000",
    "",
    "◻️*94-95*",
    "- Spina x300.000",
    "",
    "◻️*95-96*",
    "- Tulang Pisteus x5 (Pisteus; Pesisir Ducia: Area Terdalam) = ±231.000",
    "- Kain Fantom x20 (Flooray; Dasar Tebing Lunagent) = ±90.000",
    "- Bulu Berang-Berang Laut x30 (Lutris; Pesisir Ducia: Area 3) = ±343.000",
    "",
    "◻️*96-97*",
    "- Sayap Arachnidemon x5 (Arachnidemon; Lembah Arche: Area Terdalam) = ±13.000",
    "- Belenggu Logam x20 (Besy; Lembah Arche) = ±17.000",
    "- Kulit Ular Aneh x30 (Coofer; Reruntuhan Kota Rokoko) = ±34.000",
    "",
    "◻️*97-98*",
    "- Jangat Berlendir x5 (Datuk Nezim; Lahan Basah Nezim) = ±257.000",
    "- Kain Enty x20 (Enty; Rimba Penyihir) = ±102.000",
    "- Poros Kokoh x30 (Orang2an Sawah Seram; Rimba Penyihir: Area 2) = ±465.000",
    "",
    "◻️*98-99*",
    "- Perca Gendam Geni x5 (Hexter; Rimba Penyihir: Area Terdalam) = ±222.000",
    "- Piring Kappa x20 (Kappadon; Lahan Basah Nezim) = ±139.000",
    "- Bulu Gagak x30 (Orang2an Sawah Seram; Rimba Penyihir: Area 2) = ±62.000",
    "",
    "◻️*99-100*",
    "- Inti Latebra Menggeliat x5 (Trocostida; Nov Diela: Area 1) = ±2.150.000",
    "- Cairan Lekat x20 (Juvestida; Nov Diela: Area 1) = ±9.000",
    "- Kulit Pelik x30 (Mata Jahat; Padang Morga: Area 1) = ±102.000",
    "-----",
    "Total biaya: 17.851.500 + 727.000 = 18.578.500",
    "━━━━━━━━━━━━━━━━━━",
    "Fuuka imut selalu di hati"
  ].join("\n"),
  "#10": [
    "Tips Refine",
    "━━━━━━━━━━━━━━━━━━",
    "1. Spam Refine menggunakan bijih mithril dengan Char Full Luk sampai +S",
    "2. Refine terstruktur",
    "    1) Refine menggunakan bijih mithril dengan Char Full Luk sampai pity 1,5k",
    "    2) Jika belum +S, Lanjutkan Refine dengan Char BS Full Tec menggunakan bijih mithril sampai +C (Opsional menggunakan Orichalcum+Andeg dari +E sampai +B)",
    "    3) Lanjutkan Refine dengan Char Full Luk menggunakan Bijih Mithril sampai +S (opsional menggunakan Andeg dari +A sampai +S)",
    "",
    "NB:",
    "- 150pt = +1% Success Rate",
    "━━━━━━━━━━━━━━━━━━",
    "By: Master-A",
    "Fuuka Imut Fuuka Dieum"
  ].join("\n"),
  "#11": [
    "List Buff",
    "",
    "Max HP : 1180755",
    "Max MP : 9090903",
    "AMPR : 1234561",
    "Critical Rate : 1100000",
    "MATK : 52255555",
    "ATK : 5130123",
    "Weapon ATK : 7123456",
    "STR : 1110033",
    "INT : 9090903",
    "VIT : 5130123",
    "AGI : 7162029",
    "DEX : 9090904",
    "Physical Resist : 9090907",
    "Magic Resist : 2020505",
    "Kebal bumi : 6150029",
    "Frac Barrier : 6150029",
    "Aggro +% : 2020606",
    "Aggro -% : 1010147",
    "DTE Bumi : 4111113",
    "DTE Api : 3210106",
    "DTE Air : 7150030",
    "DTE Angin : 8080804",
    "           7257777",
    "           3149696",
    "DTE Cahaya : 6010289",
    "DTE Gelap : 6116116",
    "            5010092",
    "DTE Netral : 1234561",
    "",
    "Code buffland member/admin",
    "Mp : punkz",
    "Ampr : hsans,moung zy",
    "Watk : master-limbAd",
    "Dte earth : medzzo"
  ].join("\n"),
  "#12": [
    "Fuuka-chan",
    "",
    "List Leveling Char By Hsans",
    "━━━━━━━━━━━━━━━━━━",
    "Leveling Char Sambil MQ",
    "",
    "- Tanpa Adv Book",
    "- Exp tambahan dari MQ",
    "- Spot Farming",
    "- Nostalgia jadi babu",
    "- Langkah-langkah di buat untuk menyesuaikan Lv, Lv Boss, dan exp dari Quest",
    "",
    "\"Membuat Char baru > mulai dari awal untuk mode MQ \"",
    "",
    "• MQ dari Bab 1 > Gunung Nisel",
    "",
    "* 1 > 37 : Shell Mask > Gunung Nisel",
    "",
    "* MQ > Brutal Dragon Decel > Gunung Nisel",
    "",
    "* 37 > 57 : Bone Dragon > Makam Ratu",
    "",
    "* MQ > Lereng Merapi",
    "",
    "* 57 > 62 : Flare Volg Hard > Lereng Merapi",
    "",
    "* 62 > 74 : Flare Volg NM > Lereng Merapi",
    "",
    "* MQ > Gurun Akuku",
    "",
    "* 74 > 87 : Metal Stinger > Gurun Akuku",
    "",
    "* MQ > Elscaro",
    "",
    "* 87 > 96 : Flare Volg Ulti > Lereng Merapi",
    "",
    "* 96 >104 : Don Yeti > Lembah Es Polde (atau >113 dan skip Masked)",
    "",
    "* 104 > 114 : Masked Warior Ulti > Lahan Pertanian",
    "",
    "* MQ > Mata Air Kelahiran",
    "",
    "* 114 > 124 : Cerberus NM > Mata Air Kelahiran",
    "",
    "* MQ > Sungai Kegelapan",
    "",
    "* 124 > 133 : Lapin The Necromancer > Sungai Kegelapan",
    "",
    "* MQ > Bab 6 \"Duo Technista\"",
    "",
    "* 134 > 144 : Cerberus Ulti > Mata Air Kelahiran",
    "",
    "* MQ > Pabrik Demi Machina Besar",
    "",
    "* 144 > 150 : Odelon Machina (Bisa di skip) > Pabrik Demi Machina Besar",
    "",
    "* MQ > Hutan Monster",
    "",
    "* 144 > 157 : Super Death Mushroom > Hutan Monster",
    "",
    "* MQ > Mansion Lufenas",
    "",
    "* 157 > 162 : Commander Golem > Mansion Lufenas",
    "",
    "* MQ > Istana Ultimea : Tahta",
    "",
    "* 162 > 179 : Venena NM > Istana Ultimea : Tahta",
    "",
    "* 179 > 182 : Altoblepas > Dataran Rakoko",
    "",
    "* 182 > 199 : Venena Ulti > Istana Ultimea : Tahta",
    "",
    "* MQ > Kuil Naga Kegelapan",
    "",
    "* 199 > 210 : Finstern The Dark Dragon > Kuil Naga Kegelapan",
    "",
    "* MQ > Distrik Labilans",
    "",
    "* 210 > 227 : Kuzto Ulti > Distrik Labilan",
    "",
    "* 227 > 230 : Mini Boss Espectro > Lembah Arche",
    "",
    "* MQ > Lembah Arche",
    "",
    "* 230 > 241 : Arachnidemon Ulti > Lembah Arche",
    "",
    "* MQ > Hutan Lindung",
    "",
    "* 243 > 250 : Ferzen The Rock Dragon > Hutan Lindung",
    "",
    "* MQ > Zona Kemudi",
    "",
    "* 255 > 265 : Trickster Dragon Mimyugon NM > zona Kemudi",
    "",
    "* MQ > Aquacity",
    "",
    "* 270 > 287 : Trickster Dragon Mimyugon Ulti > Zona Kemudi",
    "",
    "* MQ > Mulgoon > Dataran Menabra",
    "",
    "* 291 > 303 : Mulgoon NM > Dataran amenabra /291 > 296 : Capo Profundo > Kawasan Terlantar",
    "",
    "* 296 > 309 : Wiltileaf > Reruntuhan Desa Eumano",
    "",
    "* 309 - 323 : Mulgoon Ulti > Dataran Menabra",
    "",
    "Note :",
    "",
    "> Tingkat kesulitan Tinggi (harap minta bantuan teman / guild)",
    "> Exp sistem > Selisih lv > Exp modifier",
    "",
    "0 > 1100%",
    "1 > 1000%",
    "2 > 900%",
    "3 > 700%",
    "4 > 300%",
    "5-9 > 100%",
    "10-19 > -1%/lv.",
    "",
    "Sumber : Coryn club",
    "V 0.1.3"
  ].join("\n"),
  "#13": [
    "Fuuka-chan",
    "",
    "LEVELING PROF/KEMAHIRAN TEMPA",
    "━━━━━━━━━━━━━━━━━━",
    "Ketik Kodenya yaaa....",
    "#13a > Char BS Vit Tec",
    "#13b > Char Full Tec",
    "#13c > Char BS low / non Tec"
  ].join("\n"),
  "#14": [
    "Fuuka-chan",
    "",
    "LEVELING PROF/KEMAHIRAN PADU",
    "━━━━━━━━━━━━━━━━━━",
    "Char Full Tec",
    "Skill Padu Item Level 10",
    "Siapkan: Madu Enak 6-10 stk",
    "",
    "Simple:",
    "1. Lvl 1-15 craft save point",
    "2. Madu Enak 1stak > Nektar > Revita III",
    "3. Madu Enak 1stak > Nektar > Revita IV",
    "4. Madu Enak 1stak > Nektar > Revita V",
    "5. Madu Enak 1stak > Nektar > Sirup Nektar > Revita VII",
    "6. Madu Enak 1stak > Nektar > Sirup Nektar > Revita VII",
    "7. Madu Enak 1stak > Nektar > Sirup Nektar > Revita VII",
    "",
    "Detail:",
    "Lvl 1-15",
    "Save point",
    "Bahan: Mats Mana",
    "",
    "Lvl 15-28",
    "Nektar",
    "Bahan: Madu Enak 1stak",
    "",
    "Lvl 28-40",
    "Revita III",
    "Bahan: Nektar",
    "",
    "Lvl 40-53",
    "Nektar",
    "Bahan: Madu Enak 1stak",
    "",
    "Lvl 53-65",
    "Revita IV",
    "Bahan: Nektar",
    "",
    "Lvl 65-78",
    "Nektar",
    "Bahan: Madu enak 1stak",
    "",
    "Lvl 78-85",
    "Revita V",
    "Bahan: Nektar",
    "",
    "Lvl 85-98",
    "Nektar",
    "Bahan: Madu enak 1stak",
    "",
    "Lvl 98-104",
    "Sirup Nektar",
    "Bahan: Nektar",
    "",
    "Lvl 104-107",
    "Revita VII",
    "Bahan: Sirup Nektar",
    "",
    "Lvl 107-120",
    "Nektar",
    "Bahan: Madu enak 1stak",
    "",
    "Lvl 120-126",
    "Sirup Nektar",
    "Bahan: Nektar",
    "",
    "Lvl 126-129",
    "Revita VII",
    "Bahan: Sirup Nektar",
    "",
    "Lvl 129-142",
    "Nektar",
    "Bahan: Madu enak 1stak",
    "",
    "Lvl 142-148",
    "Sirup Nektar",
    "Bahan: Nektar",
    "",
    "Lvl 148-150",
    "Revita VII",
    "Bahan: Sirup Nektar",
    "━━━━━━━━━━━━━━━━━━",
    "By: Master-A",
    "Nge-fans yaa sama Fuuka Hehe"
  ].join("\n"),
  "#15": [
    "Fuuka-chan",
    "",
    "Masuk gc pet aja",
    "",
    "Tips build pet singkat:",
    "━━━━━━━━━━━━━━━━━━",
    "1. Cari pet sampai dapet weapon/type/sifat yg pas.",
    "2. Keluarin kandang,",
    "3. Kasih makan 3k,",
    "4. Latih skill, misal belok buang, misal dapet tapi lvl 3 kebawah buang.",
    "5. Ulangi dri langkah 1 jika blm dapet skill nya lv4/lv5. Kalo dah dapet lanjut..",
    "6. Kasih makan lagi tiap 4 jam sampai dapet bonus latih 50% .",
    "no 6 dgn no 4 boleh dibalik",
    "7. Lanjut latih potensi nya(mode Hard) sesuai job pet nya sampai 100% terlatih.",
    "8. Lanjut lvling lvl dan lvling skill sampai max,",
    "9. Padu dengan pet lain dengan syarat yg sama kek no 1-8.",
    "10. Kalo butuh lock dye, padu lagi sampai sesuai target yg di inginkan.",
    "12. Lanjut latih skill- potensi-lvling sampai cap.",
    "13. Done pet anda sudah jadi 🎉🎊",
    "",
    "Sumber: Pet Toram Online Indo"
  ].join("\n"),
  "#16": [
    "Fuuka-chan",
    "",
    "🔮🔮EFEK STATUS POIN🔮🔮",
    "━━━━━━━━━━━━━━━━━━",
    "🟢Pengaruh Status Karakter",
    "",
    "Tongkat",
    "",
    "STR : ATK+3 , Stab+0.05",
    "INT : ATK+1 , MATK+4 ,ASPD+0.2",
    "AGI : ASPD+1.8",
    "DEX : MATK+1 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Busur",
    "",
    "STR : ATK+1 , Stab+0.05",
    "INT : MATK+3",
    "AGI : ASPD+3.1",
    "DEX : ATK+3 , MATK+1 , Stab+0.05 , ASPD+0.2 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Katana",
    "",
    "STR : ATK+1.5 , Stab+0.075 , Aspd+0.3",
    "INT : MATK+2",
    "AGI : MATK+1 , ASPD+3.9",
    "DEX : ATK+2.5 , MATK+1 , Stab+0.025 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Sayap Sihir",
    "",
    "INT : ATK+2 , MATK+4 , ASPD+0.2",
    "AGI : ATK+2 , ASPD+4.6",
    "DEX : MATK+1 , Stab+0.1 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Pedang 1 Tangan",
    "",
    "STR : ATK+2 , Stab+0.025 , ASPD+0.2",
    "INT : MATK+3",
    "AGI : ASPD+4.2",
    "DEX : ATK+2 , MATK+1 , Stab+0.075 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Pedang 2 Tangan",
    "",
    "STR : ATK+3 , ASPD+0.2",
    "INT : MATK+3",
    "AGI : ASPD+2.1",
    "DEX : ATK+1 , MATK+1 , Stab+0.1 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Pedang Ganda",
    "",
    "STR : ATK+1 , SubATK +1 ,Stab+0.025 , SubStab +0.06 , Aspd+0.2",
    "INT : MATK+3",
    "AGI : ATK+1 , SubATK+3 ,SubStab+0.04 , Aspd+4.2",
    "DEX : ATK+2 , MATK+1 , Stab+0.075 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Bowgun",
    "",
    "STR : Stab+0.05",
    "INT : MATK+3",
    "AGI : ASPD+2.2",
    "DEX : ATK+4 , MATK+1 , ASPD+0.2 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Sarung Tinju",
    "",
    "STR : ASPD+0.1",
    "INT : MATK+4",
    "AGI : ATK+2 , ASPD+4.6",
    "DEX : ATK+0.5 , MATK+1 ,Stab+0.025 , ASPD+0.1 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Tombak",
    "",
    "STR : ATK+2.5 , Stab+0.05 , Aspd+0.2",
    "INT : MATK+2",
    "AGI : ATK+1.5 , MATK+1 , Aspd+3.5",
    "DEX : MATK+1 , Stab+0.05 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Tangan Kosong / tanpa Senjata",
    "",
    "STR : ATK+1",
    "INT : MATK+3",
    "AGI : ASPD+9.6",
    "DEX : MATK+1 , CSPD+2.94 , Acc+1",
    "",
    "🟢Pengaruh Status Karakter",
    "",
    "Semua Job/Senjata",
    "",
    "STR : jika Str > Agi = str/5 , jika Agi > str = Agi+str/10",
    "INT : MP+0.1 , MDEF+1xn >(nilai n jika Arm diperberat=2, Arm diperingan=0.25 )",
    "VIT : Max HP x 0.33 x Lvchar , DEF+1xn > (nilai n jika Arm diperberat=2, Arm diperingan=0.25 )",
    "AGI : if Agi >str = 0,1 cd , CSPD+1.16 , Flee+1xn (nilai n jika Arm diperberat=0.75 ,Arm Diperingan=1.75)",
    "CRT : cr+0.29412 (3.4 CRT=1cr , 255CRT=75cr)",
    "LUCK: Droprate+0.1% , Mengurangi degradasi 95% dengan Anti degradasi",
    "TEC : MP+1",
    "MTL : Ailment+0.29412 (3.4 MTL=1 Ailment , 255MTL=75 Ailment)",
    "━━━━━━━━━━━━━━━━━━"
  ].join("\n"),
  "#17": [
    "Fuuka-chan",
    "",
    "🔮🔮AILMENT & INTERRUPT🔮🔮",
    "━━━━━━━━━━━━━━━━━━",
    "1) Flinch (Bergidik)",
    "",
    "- Ke Boss atau Mobs",
    "Interupsi aksinya sejenak (Singkat)",
    "",
    "- Ke Pemain",
    "Interupsi tindakan mereka sejenak (Singkat)",
    "",
    "2) Tumble (Jatuh)",
    "",
    "- Ke Bos atau Mobs",
    "Interupsi aksinya sejenak (Sedang)",
    "",
    "- Ke Pemain",
    "Interupsi tindakan mereka sejenak (Sedang)",
    "",
    "3) Stun (Pingsan)",
    "",
    "- Ke Bos atau Mobs",
    "Interupsi aksinya sejenak (Lama)",
    "",
    "- Ke Pemain",
    "Interupsi tindakan mereka sejenak (Lama)",
    "",
    "4) Knock Back (Terpelanting)",
    "",
    "- Ke Bos atau Mobs",
    "Interupsi aksinya sejenak, terpelanting ke belakang untuk beberapa jarak",
    "",
    "- Ke Pemain",
    "Interupsi aksinya sejenak, terpelanting ke belakang untuk beberapa jarak",
    "",
    "5) Poison (Keracunan)",
    "",
    "- Ke Bos atau Mobs",
    "Menimbulkan beberapa kerusakan untuk setiap tindakan selama 10 detik",
    "",
    "- Ke Pemain",
    "Menimbulkan kerusakan sebesar 5% dari sisa HP pada setiap tindakan, kerusakan ini tidak dapat membunuh pemain",
    "",
    "6) Ignite (Terbakar)",
    "",
    "- Ke Bos atau Mobs",
    "Menimbulkan beberapa kerusakan untuk setiap 1 detik (3 detik) selama 10 detik",
    "",
    "- Ke Pemain",
    "Menimbulkan kerusakan sebesar 15% dari sisa HP terkini, kerusakan ini tidak dapat membunuh pemain",
    "",
    "7) Freeze (Beku)",
    "",
    "- Ke Bos atau Mobs",
    "Mengurangi kecepatan gerak hingga 50%, berlangsung selama 10 detik. Dapat digunakan kembali saat durasi berakhir",
    "",
    "- Ke Pemain",
    "Mengurangi 50% kecepatan gerak (moontion speed) dan Ayunan Dewa (Godspeed Wield), Memiliki durasi 10 detik.",
    "",
    "8) Slow (Lambat)",
    "",
    "- Ke Bos atau Mobs",
    "Mengurangi kecepatan gerakan target sebesar 50% (25% untuk boss). Memiliki durasi 10 detik",
    "",
    "- Ke Pemain",
    "Menurunkan 50% kecepatan berjalan (movement speed), durasi efek 10 detik. Evasion, Evasion recharge and Shukuchi dinonaktifkan",
    "",
    "9) Stop (Berhenti)",
    "",
    "- Ke Bos atau Mobs",
    "Mengikat musuh ke posisinya saat ini selama 10 detik, memiliki cooldown 60 detik. Kurang efektif melawan bos karena hanya mengurangi kecepatan gerakan bos sebesar 50% (tidak mengikat bos), Lebih efektif untuk monster dan bos mini. Pola serangan seperti garis lurus atau serangan rapalan dapat digunakan saat mendapatkan debuff berhenti.",
    "",
    "- Ke Pemain",
    "Tidak dapat berpindah tempat atau berjalan, durasi 10 detik. Masih bisa menggunakan skil gerak (motion) dan rapalan seperti slash dapat digunakan saat mendapatkan debuff berhenti.",
    "Tidak dapat Evasion, Evasion recharge dan Shukuchi terhenti.",
    "",
    "10) Dizzy (Pening)",
    "",
    "- Ke Bos atau Mobs",
    "Menurunkan tingkat guard dan evasion sebesar 100% (Boss 50%)",
    "",
    "- Ke Pemain",
    "Menonaktifkan Evasion dan Guard recharge",
    "",
    "11) Dazzled (Silau)",
    "",
    "- Ke Bos atau Mobs",
    "Flee -50%",
    "",
    "- Ke Pemain",
    "",
    "12) Paralysis (Lumpuh)",
    "",
    "- Ke Bos atau Mobs",
    "Tingkatkan penundaan tindakan",
    "",
    "- Ke Pemain",
    "Mengurangi 50% ASPD (Attack Speed/Kecepatan Serangan)",
    "",
    "13) Blind (Buta)",
    "",
    "- Ke Bos atau Mobs",
    "Mengurangi akurasi 50%k",
    "",
    "- Ke Pemain",
    "Penurunan Akurasi sebesar 20% untuk serangan dalam jarak 7m, dan 40% untuk 8m ke atas",
    "",
    "14) Fear (Takut)",
    "",
    "- Ke Bos atau Mobs",
    "30% kemungkinan untuk membatalkan tindakan",
    "",
    "- Ke Pemain",
    "30% peluang gagal mengeluarkan skill",
    "",
    "15) Lethargy (Lesu)",
    "",
    "- Ke Bos atau Mobs",
    "Output kerusakan berkurang 30%",
    "",
    "- Ke Pemain",
    "Output kerusakan berkurang 30%",
    "",
    "16) Weaken (Lemah)",
    "",
    "- Ke Bos atau Mobs",
    "Mengurangi MDEF target sebesar 25%.",
    "",
    "- Ke Pemain",
    "Menambah Biaya konsumsi MP untuk semua keterampilan +100",
    "",
    "17) Bleed (Berdarah)",
    "",
    "- Ke Pemain",
    "Tidak dapat menggunakan skill fisik",
    "",
    "18) Silence (Bisu)",
    "",
    "- Ke Pemain",
    "Tidak dapat menggunakan skill sihir",
    "",
    "19) Confused",
    "",
    "- Ke Pemain",
    "Tidak diketahui",
    "",
    "20) Armor Break (Pecah Zirah)",
    "",
    "- Ke Bos atau Mobs",
    "DEF & MDEF -50%",
    "",
    "- Ke Pemain",
    "Mengurangi kekebalan fisik dan sihir hingga 50%, tidak dapat menggunakan Guard",
    "",
    "21) Fatigue (Lelah)",
    "",
    "- Ke Bos atau Mobs",
    "Mengurangi stabilitas 50%, pada serangan durasi terakhir akan mengalami graze.",
    "",
    "- Ke Pemain",
    "Mengurangi stabilitas 50%, pada serangan durasi terakhir akan mengalami graze.",
    "",
    "22) Sleep (Tidur)",
    "",
    "- Ke Bos atau Mobs",
    "Melumpuhkan untuk waktu yang lama, bangun saat menerima serangan, Bos memulihkan 3% dari HP maksimal saat bangun",
    "",
    "- Ke Pemain",
    "Melumpuhkan untuk waktu yang lama, bangun saat menerima serangan, mengaktifkan regenerasi alami",
    "",
    "23) Mana Explosion (Ledakan Mana)",
    "",
    "- Ke Pemain",
    "Setelah durasi berakhir, konsumsi semua mp menjadi 0 dan memberikan damage sama dengan konsumsi mp x10",
    "",
    "24) Sick (Sakit)",
    "",
    "- Ke Pemain",
    "Menurunkan resistensi status buruk sebesar -50% (masih dapat terkena bahkan jika Anda memiliki resistensi status buruk 100%)",
    "",
    "25) Curse (Terkutuk)",
    "",
    "- Ke Pemain",
    "Menurunkan CRT damage pemain sebesar -50%",
    "",
    "26) Item Disable",
    "",
    "- Ke Pemain",
    "Tidak dapat menggunakan barang",
    "",
    "27) Overdrive (Lari)",
    "",
    "- Ke Pemain",
    "Mengkonsumsi HP saat MP tidak mencukupi untuk melakukan skill, juga menerapkan tenacity (Gigih) ke semua skill dalam kombo (tidak mengganti tag yang ada)",
    "",
    "28) Suction (Pengisapan)",
    "",
    "- Ke Bos atau Mobs",
    "Menarik ke pusat serangan, 50% peluang tarik untuk Bos",
    "",
    "- Ke Pemain",
    "Menarik ke pusat serangan, saat terkena menonaktifkan evasion dan Guard selama 1 detik",
    "",
    "29) Petrified (Kaku)",
    "",
    "- Ke Pemain",
    "Menghindar Mutlak +100%, & menghapus aggro saat ini sebesar 99%",
    "",
    "30) Inversion",
    "",
    "- Ke Pemain",
    "Mengganti HP% dan MP% Anda saat ini",
    "━━━━━━━━━━━━━━━━━━"
  ].join("\n"),
  "#18": [
    "Fuuka-chan",
    "",
    "🔮🔮POTENSIAL EQUIPMENT🔮🔮",
    "━━━━━━━━━━━━━━━━━━",
    "🟢STR",
    "",
    "- Setiap 10 stat STR menambah 1 potential untuk Pedang 2 Tangan",
    "",
    "- Setiap 20 stat STR menambah 1 potential untuk Pedang 1 Tangan, Busur dan Tombak",
    "",
    "🟢INT",
    "",
    "- Setiap 10 stat INT menambah 1 potential untuk Tongkat",
    "",
    "- Setiap 20 stat INT menambah 1 potensial untuk Sayap Sihir",
    "",
    "🟢VIT",
    "",
    "- Setiap 10 stat VIT menambah 1 potential untuk Armor",
    "",
    "🟢AGI",
    "",
    "- Setiap 10 stat AGI menambah 1 potential untuk Sarung Tinju",
    "",
    "- Setiap 20 stat AGI menambah 1 potential untuk Tombak, Sayap Sihir dan Katana",
    "",
    "🟢DEX",
    "",
    "- Setiap 10 stat DEX menambah 1 potential untuk Bowgun",
    "",
    "- Setiap 20 stat DEX menambah 1 potential untuk Pedang 1 Tangan, Busur, Katana",
    "",
    "━━━━━━━━━━━━━━━━━━"
  ].join("\n"),
  "#19": [
    "Fuuka-chan",
    "",
    "Tips Raid",
    "━━━━━━━━━━━━━━━━━━",
    "Growler Bison (Raid biru)",
    "Posisi bagus: samping bossnya",
    "- Kalau tank mulai dengan stun, jangan kelamaan deket2 soalnya ada shockwave",
    '- Pake regis "Pyrexia" kalau kena hit (gak tau sih fungsinya ngapain)',
    "",
    "Pattern berbahaya:",
    "1. Boss lari dari tank",
    "2. Boss nembak bola ke player dengan jarak paling jauh",
    "3. AoE gede",
    "━━━━━━━━━━━━━━━━━━",
    "Demonic Skull Dragon (Raid ungu)",
    "Posisi bagus: barat lautnya boss atau belakang",
    "",
    "Pattern berbahaya:",
    "1. 3 AoE biru lurus atau nabok pake 2 tangan, yang mana pattern 3 hiu melingkar, kalau gak diinterupt (flinch, tumble, stun), kepalanya bakal nengok ke lutut kiri 1 detik sebelum hiunya keluar",
    "2. Boss lari dari tank",
    "3. AoE merah donat (kalau bisa interrupt sih)",
    "━━━━━━━━━━━━━━━━━━",
    "Roaring Thruma (Raid hijau)",
    "Posisi bagus: (gak ada di tulisan sih, tapi menurutku) belakang",
    "",
    "Pattern berbahaya:",
    "1. Boss lari dari tank",
    "2. Animasi pedang ke serong kanan serong kiri, yang ngeluarin 5 hiu x 2",
    "3. Nancapin 1 pedang ke tanah dan nembak bola (300k+ fatal attack ke tank)",
    "4. AoE merah lari ke arah tank, yang mana bakal ngeluarin hiu gede ke depannya.",
    "━━━━━━━━━━━━━━━━━━",
    "Mighty Chimera (Raid kuning)",
    "Posisi bagus: di samping atau di belakang (kalau aku sih lebih aman kalau berjarak 0 meter)",
    "",
    "Pattern berbahaya:",
    "1. AoE biru 1 arena, ngasih kita ailment petrify / kaku",
    "2. Mundur dari tank, yang mana ngeluarin banyak hiu lurus dan serong hanya jika banyak yang berada dalam jangkauan",
    "3. AoE merah di samping kalau ada banyak yang disana (yang mana kalau 0 meter tetap aman)",
    "4. AoE biru kecil yang ngeluarin badai, kalau udah berkali-kali lawannya.",
    "━━━━━━━━━━━━━━━━━━",
    "Blazing Celdyte (Raid Merah)",
    "Raid boss Api",
    "",
    "* Posisi paling aman ada di sebelah kanan arah boss (di sebelah kiri arah player)",
    "",
    "* Jika terlalu banyak spam skill boss otomatis akan mengeluarkan meteor mini (tanpa ada targeting aoe)",
    "",
    "* Boss tidak bisa di stun tapi masih bisa di gedik atau pakai skill impact",
    "",
    "* setelah ngeluarin aoe biru dari sebelah kiri boss jangan di dekat nya karna boss pasti",
    "memberikan damage yang di sekitar nya menggunakan ekor",
    "",
    '* Ada circle biru dari "Fireguard Schnee" untuk menjadi tempat aman saat raid. Jika keluar circle, maka akan kena damage per detik dengan ailment \'Terbakar\'. Jangan bunuh Fireguard Schnee atau semua player akan kena damage tersebut sebanyak 10 hit selama 10 detik.',
    "",
    "* Hati2 dengan pattern hiu lurus ke segala arah karena nanti bossnya nyerang tanpa aoe (cara menghindarnya tinggal menjauh, tapi gak tau jarak berapa amannya)",
    "━━━━━━━━━━━━━━━━━━",
    "Semangat Raidnya 🔥🔥🔥",
    "Fuuka imut Fuuka kawaii"
  ].join("\n"),
  "#20": [
    "Fuuka-chan",
    "",
    "Panduan Newbie",
    "━━━━━━━━━━━━━━━━━━",
    "Tutorial Video",
    "Channel yt: YusagiKurumi",
    "1. Bow (Cap 270)",
    "https://youtu.be/e8solPHDTJE?si=mdB4b8qkmd2T7awV",
    "2. Katana (Cap 280)",
    "https://youtu.be/ucX6s4Xb8IU?si=afb1IMXXocdfjkIE",
    "3. Dual Sword (Cap 290)",
    "https://youtu.be/NF8hEtuxJqc?si=z_PUAdIiLmPiMIWc",
    "",
    "Ketik Kodenya yaaa....",
    "#20a > Episode 1",
    "#20b > Episode 2",
    "#20c > Episode 3",
    "#20d > Episode 4",
    "#20e > Episode 5",
    "#20f > Episode 6",
    "#20g > Episode 7",
    "#20h > Episode 8",
    "━━━━━━━━━━━━━━━━━━",
    "By: Master-A & Force Knight"
  ].join("\n"),
  "#98": [
    "Kata Mutiara Sepuh",
    "",
    "🎼Aku mah masih pemula",
    "Ajarin donk puh sepuh",
    "Puh sepuh ajarin donk",
    "Masih pemula aku",
    "Puh sepuh",
    "Tingkiwingki dipsi lala puh sepuh",
    "Ajarin donk",
    "Puhhhh sepuhhhh"
  ].join("\n"),
  "#99": [
    "Tes Kehokian"
  ].join("\n")
};

function normalizeTopicKey(value) {
  return (value || "").trim().toLowerCase();
}

const sepuhAudioPath = path.resolve(__dirname, "../../audio/sepuh.ogg");

module.exports = {
  name: "help",
  description: "Menampilkan bantuan penggunaan bot.",
  topicReplies,
  normalizeTopicKey,
  execute: async ({ sock, message, args = [] }) => {
    const normalizedArg = normalizeTopicKey(args[0]);
    const topicReply = topicReplies[normalizedArg];
    const topicKey = topicReply ? normalizedArg : "menu";
    const text = normalizedArg === "#98" || normalizedArg === "#99"
      ? normalizeSpacing(topicReply || "")
      : formatHelpMessage(topicReply || helpMenuText, topicKey);

    if (normalizedArg === "#98") {
      await sock.sendMessage(
        message.key.remoteJid,
        {
          audio: fs.readFileSync(sepuhAudioPath),
          mimetype: "audio/ogg; codecs=opus",
          ptt: true
        },
        {
          quoted: message
        }
      );
    }

    if (normalizedArg === "#99") {
      const senderName =
        message.pushName ||
        message.key?.participant?.split("@")[0] ||
        message.key?.remoteJid?.split("@")[0] ||
        "onii-chan";
      const { percentage, response, opener } = getRandomLuckResult();

      await sock.sendMessage(
        message.key.remoteJid,
        {
          text: [
            opener,
            "",
            `Tes kehokian untuk ${senderName} yaa~ (≧◡≦)`,
            `Hasil hoki hari ini: *${percentage}%* (๑˃ᴗ˂)ﻭ`,
            "",
            response
          ].join("\n")
        },
        {
          quoted: message
        }
      );

      return;
    }

    await sock.sendMessage(
      message.key.remoteJid,
      {
        text
      },
      {
        quoted: message
      }
    );
  }
};
