const path = require("path");
const fs = require("fs");

const divider = "━━━━━━━━━━━━━━━━━━━━";
const sepuhAudioPath = path.resolve(__dirname, "../../audio/sepuh.ogg");
const sepuhAudio = fs.readFileSync(sepuhAudioPath);
const readMoreSpacer = String.fromCharCode(8206).repeat(4001);

const luckPercentages = [0, 1, 2, 5, 10, 20, 25, 50, 99, 100];

const dynamicGreetings = [
  [
    "Yahhoo~ Fuuka datang yaa, hehee~ (≧∇≦)/",
    "Kalau ada yang dicari, bilang pelan-pelan ke Fuuka yaa~",
  ],
  [
    "Ehehe, Fuuka siap bantu nih~ (≧ω≦)",
    "Sini sini, Fuuka jelasin dengan manis yaa~",
  ],
  [
    "Uwaa, Fuuka di sini lhoo~ (๑˃̵ᴗ˂̵)",
    "Biar Fuuka yang kasih tau pelan-pelan yaa~",
  ],
  [
    "Fuuka muncul duluan nih~ (≧▽≦)",
    "Yuk yuk, kita lihat bareng sama Fuuka yaa~",
  ],
];

const cuteFooterQuestions = [
  "Nee nee, Fuuka imouto yang imut kan, onii-chan? (≧ω≦)",
  "Ehehe... Fuuka jelasinya gampang dimengerti kan? puji Fuuka dong~ (๑˃̵ᴗ˂̵)",
  "Fuuka udah bantuin onii-chan dengan manis kan? (〃▽〃)",
  "Kalau masih bingung, panggil Fuuka lagi yaa, onii-chan~ (o^▽^o)",
  "Fuuka kecil begini tetep bisa diandelin kan? (≧∇≦)",
  "Ano... Fuuka kawaii banget kan hari ini? hehe~ (˶ᵔ ᵕ ᵔ˶)",
];

const topicFooterQuestions = {
  mq: [
    "Semangat yaa onii-chan, jalani Main Quest pelan-pelan bareng keberanian manis~ (≧▽≦)",
    "Fuuka yakin onii-chan bisa lancar jalanin MQ ini yaa~ semangaaat! (๑˃ᴗ˂)ﻭ",
    "Main Quest-nya jangan takut yaa, Fuuka dukung dari sini~ (〃▽〃)",
    "Yuk yuk, semangat terus buat beresin MQ satu per satu yaa~ (o^▽^o)",
    "Fuuka kirim semangat imut biar perjalanan MQ onii-chan makin lancar~ (≧ω≦)",
    "Pelan-pelan aja yaa, yang penting MQ-nya jalan terus~ semangat! (≧◡≦)",
    "Kalau capek pas MQ, ingat masih ada semangat dari Fuuka yaa~ (〃ω〃)",
    "Hehee, onii-chan pasti bisa taklukin Main Quest ini~ (≧∇≦)/",
    "Bekal udah siap, sekarang waktunya semangat jalanin MQ yaa~ (๑˃ᴗ˂)ﻭ",
    "Fuuka percaya onii-chan bisa kuat sampai quest terakhir yaa~ (o^▽^o)",
  ],
  raid: [
    "Semangat raid-nya yaa, onii-chan~ hajar bossnya pelan-pelan dan kompak! (≧▽≦)",
    "Fuuka dukung dari sini, semoga raid onii-chan lancar dan menang yaa~ (๑˃ᴗ˂)ﻭ",
    "Yuk yuk, semangat terus pas raid dan jangan panik yaa~ (〃▽〃)",
    "Fuuka percaya onii-chan bisa lewatin raid ini dengan manis~ (o^▽^o)",
    "Main raid yang rapi yaa, semoga bossnya cepat tumbang~ (≧ω≦)",
    "Semangaaat, kompak bareng tim dan hati-hati sama pattern boss yaa~ (≧◡≦)",
    "Fuuka kirim semangat imut buat raid onii-chan hari ini~ (〃ω〃)",
    "Jangan menyerah yaa, onii-chan pasti bisa clear raid-nya~ (≧∇≦)/",
    "Semoga drop-nya bagus dan raid-nya mulus yaa~ semangat! (๑˃ᴗ˂)ﻭ",
    "Fuuka doain raid onii-chan aman, kompak, dan menang yaa~ (o^▽^o)",
  ],
  ailment: [
    "Fuuka sedih kalau onii-chan kena status buruk terus... jaga diri baik-baik yaa~ (´ . .̫ . `)",
    "Jangan sampai sakit atau kena efek aneh terus yaa, onii-chan~ Fuuka khawatir... (｡•́︿•̀｡)",
    "Fuuka mohon hati-hati yaa, jangan biarin badan onii-chan tumbang karena ailment~ (´；ω；`)",
    "Kalau kena status buruk terus Fuuka ikut sedih... jaga kesehatan yaa~ (｡•́︿•̀｡)",
    "Tolong jaga diri yaa, onii-chan... Fuuka maunya onii-chan tetap sehat dan aman~ (´ . .̫ . `)",
    "Fuuka nggak mau lihat onii-chan sakit-sakitan karena ailment... hati-hati yaa~ (╥﹏╥)",
    "Pelan-pelan aja yaa, yang penting onii-chan tetap sehat dan nggak kena debuff aneh~ (´；ω；`)",
    "Fuuka titip pesan, jangan lupa jaga kondisi badan dan karakter yaa~ (｡•́︿•̀｡)",
    "Kalau onii-chan sehat dan aman, Fuuka juga jadi tenang... jadi hati-hati yaa~ (´ . .̫ . `)",
    "Fuuka sayang sama onii-chan, jadi jangan sampai sakit dan tetap jaga kesehatan yaa~ (╥﹏╥)",
  ],
};

const topicHeaderIntros = {
  menu: [
    "Pilih nomor menu yang mau onii-chan lihat yaa~ (≧▽≦)",
    "Coba pilih salah satu nomor menu di bawah ini yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau cek info tertentu, pilih nomor menunya yaa~ (≧ω≦)",
    "Yuk yuk, sentuh nomor menu yang bikin onii-chan penasaran yaa~ (o^▽^o)",
    "Fuuka siap nemenin, tinggal pilih nomor menu yang mau dibuka yaa~ (〃▽〃)",
    "Kalau bingung mulai dari mana, pilih aja nomor menu yang menarik yaa~ (≧◡≦)",
    "Mau info yang mana nih? Pilih nomor menunya yaa, onii-chan~ (๑˃ᴗ˂)ﻭ",
    "Hehee, pilih nomor menu favorit onii-chan dulu yaa~ (≧∇≦)/",
  ],
  guild: [
    "Ehehe, sekarang Fuuka jelasin tentang guild pelan-pelan yaa~ (≧ω≦)",
    "Fuuka mode guru kecil aktif nih, yuk lihat cerita guildnya yaa~ (๑˃ᴗ˂)ﻭ",
    "Sini sini, Fuuka mau ceritain makna dan sejarah guild dengan manis yaa~ (〃▽〃)",
    "Yuk duduk yang manis, Fuuka jelasin soal guild satu-satu yaa~ (o^▽^o)",
    "Fuuka siap ngajarin pelan-pelan tentang guild kita yaa, onii-chan~ (≧◡≦)",
    "Hehee, biar Fuuka jadi guru kecil lucu yang jelasin sejarah guild yaa~ (≧∇≦)/",
    "Kalau penasaran sama asal-usul guild, Fuuka bantu jelasin yaa~ (๑˃ᴗ˂)ﻭ",
    "Fuuka akan cerita tentang guild ini dengan lembut dan rapi yaa~ (≧▽≦)",
    "Nih yaa, Fuuka jelasin makna guildnya dulu biar gampang dimengerti~ (〃ω〃)",
    "Mari belajar bareng Fuuka tentang sejarah guild yaa~ (o^▽^o)",
  ],
  newbie: [
    "Fuuka siap nemenin onii-chan belajar dari awal yaa~ (≧▽≦)",
    "Yuk yuk, guru kecil Fuuka jelasin panduan newbie pelan-pelan yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau masih baru, sini bareng Fuuka biar nggak bingung yaa~ (〃▽〃)",
    "Fuuka siap kasih panduan awal yang manis buat onii-chan~ (o^▽^o)",
    "Hehee, sekarang giliran Fuuka jelasin bekal newbie yaa~ (≧ω≦)",
    "Fuuka bantu arahkan langkah awalnya biar lebih gampang yaa~ (≧◡≦)",
    "Pelan-pelan aja, Fuuka temenin panduan newbie ini yaa~ (〃ω〃)",
    "Mari mulai dari dasar bareng Fuuka yaa, onii-chan~ (≧∇≦)/",
    "Fuuka udah siapin panduan pemula yang rapi nih~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau mulai main dengan enak, ikutin panduan Fuuka yaa~ (o^▽^o)",
  ],
  buff: [
    "Fuuka bawain daftar buff ini biar kekuatan player onii-chan makin naik yaa~ (≧▽≦)",
    "Yuk yuk, pakai buff ini biar karakter onii-chan jadi makin kuat yaa~ (๑˃ᴗ˂)ﻭ",
    "Fuuka kasih tau buff yang bisa bantu naikin power player yaa~ (〃▽〃)",
    "Kalau mau stats makin gahar, cek buff player ini yaa~ (o^▽^o)",
    "Hehee, Fuuka siap tunjukin buff buat tambah tenaga karakter yaa~ (≧ω≦)",
    "Buff-buff ini bisa bikin player onii-chan makin mantap lho yaa~ (≧◡≦)",
    "Fuuka bantu kumpulin buff yang cocok buat ningkatin kekuatan player yaa~ (〃ω〃)",
    "Mau karakter lebih kuat? Nih yaa, Fuuka kasih daftar buff-nya~ (≧∇≦)/",
    "Pelan-pelan yaa, Fuuka jelasin buff penting buat nambah power player~ (๑˃ᴗ˂)ﻭ",
    "Dengan buff ini, karakter onii-chan bisa jadi lebih sangar yaa~ (o^▽^o)",
  ],
  mq: [
    "Main Quest itu perjalanan utama yaa, jadi Fuuka bantu siapin bekalnya dulu~ (≧▽≦)",
    "Sebelum jalan MQ, yuk siapin bahan-bahannya dulu bareng Fuuka yaa~ (๑˃ᴗ˂)ﻭ",
    "Fuuka kasih catatan persiapan biar onii-chan lebih siap sebelum Main Quest yaa~ (〃▽〃)",
    "Kalau mau jalan MQ lebih mulus, cek dulu bahan persiapannya yaa~ (o^▽^o)",
    "Hehee, Fuuka bantuin siap-siap sebelum onii-chan lanjut Main Quest yaa~ (≧ω≦)",
    "Ini dia bekal kecil dari Fuuka buat persiapan sebelum Quest Utama yaa~ (≧◡≦)",
    "Pelan-pelan yaa, Fuuka jelasin bahan yang perlu disiapin sebelum MQ~ (〃ω〃)",
    "Biar nggak bolak-balik cari item, Fuuka siapin daftar MQ ini yaa~ (≧∇≦)/",
    "Main Quest alias Quest Utama bakal lebih enak kalau persiapannya rapi yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih yaa, Fuuka bantu kasih daftar persiapan sebelum onii-chan gas MQ~ (o^▽^o)",
  ],
  bag: [
    "Upgrade tas pelan-pelan itu penting yaa, biar mainnya nanti makin nyaman~ (≧▽≦)",
    "Yuk yuk, tasnya dibesarin pelan-pelan dulu biar nggak repot pas main yaa~ (๑˃ᴗ˂)ﻭ",
    "Fuuka kasih daftar ini biar onii-chan bisa upgrade tas dengan nyaman yaa~ (〃▽〃)",
    "Kalau tas lebih lega, perjalanan main nanti juga lebih enak yaa~ (o^▽^o)",
    "Hehee, mending siapin bahan upgrade tas dari sekarang yaa~ (≧ω≦)",
    "Biar nggak sesek inventori terus, yuk upgrade tas pelan-pelan yaa~ (≧◡≦)",
    "Fuuka bantu kasih panduan bahan tas supaya main ke depannya lebih nyaman yaa~ (〃ω〃)",
    "Pelan-pelan aja, yang penting slot tas onii-chan makin luas yaa~ (≧∇≦)/",
    "Tas yang lega bikin farming dan simpan item jadi lebih santai yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih yaa, Fuuka bantu siapin daftar upgrade tas demi kenyamanan main~ (o^▽^o)",
  ],
  leveling: [
    "Nih yaa, Fuuka jelasin cara leveling yang diajarin Hsans oni-chan pelan-pelan~ (≧▽≦)",
    "Yuk yuk, Fuuka bantu tunjukin alur leveling dari Hsans oni-chan yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau leveling lebih terarah, sini Fuuka jelasin panduan dari Hsans oni-chan yaa~ (〃▽〃)",
    "Hehee, sekarang Fuuka bacain cara leveling versi Hsans oni-chan yaa~ (o^▽^o)",
    "Fuuka siap bantu jelasin langkah leveling yang diajarin Hsans oni-chan~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka tuntun urutan leveling dari Hsans oni-chan dulu~ (≧◡≦)",
    "Biar nggak bingung cari spot leveling, Fuuka jelasin ajaran Hsans oni-chan yaa~ (〃ω〃)",
    "Mari belajar leveling bareng Fuuka dari panduan Hsans oni-chan yaa~ (≧∇≦)/",
    "Nih, Fuuka siapin alur leveling yang diajarin Hsans oni-chan biar gampang diikutin~ (๑˃ᴗ˂)ﻭ",
    "Kalau onii-chan mau naik level dengan rapi, ikutin penjelasan Fuuka dari Hsans oni-chan yaa~ (o^▽^o)",
  ],
  refine: [
    "Nih yaa, Fuuka ajarin cara refine biar perlengkapan onii-chan cepat makin kuat~ (≧▽≦)",
    "Yuk yuk, Fuuka jelasin cara menempa equipment sampai +S dengan manis yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau gear lebih kuat, sini Fuuka ajarin tips refine pelan-pelan yaa~ (〃▽〃)",
    "Hehee, refine itu buat memperkuat perlengkapan, jadi Fuuka bantu jelasin yaa~ (o^▽^o)",
    "Fuuka siap kasih tips cepat buat bikin equipment onii-chan makin mantap~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka tuntun cara refine supaya gear onii-chan tambah kuat~ (≧◡≦)",
    "Biar perlengkapannya makin tajam dan kuat, yuk belajar refine bareng Fuuka yaa~ (〃ω〃)",
    "Mari lihat cara cepat memperkuat equipment player lewat refine yaa~ (≧∇≦)/",
    "Fuuka siapin panduan refine ini biar onii-chan lebih gampang kejar +S yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka jelasin langkah refine buat bantu naikin kekuatan perlengkapan yaa~ (o^▽^o)",
  ],
  blacksmith: [
    "Nih yaa, Fuuka ajarin cara bikin char blacksmith sesuai stat yang pas~ (≧▽≦)",
    "Yuk yuk, Fuuka jelasin pembagian stat buat char blacksmith pelan-pelan yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau bikin BS yang rapi, sini Fuuka bantu jelasin stat-nya yaa~ (〃▽〃)",
    "Hehee, Fuuka siap tuntun cara isi stat buat char blacksmith~ (o^▽^o)",
    "Biar char blacksmith onii-chan nggak salah arah, Fuuka jelasin susunan statnya yaa~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka ajarin cara bagi stat blacksmith sesuai senjatanya~ (≧◡≦)",
    "Mari belajar bikin char blacksmith yang enak dipakai bareng Fuuka yaa~ (〃ω〃)",
    "Fuuka siap bantu kasih panduan stat blacksmith biar gampang diikuti~ (≧∇≦)/",
    "Kalau onii-chan mau rakit BS yang pas, ikutin penjelasan Fuuka yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka jelasin cara isi stat blacksmith supaya hasilnya lebih mantap yaa~ (o^▽^o)",
  ],
  smithProf: [
    "Nih yaa, Fuuka jadi pandai besi kecil dulu buat ngajarin kemahiran tempa~ (≧▽≦)",
    "Yuk yuk, Fuuka jelasin cara naikin kemahiran tempa kayak blacksmith profesional yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau skill tempa makin tinggi, sini Fuuka ajarin langkah-langkahnya yaa~ (〃▽〃)",
    "Hehee, Fuuka siap tuntun cara ningkatin keterampilan tempa pelan-pelan yaa~ (o^▽^o)",
    "Fuuka mode pandai besi aktif, sekarang kita belajar kemahiran tempa yaa~ (≧ω≦)",
    "Biar onii-chan makin jago nge-tempa, Fuuka bantu jelasin alurnya yaa~ (≧◡≦)",
    "Pelan-pelan yaa, Fuuka ajarin cara naikin prof tempa biar nggak bingung~ (〃ω〃)",
    "Mari belajar jadi blacksmith yang rapi bareng Fuuka yaa~ (≧∇≦)/",
    "Fuuka siap kasih panduan bahan dan item buat naikkin kemahiran tempa yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka jelasin cara meningkatkan skill tempa biar onii-chan makin pro yaa~ (o^▽^o)",
  ],
  potential: [
    "Nih yaa, Fuuka jelasin fungsi tiap stat terhadap potensial equipment pelan-pelan~ (≧▽≦)",
    "Yuk yuk, Fuuka bantu terangkan pengaruh stat ke potensial equipment yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau paham potensial equipment, sini Fuuka jelasin hubungan stat-nya yaa~ (〃▽〃)",
    "Hehee, sekarang Fuuka terangkan pengaruh setiap stat buat potensial equipment yaa~ (o^▽^o)",
    "Fuuka siap bantu kasih penjelasan stat mana yang nambah potensial equipment~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka ajarin fungsi tiap stat untuk potensial equipment~ (≧◡≦)",
    "Biar nggak bingung, Fuuka jelasin pengaruh stat terhadap potential equipment satu-satu yaa~ (〃ω〃)",
    "Mari belajar bareng Fuuka tentang stat dan potensial equipment yaa~ (≧∇≦)/",
    "Fuuka siapin penjelasan ini biar onii-chan gampang paham potensial equipment~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka bantu terangkan tiap stat memengaruhi potensial equipment bagaimana yaa~ (o^▽^o)",
  ],
  synthesisProf: [
    "Nih yaa, Fuuka jadi ahli padu kecil dulu buat ngajarin kemahiran padu item~ (≧▽≦)",
    "Yuk yuk, Fuuka jelasin cara naikin kemahiran padu item pelan-pelan yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau skill padu item makin tinggi, sini Fuuka ajarin urutannya yaa~ (〃▽〃)",
    "Hehee, Fuuka siap tuntun cara ningkatin keterampilan padu item dengan rapi yaa~ (o^▽^o)",
    "Fuuka mode peracik aktif, sekarang kita belajar kemahiran padu item yaa~ (≧ω≦)",
    "Biar onii-chan makin jago padu item, Fuuka bantu jelasin langkahnya yaa~ (≧◡≦)",
    "Pelan-pelan yaa, Fuuka ajarin cara naikin prof padu item biar nggak bingung~ (〃ω〃)",
    "Mari belajar jadi peracik item yang rapi bareng Fuuka yaa~ (≧∇≦)/",
    "Fuuka siap kasih panduan bahan dan urutan buat naikkin kemahiran padu item yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka jelasin cara meningkatkan skill padu item biar onii-chan makin pro yaa~ (o^▽^o)",
  ],
  xtallMaster: [
    "Nih yaa, Fuuka jelasin daftar xtall pinjaman dari Master-A oni-chan pelan-pelan~ (≧▽≦)",
    "Yuk yuk, Fuuka bantu tunjukin xtall milik Master-A yang bisa dipinjam yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau onii-chan mau cek xtall pinjaman, sini Fuuka jelasin daftarnya yaa~ (〃▽〃)",
    "Hehee, Fuuka siap bacain list xtall Master-A yang bisa dipinjam player yaa~ (o^▽^o)",
    "Fuuka bantu jelasin xtall apa aja yang tersedia buat dipinjam yaa~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka tunjukin daftar xtall pinjaman dari Master-A oni-chan~ (≧◡≦)",
    "Biar nggak bingung cari xtall pinjaman, Fuuka jelasin list-nya satu-satu yaa~ (〃ω〃)",
    "Mari lihat daftar xtall Master-A yang bisa dipinjam bareng Fuuka yaa~ (≧∇≦)/",
    "Fuuka siap kasih tahu xtall mana saja yang boleh dipinjam player yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka terangkan daftar xtall pinjaman biar onii-chan gampang pilih yaa~ (o^▽^o)",
  ],
  xtallEvent: [
    "Nih yaa, Fuuka jelasin xtall-xtall yang bisa didapat dari event pelan-pelan~ (≧▽≦)",
    "Yuk yuk, Fuuka bantu tunjukin daftar xtall event yang bisa onii-chan incar yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau tahu xtall dari event, sini Fuuka jelasin list-nya yaa~ (〃▽〃)",
    "Hehee, sekarang Fuuka terangkan xtall apa aja yang bisa didapat saat event yaa~ (o^▽^o)",
    "Fuuka siap bantu kasih daftar xtall event biar onii-chan nggak ketinggalan yaa~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka tunjukin xtall event satu per satu~ (≧◡≦)",
    "Biar gampang cari target event, Fuuka jelasin list xtall event ini yaa~ (〃ω〃)",
    "Mari lihat bareng Fuuka xtall mana saja yang muncul di event yaa~ (≧∇≦)/",
    "Fuuka siap kasih tahu xtall event yang menarik buat diburu yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka bantu terangkan daftar xtall event biar gampang dipahami yaa~ (o^▽^o)",
  ],
  pet: [
    "Nih yaa, Fuuka ajarin cara mengasuh pet pelan-pelan biar hasilnya bagus~ (≧▽≦)",
    "Yuk yuk, Fuuka bantu jelasin cara pelihara dan build pet yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau pet yang rapi, sini Fuuka ajarin langkah ngurusnya yaa~ (〃▽〃)",
    "Hehee, sekarang Fuuka terangkan cara merawat pet dari awal yaa~ (o^▽^o)",
    "Fuuka siap bantu ajarin gimana cara mengasuh pet dengan benar~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka tunjukin cara build dan latih pet~ (≧◡≦)",
    "Biar pet onii-chan makin oke, Fuuka jelasin langkah-langkahnya yaa~ (〃ω〃)",
    "Mari belajar jadi pengasuh pet yang manis bareng Fuuka yaa~ (≧∇≦)/",
    "Fuuka siap kasih panduan singkat buat build dan rawat pet yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka bantu terangkan cara membesarkan pet sampai jadi yaa~ (o^▽^o)",
  ],
  raid: [
    "Nih yaa, Fuuka ajarin cara raid yang lebih rapi dan aman pelan-pelan~ (≧▽≦)",
    "Yuk yuk, Fuuka bantu jelasin biar onii-chan makin jago pas raid yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau raid lebih lancar, sini Fuuka terangkan pattern dan posisinya yaa~ (〃▽〃)",
    "Hehee, sekarang Fuuka kasih tips biar raid onii-chan jadi lebih baik yaa~ (o^▽^o)",
    "Fuuka siap bantu ngajarin cara hadapin boss raid dengan lebih tenang~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka tunjukin posisi aman dan pattern berbahaya saat raid~ (≧◡≦)",
    "Biar nggak panik pas raid, Fuuka jelasin tips pentingnya satu-satu yaa~ (〃ω〃)",
    "Mari belajar raid yang kompak dan aman bareng Fuuka yaa~ (≧∇≦)/",
    "Fuuka siap kasih panduan kecil biar performa raid onii-chan makin bagus yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka bantu terangkan cara melakukan raid dengan lebih baik yaa~ (o^▽^o)",
  ],
  statusPoint: [
    "Nih yaa, Fuuka jadi guru cilik dulu buat jelasin efek status poin pelan-pelan~ (≧▽≦)",
    "Yuk yuk, Fuuka bantu terangkan pengaruh status poin ke player yaa~ (๑˃ᴗ˂)ﻭ",
    "Kalau mau paham status poin, sini Fuuka jelasin satu-satu yaa~ (〃▽〃)",
    "Hehee, sekarang Fuuka ajarin efek status poin ke karakter yaa~ (o^▽^o)",
    "Fuuka siap bantu ngajarin fungsi status poin dengan cara yang gampang yaa~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka jelasin pengaruh tiap status ke player~ (≧◡≦)",
    "Biar nggak bingung bagi status, Fuuka terangkan efeknya satu-satu yaa~ (〃ω〃)",
    "Mari belajar status poin bareng guru cilik Fuuka yaa~ (≧∇≦)/",
    "Fuuka siapin penjelasan ini biar onii-chan gampang ngerti efek status poin~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka bantu terangkan bagaimana status poin memengaruhi player yaa~ (o^▽^o)",
  ],
  ailment: [
    "Nih yaa, Fuuka mau peringatkan onii-chan biar hati-hati sama ailment dan interrupt ini~ (≧▽≦)",
    "Yuk yuk, dengar baik-baik yaa... Fuuka jelasin efek status buruk yang harus diwaspadai~ (๑˃ᴗ˂)ﻭ",
    "Kalau nggak hati-hati, ailment bisa ganggu banget lho... jadi Fuuka jelasin yaa~ (〃▽〃)",
    "Hehee, sekarang Fuuka kasih peringatan manis soal interrupt dan status buruk yaa~ (o^▽^o)",
    "Fuuka siap bantu kasih tahu debuff berbahaya biar onii-chan lebih waspada~ (≧ω≦)",
    "Pelan-pelan yaa, Fuuka terangkan efek status buruk yang bisa bikin repot~ (≧◡≦)",
    "Biar nggak kaget pas kena ailment, Fuuka jelasin dulu satu-satu yaa~ (〃ω〃)",
    "Mari belajar hati-hati sama interrupt dan ailment bareng Fuuka yaa~ (≧∇≦)/",
    "Fuuka siap kasih peringatan kecil supaya onii-chan nggak lengah saat battle yaa~ (๑˃ᴗ˂)ﻭ",
    "Nih, Fuuka bantu terangkan status buruk ini biar onii-chan lebih siap yaa~ (o^▽^o)",
  ],
};

const luckOpeners = [
  "Fufu~ Fuuka cek hokinya dulu yaa (≧∇≦)/",
  "Ehehe, tes kehokian dimulaii~ (๑˃ᴗ˂)",
  "Yuk yuk, Fuuka intip aura hokinya yaa~ (≧ω≦)",
  "Jeng jeng~ Fuuka mau lihat hoki hari ini nih~ (o^▽^o)",
  "Hehe, Fuuka putar roda keberuntungan dulu yaa~ (≧◡≦)",
  "Okeee, Fuuka cek nasib manisnya dulu~ (๑˃ᴗ˂)ﻭ",
  "Sebentar yaa, Fuuka kibas-kibas kartu hoki dulu~ (ﾉ´ヮ`)ﾉ*:･ﾟ✧",
  "Hoki meter Fuuka mulai nyala nih, ting ting~ (o^▽^o)",
  "Fuuka buka radar keberuntungan dulu yaa~ (≧◡≦)",
  "Mata Fuuka siap scan aura hoki onii-chan~ (☆▽☆)",
  "Duduk manis dulu, hasil hokinya lagi Fuuka racik~ (´꒳`)",
  "Fuuka kocok angka keberuntungan dulu yaa~ (๑˃ᴗ˂)",
  "Ayo lihat nasib manis hari ini bareng Fuuka~ (≧ω≦)",
  "Fuuka panggil peri hoki sebentar yaa~ (˶ᵔ ᵕ ᵔ˶)",
  "Taraaa~ mesin kehokian Fuuka mulai jalan~ (≧∇≦)/",
  "Jangan kedip, angka hoki onii-chan mau muncul~ (｡•̀ᴗ-)✧",
  "Fuuka cek dulu, semoga hasilnya gemesin yaa~ (〃▽〃)",
  "Bismillah hoki manis, Fuuka mulai hitung yaa~ (๑•̀ㅂ•́)و",
  "Fufu, aura onii-chan lagi Fuuka timbang pelan-pelan~ (￣▽￣*)ゞ",
  "Onii-chan siap? Fuuka intip angka rahasianya dulu~ (o´▽`o)",
];

const hokiResponses = {
  0: [
    "Yahh... 0% nih onii-chan, aura hokinya lagi tidur total~ bleee :p",
    "Ehehe... 0% dong, bahkan keberuntunganmu malu buat muncul~ (￣▽￣*)ゞ",
    "Fuuka cek lagi... tetep 0%. Aduh, ini mah zonk imut~ (´ . .̫ . `)",
    "0% yaa... dompet gacha kamu harus diselametin dulu deh~ (≧▽≦)",
    "Astaga, 0% beneran. Hoki onii-chan kabur entah ke mana~ :3",
    "Fuuka nggak bohong yaa... hasilnya 0%. Sedih tapi lucu~ (˶ᵔ ᵕ ᵔ˶)",
    "0% nih! Bahkan semangetnya Fuuka lebih tinggi dari hokimu hari ini~ (≧ω≦)",
    "Onii-chan dapat 0%... peluk dulu sini, jangan nangis yaa~ (｡•́︿•̀｡)",
    "0% muncul pelan-pelan... Fuuka ikut diem sebentar deh~ (´･ᴗ･`)",
    "Aduh, 0% yaa. Hokinya lagi cuti panjang kayaknya~ (￣▽￣*)ゞ",
    "0% nih, tapi Fuuka tetap kasih semangat imut buat onii-chan~ (๑˃ᴗ˂)",
    "Hasilnya kosong manis... jangan dipakai duel nasib dulu yaa~ (´꒳`)",
    "0% terdeteksi! Fuuka bungkusin keberanian kecil dulu~ (｡•̀ᴗ-)✧",
    "Yaaah, angka hokinya malu banget sampai nggak muncul~ (〃▽〃)",
    "0% ini bukan apes, cuma hoki lagi mode sembunyi~ (˶ᵔ ᵕ ᵔ˶)",
    "Fuuka ulang lihat... tetap 0%. Lucu tapi bahaya~ (≧ω≦)",
    "Hari ini 0%, onii-chan. Gacha ditunda dulu yaa, sayang~ (｡•́︿•̀｡)",
    "Hoki onii-chan tidur pules banget, Fuuka nggak tega bangunin~ (￣o￣) zzZ",
    "0% yaa... Fuuka kasih teh manis keberuntungan dulu deh~ (o^▽^o)",
    "Zonk kecil datang menyapa, tapi Fuuka tetap di pihakmu~ (๑•̀ㅂ•́)و",
  ],
  1: [
    "1% yaa~ tipis banget, tapi masih ada sisa harapan kecil imut~ (๑•̀ㅂ•́)و",
    "Fuuka lihat ada 1% hoki... kecil banget sampe hampir ilang~ :p",
    "1% doang, onii-chan. Kedip dikit juga lewat~ (￣y▽￣)╭",
    "Ehehe, 1%~ minimal nggak 0% yaa, syukuri dulu~ (˶ᵔ ᵕ ᵔ˶)",
    "1% nih. Hoki kamu lagi malu-malu munculnya~ (〃▽〃)",
    "Fuuka kasih laporan: 1%. Masih mending daripada zonk total~ (´꒳`)",
    "1% yaa... ini keberuntungan versi cicilan kayaknya~ (≧▽≦)",
    "Tipis-tipis 1%, onii-chan. Jangan dipake gacha dulu deh~ :3",
    "1% muncul malu-malu, kayak hoki kecil lagi ngintip~ (〃▽〃)",
    "Fuuka nemu 1% nih, kecil tapi masih bisa dielus-elus~ (´꒳`)",
    "Hoki 1% itu mungil banget, jangan ditakutin yaa~ (˶ᵔ ᵕ ᵔ˶)",
    "1% yaa... cukup buat nyalain lilin harapan mini~ (o^▽^o)",
    "Ada 1% imut nyangkut di pojokan nasibmu~ (≧ω≦)",
    "Fuuka lapor: 1% hoki berhasil diselamatkan~ (๑•̀ㅂ•́)و",
    "1% ini tipis, tapi Fuuka anggap dia berani muncul~ (｡•̀ᴗ-)✧",
    "Onii-chan dapat 1%, masih kecil tapi nggak sendirian~ (๑˃ᴗ˂)",
    "Hokinya 1%, kayak remah kue keberuntungan~ (≧◡≦)",
    "1% nih, Fuuka simpan baik-baik biar nggak kabur~ (￣▽￣*)ゞ",
    "Hasilnya 1%, kecil gemes tapi belum siap tempur~ (o´▽`o)",
    "Satu persen dulu yaa, pelan-pelan nanti bisa tumbuh~ (´｡• ᵕ •｡`)",
  ],
  2: [
    "2% yaa~ hokinya mulai bangun, tapi masih ngulet dulu~ (￣o￣) zzZ",
    "Fuuka hitung-hitung... hasilnya 2%. Masih mini banget~ (≧ω≦)",
    "2% dong, sedikit lebih baik tapi tetap rawan ditikung nasib~ :p",
    "Ehehe, 2% itu lucu sih... kecil, tapi ada~ (˶ᵔ ᵕ ᵔ˶)",
    "Hasil tesnya 2%! Hoki onii-chan udah muncul setitik~ (๑˃ᴗ˂)ﻭ",
    "2% yaa, semoga nanti naik... sekarang sih masih mode hemat~ (´ . .̫ . `)",
    "Fuuka bilang 2% nih. Jangan sombong dulu yaa~ (￣▽￣*)ゞ",
    "2% hoki terdeteksi! Masih kategori receh tapi manis~ (o^▽^o)",
    "2% yaa, hokinya udah bangun tapi masih pakai selimut~ (´꒳`)",
    "Fuuka nemu 2% kecil di balik awan nasibmu~ (≧◡≦)",
    "Hoki 2% itu mungil, tapi sudah mulai berani jalan~ (๑˃ᴗ˂)",
    "2% nih, onii-chan. Jangan diajak lari dulu, nanti capek~ (￣▽￣)",
    "Ehehe, 2% ini kayak bibit hoki yang baru tumbuh~ (˶ᵔ ᵕ ᵔ˶)",
    "Fuuka catat 2%, cukup buat senyum satu garis dulu~ (〃▽〃)",
    "2% muncul! Kecil, tapi Fuuka tepuk tangan pelan~ (o^▽^o)",
    "Hoki onii-chan 2%, masih belajar jadi kuat nih~ (๑•̀ㅂ•́)و",
    "2% yaa, nasib baiknya baru stretching~ (￣o￣) zzZ",
    "Fuuka lihat 2% berkilau tipis-tipis~ (☆▽☆)",
    "Hasilnya 2%, cukup imut buat dibawa pulang~ (o´▽`o)",
    "2% dulu yaa, jangan sedih, Fuuka temenin kok~ (｡•́︿•̀｡)",
  ],
  5: [
    "5% yaa~ lumayan buat senyum tipis dulu, onii-chan~ (´꒳`)",
    "Hokinya 5%! Masih kecil, tapi udah bisa pamer dikit~ (≧▽≦)",
    "Fuuka cek hasilnya 5% yaa, lumayan buat modal pede~ (๑•̀ㅂ•́)و",
    "5% nih! Belum wah banget, tapi nggak malu-maluin~ (￣▽￣)",
    "Ehehe, 5% itu hoki mini yang lucu yaa~ (o^▽^o)",
    "Fuuka umumkan: 5%! Mulai ada cahaya keberuntungan~ (≧ω≦)",
    "5% yaa, cukup buat bilang 'masih ada harapan'~ (˶ᵔ ᵕ ᵔ˶)",
    "Hasilnya 5%! Tipis, tapi udah nggak bikin Fuuka khawatir~ (๑˃ᴗ˂)",
    "5% nih, hoki kecilnya mulai pakai pita lucu~ (≧◡≦)",
    "Fuuka lihat 5%, belum besar tapi sudah ada niat baik~ (´꒳`)",
    "5% yaa, cukup buat langkah pertama yang manis~ (o^▽^o)",
    "Hoki 5% itu kayak senyum malu-malu dari nasib~ (〃▽〃)",
    "5% muncul, onii-chan boleh pede setengah centi dulu~ (￣▽￣*)ゞ",
    "Fuuka kasih nilai 5%, kecil tapi punya pesona~ (˶ᵔ ᵕ ᵔ˶)",
    "5% nih, jangan boros dipakai buat hal nekat yaa~ (｡•̀ᴗ-)✧",
    "Hokinya 5%, Fuuka bungkusin dengan semangat imut~ (๑•̀ㅂ•́)و",
    "5% yaa, belum mantap tapi sudah nggak nol lagi~ (≧ω≦)",
    "Fuuka temukan 5% di saku keberuntunganmu~ (o´▽`o)",
    "Hasil 5% ini lucu, kayak hoki masih latihan senyum~ (´｡• ᵕ •｡`)",
    "5% dulu, onii-chan. Pelan-pelan nanti naik kelas~ (๑˃ᴗ˂)ﻭ",
  ],
  10: [
    "10% yaa~ nah, ini baru mulai enak dilihat~ (´꒳`)",
    "Fuuka kasih nilai hoki 10%! Sudah lumayan manis nih~ (o^▽^o)",
    "10% dong, onii-chan. Ada bakat beruntung dikit~ (≧ω≦)",
    "Ehehe, 10% itu udah bisa bikin Fuuka angguk-angguk puas~ (˶ᵔ ᵕ ᵔ˶)",
    "Hoki kamu 10%! Masih santai, tapi udah aman~ (๑•̀ㅂ•́)و",
    "Fuuka deteksi 10% yaa~ keberuntunganmu mulai rajin masuk kerja~ (≧▽≦)",
    "10% nih, cukup buat bikin hari onii-chan agak cerah~ (๑˃ᴗ˂)",
    "Lumayan~ 10%! Bukan sultan hoki, tapi nggak apes juga~ (￣▽￣)",
    "10% nih, Fuuka mulai lihat kilau kecil di auramu~ (☆▽☆)",
    "Hoki 10% itu sudah cukup buat senyum manis dulu~ (o^▽^o)",
    "Fuuka catat 10%, awal yang cukup gemesin yaa~ (≧◡≦)",
    "10% muncul rapi, kayak hoki kecil siap apel pagi~ (๑•̀ㅂ•́)و",
    "Ehehe, 10% ini masih mungil tapi nggak mengecewakan~ (´꒳`)",
    "10% yaa, cukup buat bilang hari ini masih ramah~ (˶ᵔ ᵕ ᵔ˶)",
    "Fuuka kasih tepuk tangan kecil buat 10% ini~ (ﾉ´ヮ`)ﾉ*:･ﾟ✧",
    "Hokinya 10%, onii-chan boleh senyum dikit lebih lebar~ (〃▽〃)",
    "10% nih, nasib baiknya mulai masuk frame~ (｡•̀ᴗ-)✧",
    "Fuuka lihat 10%, belum wow tapi sudah manis~ (≧ω≦)",
    "Hasil 10%, cukup buat modal percaya diri kecil~ (o´▽`o)",
    "10% yaa, bukan jackpot, tapi bukan zonk juga~ (￣▽￣*)ゞ",
  ],
  20: [
    "20% yaa~ wah, onii-chan mulai wangi hoki nih~ (≧▽≦)",
    "Fuuka senyum dulu... hasilnya 20%! Lumayan cakep~ (´꒳`)",
    "20% dong! Hoki kamu mulai bisa diajak kerja sama~ (๑•̀ㅂ•́)و",
    "Ehehe, 20% itu udah masuk kategori lumayan banget yaa~ (o^▽^o)",
    "Hasil tes kehokian: 20%! Fuuka setuju ini cukup bagus~ (๑˃ᴗ˂)",
    "20% yaa, udah boleh agak pede dikit~ (￣▽￣)",
    "Fuuka lihat aura hijau-hijau... eh ternyata 20% hoki~ (≧ω≦)",
    "20% nih! Keberuntunganmu mulai ngelirik balik, onii-chan~ (〃▽〃)",
    "20% yaa, hoki onii-chan mulai kelihatan pipinya~ (≧◡≦)",
    "Fuuka senang lihat 20%, ini sudah lumayan imut~ (o^▽^o)",
    "Hoki 20% mulai jalan pelan-pelan ke arahmu~ (´꒳`)",
    "20% nih, cukup buat bikin nasib tersenyum tipis~ (˶ᵔ ᵕ ᵔ˶)",
    "Fuuka catat 20%, sudah boleh optimis kecil-kecilan~ (๑•̀ㅂ•́)و",
    "20% muncul dengan gaya manis, nggak buruk sama sekali~ (๑˃ᴗ˂)",
    "Hasil 20%, onii-chan mulai punya aura cerah nih~ (☆▽☆)",
    "20% yaa, Fuuka suka progress kecil begini~ (o´▽`o)",
    "Keberuntungan 20% lagi nyapa sopan ke onii-chan~ (〃▽〃)",
    "Fuuka deteksi 20%, ini hoki mini yang cukup rajin~ (≧ω≦)",
    "20% nih, cukup buat coba hal kecil yang aman~ (｡•̀ᴗ-)✧",
    "Hokinya 20%, belum sultan tapi sudah punya senyum~ (￣▽￣)",
  ],
  25: [
    "25% yaa~ seperempat sultan hoki nih, ehehe~ (≧ω≦)",
    "Fuuka kasih hasil 25%! Udah lumayan ganteng hokinya~ (๑•̀ㅂ•́)و",
    "25% dong, onii-chan. Keberuntunganmu mulai serius~ (￣▽￣)",
    "Ehehe, 25% itu enak yaa... nggak kebanyakan, nggak kurang~ (˶ᵔ ᵕ ᵔ˶)",
    "Hoki kamu 25%! Fuuka approve hasil ini~ (o^▽^o)",
    "25% nih, sudah masuk level 'boleh dicoba'~ (๑˃ᴗ˂)",
    "Fuuka deteksi 25%! Aura beruntungmu lagi naik pelan-pelan~ (≧▽≦)",
    "25% yaa~ lucu juga, hokinya pas di tengah-tengah manis~ (´꒳`)",
    "25% nih, seperempat jalan menuju hoki cakep~ (๑•̀ㅂ•́)و",
    "Fuuka lihat 25%, sudah cukup manis buat dipuji~ (o^▽^o)",
    "Hoki 25% datang dengan langkah kecil yang rapi~ (˶ᵔ ᵕ ᵔ˶)",
    "25% yaa, onii-chan mulai punya modal senyum~ (〃▽〃)",
    "Fuuka kasih bintang kecil buat 25% ini~ (☆▽☆)",
    "Hasil 25%, cukup stabil dan tetap imut~ (≧◡≦)",
    "25% nih, nasib baiknya sudah mulai betah dekat kamu~ (๑˃ᴗ˂)",
    "Ehehe, 25% ini kayak hoki pakai sepatu baru~ (o´▽`o)",
    "Fuuka catat 25%, boleh dicoba tapi tetap kalem yaa~ (｡•̀ᴗ-)✧",
    "Hokinya 25%, Fuuka angguk manis dulu~ (´｡• ᵕ •｡`)",
    "25% yaa, lumayan buat bawa perasaan positif~ (≧ω≦)",
    "Seperempat hoki terkumpul, onii-chan jangan jumawa dulu~ (￣▽￣*)ゞ",
  ],
  50: [
    "50% yaa~ wah, setengah dewa hoki nih onii-chan~ (≧▽≦)",
    "Fuuka tepuk tangan dulu! 50% itu cakep banget~ (๑˃ᴗ˂)ﻭ",
    "Hasilnya 50%! Kalau gagal, berarti nasib aja yang iseng~ :p",
    "Ehehe, 50% itu udah bikin Fuuka ikut semangat~ (≧ω≦)",
    "50% dong! Hoki kamu lagi separuh full power~ (o^▽^o)",
    "Fuuka umumkan: 50%! Ini udah level mantap yaa~ (๑˃ᴗ˂)",
    "50% nih, separuh dunia lagi dukung onii-chan~ (´꒳`)",
    "Wahh 50%! Udah boleh senyum lebar tuh~ (〃▽〃)",
    "50% nih, Fuuka suka angka seimbang yang manis begini~ (o^▽^o)",
    "Setengah hoki terkumpul! Onii-chan mulai bersinar~ (☆▽☆)",
    "50% yaa, ini sudah enak banget buat dilihat~ (≧◡≦)",
    "Fuuka catat 50%, nasib baiknya lumayan nurut~ (๑•̀ㅂ•́)و",
    "Hokinya 50%, kalau senyum sekarang cocok banget~ (˶ᵔ ᵕ ᵔ˶)",
    "50% muncul cakep, Fuuka ikut tepuk tangan kecil~ (ﾉ´ヮ`)ﾉ*:･ﾟ✧",
    "Ehehe, setengah jalan menuju hoki dewa nih~ (≧ω≦)",
    "50% yaa, cukup kuat buat bikin onii-chan pede~ (｡•̀ᴗ-)✧",
    "Hasilnya 50%, Fuuka kasih label mantap imut~ (๑˃ᴗ˂)",
    "Hoki separuh full, hati-hati nanti ketagihan pede~ (￣▽￣*)ゞ",
    "50% nih, aura hoki onii-chan sudah kelihatan rapi~ (o´▽`o)",
    "Fuuka senang lihat 50%, rasanya pas dan manis~ (´꒳`)",
  ],
  99: [
    "99% yaa?! Onii-chan lagi dicium dewi hoki nih kayaknya~ (≧▽≦)",
    "Fuuka kaget! 99% itu hampir sempurna, manis banget~ (๑˃ᴗ˂)ﻭ",
    "99% dong! Tinggal 1% lagi jadi monster keberuntungan~ (≧ω≦)",
    "Ehehe, 99% ini udah bikin Fuuka ikut iri dikit~ (〃▽〃)",
    "Hokinya 99%! Onii-chan hari ini bahaya banget kalau digacha-in~ (o^▽^o)",
    "Fuuka kasih stempel: 99%! Ini level sultan hoki premium~ (￣▽￣)",
    "99% yaa, keberuntunganmu hari ini nyaris nggak masuk akal~ (´꒳`)",
    "Aaaa 99%! Fuuka curiga onii-chan nyimpen lucky charm rahasia~ (๑˃ᴗ˂)",
    "99% nih?! Fuuka sampai cek dua kali saking kinclongnya~ (☆▽☆)",
    "Hoki 99% itu hampir terlalu manis buat dipercaya~ (≧◡≦)",
    "Onii-chan 99%, aura beruntungnya nyaris menyilaukan~ (o^▽^o)",
    "Fuuka lihat 99%, ini mah nasib baik nempel erat~ (๑•̀ㅂ•́)و",
    "99% yaa, jangan-jangan hari ini semua pintu kebuka~ (˶ᵔ ᵕ ᵔ˶)",
    "Hasil 99%, Fuuka ikut bangga sambil senyum lebar~ (〃▽〃)",
    "99% datang dengan gaya elegan, hampir sempurna banget~ (｡•̀ᴗ-)✧",
    "Ehehe, 99% ini bikin Fuuka pengen minta tips hoki~ (´꒳`)",
    "Onii-chan hampir full hoki, tinggal seujung rambut lagi~ (≧ω≦)",
    "Fuuka kasih pita emas buat 99% ini~ (ﾉ´ヮ`)ﾉ*:･ﾟ✧",
    "99% nih, angka yang bikin hari terasa manis banget~ (o´▽`o)",
    "Hoki onii-chan 99%, Fuuka sampai ikut berbinar~ (๑˃ᴗ˂)ﻭ",
  ],
  100: [
    "100%!!! Onii-chan resmi jadi sepuh hoki hari iniii~ (≧▽≦)",
    "Fuuka teriak dulu: 100%! Ini mah hoki max level! (≧∇≦)/",
    "100% dong?! Bahkan nasib pun nurut sama onii-chan hari ini~ (๑˃ᴗ˂)ﻭ",
    "Ehehe... 100% itu bukan beruntung lagi, itu curang manis~ (≧ω≦)",
    "Fuuka kasih mahkota imut: 100%! Raja hoki muncul~ (￣▽￣)",
    "100% yaa! Kalau masih gagal juga, itu semesta yang salah~ (o^▽^o)",
    "Aaaa 100%! Fuuka sampai pengen numpang hoki dikit dong~ (｡•́︿•̀｡)",
    "Fix 100%! Aura hokimu nyala terang banget hari ini~ (๑˃ᴗ˂)",
    "100%!!! Fuuka kasih mahkota hoki super imut~ (☆▽☆)",
    "Hoki full power! Onii-chan hari ini bersinar banget~ (≧◡≦)",
    "100% yaa, angka sempurna yang bikin Fuuka meloncat kecil~ (o^▽^o)",
    "Fuuka cek ulang: tetap 100%. Ini bukan mimpi, onii-chan~ (๑•̀ㅂ•́)و",
    "Hasil 100%, semua bintang keberuntungan lagi dukung kamu~ (ﾉ´ヮ`)ﾉ*:･ﾟ✧",
    "100% nih! Fuuka sampai pengen pasang banner selamat~ (≧∇≦)/",
    "Onii-chan full hoki, hati-hati nasib baik jadi manja~ (￣▽￣*)ゞ",
    "Ehehe, 100% ini manis banget sampai Fuuka iri dikit~ (〃▽〃)",
    "100% yaa, keberuntunganmu hari ini mode festival~ (o´▽`o)",
    "Fuuka kasih stempel besar: hoki maksimal dan super gemes~ (˶ᵔ ᵕ ᵔ˶)",
    "Hoki 100%, onii-chan resmi jadi anak emas nasib hari ini~ (｡•̀ᴗ-)✧",
    "Aaaa 100%! Fuuka tepuk tangan sampai pipi ikut senyum~ (๑˃ᴗ˂)ﻭ",
  ],
};
function getRandomCuteFooter() {
  return cuteFooterQuestions[
    Math.floor(Math.random() * cuteFooterQuestions.length)
  ];
}

function getRandomGreetingLines() {
  return dynamicGreetings[Math.floor(Math.random() * dynamicGreetings.length)];
}

function getRandomIntro(topicKey) {
  const intros = topicHeaderIntros[topicKey] || topicHeaderIntros.menu;
  return intros[Math.floor(Math.random() * intros.length)];
}

function getRandomLuckResult() {
  const percentage =
    luckPercentages[Math.floor(Math.random() * luckPercentages.length)];
  const responses = hokiResponses[percentage];
  const response = responses[Math.floor(Math.random() * responses.length)];
  const opener = luckOpeners[Math.floor(Math.random() * luckOpeners.length)];

  return { percentage, response, opener };
}

function normalizeSpacing(text) {
  return String(text)
    .split("\n")
    .map((line) => line.trimEnd())
    .join("\n")
    .trim();
}

function formatHelpMessage(content, topicKey = "menu") {
  const body = normalizeSpacing(content);
  const [greetingLine] = getRandomGreetingLines();
  const introLine = getRandomIntro(topicKey);

  return [
    greetingLine,
    "",
    introLine,
    "",
    divider,
    "MENU",
    divider,
    "",
    body,
    divider,
    "",
    getRandomCuteFooter(),
  ]
    .filter((line, index, array) => {
      if (line !== "") {
        return true;
      }

      return array[index - 1] !== "";
    })
    .join("\n");
}

function formatTopicMessage(content, topicKey, options = {}) {
  const body =
    options.useReadMore === false
      ? normalizeSpacing(content)
      : insertReadMoreAfterTitle(content);
  const [greetingLine] = getRandomGreetingLines();
  const introLine = getRandomIntro(topicKey);
  const footerLine = getRandomTopicFooter(topicKey);

  return [greetingLine, "", introLine, "", body, "", footerLine].join("\n");
}

function insertReadMoreAfterTitle(content) {
  const lines = normalizeSpacing(content).split("\n");

  if (lines.length <= 3) {
    return normalizeSpacing(content);
  }

  return [...lines.slice(0, 3), readMoreSpacer, ...lines.slice(3)].join("\n");
}

function getRandomTopicFooter(topicKey) {
  const footers = topicFooterQuestions[topicKey];

  if (!footers || footers.length === 0) {
    return getRandomCuteFooter();
  }

  return footers[Math.floor(Math.random() * footers.length)];
}

const helpMenuText = [
  "#1   > Makna dan Sejarah Pendirian Guild",
  "",
  "#2   > Panduan Newbie",
  "#3   > Kode Buff Player Toram",
  "#4   > Bahan MQ",
  "#5   > Perluas Tas",
  "#6   > Leveling Char",
  "",
  "#7   > Tips Refine",
  "#8   > Stat Blacksmith",
  "#9   > Leveling Prof / Kemahiran Tempa",
  "#10 > Potensial Equipment",
  "#11 > Leveling Prof / Kemahiran Padu",
  "",
  "#12 > Xtall Master",
  "#13 > Xtall Event",
  "",
  "#14 > Info Seputar Pet",
  "#15 > Tips Raid",
  "#16 > Pengaruh Status Pada Karakter",
  "#17 > Detail Ailment & Interupt",
  "",
  "#98 > Kata Mutiara Sepuh",
  "#99 > Tes Kehokian",
].join("\n");

const topicReplies = {
  "#1": [
    divider,
    "*Makna dan Sejarah Pendirian Guild*",
    divider,
    "",
    "*Nama Guild*",
    "Force Knight artinya kekuatan ksatria",
    "",
    "*Logo Guild*",
    "Maknanya menggambarkan beragam job. Pada logo guild terdapat ksatria yang dibelakangnya dua pedang (kekuatan fisik jarak dekat), dua tongkat (kekuatan sihir), dan satu panah (kekuatan fisik jarak jauh). Kesimpulannya bisa semua jenis job",
    "",
    "*Bot Guild*",
    "Nama Fuuka terdapat huruf F & K merupakan awal huruf dari Force & Knight",
    "",
    "*Sejarah Pendirian Guild*",
    "",
    "*Juli 2020*",
    "Petualang bernama Master-A masuk ke dunia Toram.",
    "",
    "*Oktober 2020*",
    "Master-A bertekad untuk membentuk guild.",
    "",
    "*November 2020*",
    "Pembuatan nama guild Force Knight.",
    "",
    "*21 Februari 2021*",
    "Pendirian Guild Force Knight bersamaan dengan Perayaan ulangtahun Master-A",
    "",
    "*21 Oktober 2021*",
    "Peresmian dan perombakan susunan pengurus guild",
    "",
    "Guild Force Knight didirikan pada tanggal 21 Februari 2021 oleh Master-A selaku Guild Master (GM) dengan dibantu oleh 7 rekan pendiri terdahulu. Beberapa kali guild ini mengalami perombakan posisi Vice Guild Master (VGM). Saat ini terdapat 1 VGM sebagai berikut: Squeshy",
    divider,
  ].join("\n"),
  "#2": [
    divider,
    "Panduan Newbie",
    divider,
    "",
    "Newbie Tutorial by FK",
    "https://docs.google.com/document/d/1sGEPthwNcaCkuFhw_3KoRs7QbyxWppDkwhu0D8vYPT0/edit?usp=sharing",
    "",
    "Tutorial Video",
    "Channel yt: YusagiKurumi",
    "",
    "1. Bow (Cap 270)",
    "https://youtu.be/e8solPHDTJE?si=mdB4b8qkmd2T7awV",
    "",
    "2. Katana (Cap 280)",
    "https://youtu.be/ucX6s4Xb8IU?si=afb1IMXXocdfjkIE",
    "",
    "3. Dual Sword (Cap 290)",
    "https://youtu.be/NF8hEtuxJqc?si=z_PUAdIiLmPiMIWc",
    "",
    "4. Bow Tana (Cap 310)",
    "https://youtu.be/M2hG6T6CisE?si=DFZTs5fLNMtlm8re",
    "",
    divider,
  ].join("\n"),
  "#3": [
    divider,
    "Kode Buff Player Toram",
    divider,
    "",
    "*List Buff*",
    "",
    "Max HP",
    "1180755",
    "",
    "Max MP",
    "9090903",
    "",
    "AMPR",
    "1234561",
    "",
    "Critical Rate",
    "1100000",
    "",
    "MATK",
    "52255555",
    "",
    "ATK",
    "5130123",
    "",
    "Weapon ATK",
    "7123456",
    "",
    "STR",
    "1110033",
    "",
    "INT",
    "9090903",
    "",
    "VIT",
    "5130123",
    "",
    "AGI",
    "7162029",
    "",
    "DEX",
    "9090904",
    "",
    "Physical Resist",
    "9090907",
    "",
    "Magic Resist",
    "2020505",
    "",
    "Kebal bumi",
    "6150029",
    "",
    "Frac Barrier",
    "6150029",
    "",
    "Aggro +%",
    "2020606",
    "",
    "Aggro -%",
    "1010147",
    "",
    "DTE Bumi",
    "4111113",
    "2210103",
    "",
    "DTE Api",
    "3210106",
    "2210106",
    "",
    "DTE Air",
    "7150030",
    "2210100",
    "",
    "DTE Angin",
    "8080804",
    "7257777",
    "3149696",
    "2210101",
    "",
    "DTE Cahaya",
    "6010289",
    "2210105",
    "",
    "DTE Gelap",
    "6116116",
    "5010092",
    "2210104",
    "",
    "DTE Netral",
    "1234561",
    "2210102",
    "",
    "*Code buffland member/admin*",
    "",
    "MP         : punkz",
    "AMPR       : hsans, moung zy",
    "WATK       : Master-A",
    "DTE earth  : medzzo",
    "",
    divider,
  ].join("\n"),
  "#4": [
    divider,
    "BAHAN MQ",
    divider,
    "",
    "Catatan: MQ adalah Main Quest atau Quest Utama.",
    "",
    "*BAB 1 :*",
    "- Daun Colon (Colon Leaf) x5",
    "- Sisik Naga (Hard Dragon Skin) x2",
    "- Daging Domba (Lamb Meat) x1",
    "- Sulur (Vine) x3",
    "- Paruh Tebal (Thick Beak) x3",
    "- Sayap Peri (Fairy Feather) x3",
    "",
    "*BAB 2 :*",
    "- Koin Ksatria (Swordsman Stone Coin) x20",
    "",
    "*BAB 3 :*",
    "- Daging Tikus Pasir (Sand Mole Meat) x1",
    "- Cakar Binatang Buas (Beast Claw) x3",
    "- Kulit Kodok Pasir (Sand Frog Skin) x5",
    "- Taring Bergerigi (Jagged Fang) x10",
    "- Kristal Saham (Saham Crystal) x5",
    "- Permata Jiwa (Spiritual Gemstone) x1",
    "",
    "*BAB 8 :*",
    "- Anggur Rokoko (Rokoko Grape) x5",
    "",
    "*BAB 9 :*",
    "- Kayu Labilans (Labilans Wood) x10",
    "",
    "*BAB 11 :*",
    "- Tanduk Patah (Broken Horn) x20",
    "",
    "*BAB 12 :*",
    "- Biji Berkembang (Growing Ore) x5",
    "- Batu Jabali (Jabali Stone) x5",
    "",
    "*BAB 14 :*",
    "- Kulit Tebal Berlendir (Slimy Thick Skin) x20",
    "- Akar Melilit (Tangled Roots) x10",
    "- Kayu Menabra (Menabra Wood) x10",
    "",
    "*BAB 15 :*",
    "- Pupuk Keruh (Stagnant Fertilizer) x10",
    "",
    divider,
  ].join("\n"),
  "#5": [
    divider,
    "Perluas Tas",
    divider,
    "",
    "*List Bahan Untuk Upgrade Slot Tas by Guild Force Knight*",
    "",
    "◻️*50-51*",
    "- Kulit Colon x1 (Colon; _Tanah Pembangunan_) = ±1.000",
    "",
    "◻️*51-52*",
    "- Kulit Berkualitas x1 (Lavarca; _Dataran Rakau_) = ±3.500",
    "",
    "◻️*52-53*",
    "- Spina x1.000",
    "",
    "◻️*53-54*",
    "- Kulit Minotaur x1 (Minotaur; _Kuil Runtuh: Area Terlarang_) = ±12.000",
    "- Pecahan Kristal Jingga x1 (Cobre; _Danau Icule_) = ±6.000",
    "",
    "◻️*54-55*",
    "- Kulit Anjing Hutan x1 (Anjing Hutan; _Hutan Marbabo: Bagian Dalam_) = ±5.000",
    "- Lencana Goblin x1 (Boss Goblin; _Gua Ribisco: Bagian Dalam_) = ±7.500",
    "",
    "◻️*55-56*",
    "- Spina x2.000",
    "",
    "◻️*56-57*",
    "- Bulu Mochelo x1 (Mochelo; _Lereng Merapi A3_) = ±12.000",
    "- Kain Linen x10 (Crow Killer; _Dusun Douce_) = ±60.000",
    "",
    "◻️*57-58*",
    "- Bulu Naga Giok x1 (Forestia; _Tanah Kaos_) = ±20.000",
    "- Tanduk Berkualitas x10 (Bandot; _Tanah Tinggi Yorl_) = ±300.000",
    "",
    "◻️*58-59*",
    "- Sabuk Bos Roga x1 (Boss Roga; _Gua Bawah Tanah Saham: Ujung_) = ±15.000",
    "- Kain Beledu x10 (Orc Petarung; _Gua Bawah Tanah Saham_) = ±57.000",
    "",
    "◻️*59-60*",
    "- Spina x4.000",
    "",
    "◻️*60-61*",
    "- Cakar Beruang x2 (Violaccoon; _Padang Darkanon_) = ±90.000",
    "- Sheeting Fabric x20 (Cassy; _Makam Ratu Kuno: Area 2_) = ±6.000",
    "",
    "◻️*61-62*",
    "- Rantai Kukuh x2 (Pendekar Bertopeng; _Tanah Tinggi Pertanian_) = ±6.000",
    "- Kain Polister x20 (Boneka Pengembara; _Kota Hilang_) = ±70.000",
    "",
    "◻️*62-63*",
    "- Sisik Naga Sabana x2 (Naga Sabana Yelb; _Desa Albatif_) = ±5.000",
    "- Kulit Serigala Alien x20 (Serigala Luar; _Gerbang Dunia Lain: Area 1_) = ±450.000",
    "",
    "◻️*63-64*",
    "- Spina x8.000",
    "",
    "◻️*64-65*",
    "- Jubah Sobek x2 (Goovua; _Gurun Akaku: Bukit_) = ±60.000",
    "- Kulit Tupai x20 (Rodentail; _Maia Diela_) = ±130.000",
    "",
    "◻️*65-66*",
    "- Tanduk Elang Zamrud x2 (Elang Zamrud; _Teras Kerikil_) = ±22.000",
    "- Bulu Kambing x20 (Koza; _Jurang Dunkel_) = ±170.000",
    "",
    "◻️*66-67*",
    "- Sayap Naga Senja x2 (Naga Senja; _Benteng Solfini: Atap_) = ±270.000",
    "- Bulu Halus x20 (Little Snow Boar; _Lembah Es Polde_) = ±20.000",
    "",
    "◻️*67-68*",
    "- Spina x16.000",
    "",
    "◻️*68-69*",
    "- Rantai Penyucian x2 (Cerberus; _Mata Air Kelahiran: Puncak_) = ±4.000",
    "- Kain Goyah x20 (Jewel Eye; _Mata Air Kelahiran: Tengah_) = ±130.000",
    "",
    "◻️*69-70*",
    "- Benang Aranea x2 (Aranea; _Taman Sublimasi: Pusat_) = ±120.000",
    "- Benang Laba-Laba Kecil x20 (Aramia; _Taman Sublimasi: Area 2_) = ±120.000",
    "",
    "◻️*70-71*",
    "- Kain Dewi Tiruan x3 (Imitacia; _Istana Gelap: Aula Besar_) = ±22.000",
    "- Kain Apung x10 (Flying Executioner; _Buaian Prajurit_) = ±220.000",
    "- Tapak Lembut x20 (Bunny Summoner; _Sungai Kegelapan_) = ±28.000",
    "",
    "◻️*71-72*",
    "- Surai Hewan Iblis x3 (Memecoleous; _Istana Gelap: Area2_) = ±825.000",
    "- Bantalan Tapak Keras x10 (Manticore; _Istana Gelap: Area1_) = ±100.000",
    "- Bulu Bayangan Hitam x20 (Shadow Fly; _Istana Gelap: Area1_) = ±233.000",
    "",
    "◻️*72-73*",
    "- Spina 32.000",
    "",
    "◻️*73-74*",
    "- Bulu Tapir x3 (Tapir; _Graben Membara: Permukaan_) = ±19.000",
    "- Bulu Kaku x10 (Wooly; _Graben Membara: Permukaan_) = ±100.000",
    "- Minyak Anti Karat x20 (Ornis Demi Machina; _Garis Pertahanan Artileri Otomatis_) = ±217.000",
    "",
    "◻️*74-75*",
    "- Kain Kuno x3 (Proto Leon; _Reruntuhan Singolaire: Lantai 3_) = ±309.000",
    "- Kulit Pohon Lunak x10 (Floral Bee; _Situs Simcracker_) = ±50.000",
    "- Rambut Potum Kotor x20 (Slum Potum; _Klaspe Kumuh_) = ±100.000",
    "",
    "◻️*75-76*",
    "- Tulang Raksasa Merah x3 (Dusk Machina; _Pabrik Demi Machina Kecil: Area 2_) = ±1.067.000",
    "- Mantel Hitam Sobek x10 (Rugos Demi Machina; _Pabrik Demi Machina Kecil: Area 2_) = ±40.000",
    "- Rantai Putus x20 (Machina Penyiksa; _Pabrik Demi Machina Kecil: Area 2_) = ±45.000",
    "",
    "◻️*76-77*",
    "- Sisik Chimera x3 (Mozto Machina; _Pabrik Demi Machina Besar: Bagian Terdalam_) = ±123.000",
    "- Benda Pendar Aneh x10 (Horn Machina; _Pabrik Demi Machina Besar_) = ±120.000",
    "- Tentakel Tangguh x20 (Ledon Machina; _Pabrik Demi Machina Besar_) = ±158.000",
    "",
    "◻️*77-78*",
    "- Spina x64.000",
    "",
    "◻️*78-79*",
    "- Jubah Roh Hutan x3 (Lalvada; _Hutan Monster: Bagian Dalam_) = ±116.000",
    "- Taring Tanaman x10 (Nepenthe; _Hutan Monster_) = ±4.500",
    "- Kain Felt x20 (Naga Boneka; _Mansion Lufenas_) = ±455.000",
    "",
    "◻️*79-80*",
    "- Aloi Lyark x3 (Gwaimol; _Penjara Cuervo: Atap_) = ±190.000",
    "- Baju Penjaga Robek x10 (Sipir Lyark; _Penjara Cuervo: Lantai 2_) = ±51.000",
    "- Kain Lembu x20 (Lyark Spesialis; _Laboratorium Brahe: Area 2_) = ±15.000",
    "",
    "◻️*80-81*",
    "- Kain Bercahaya x4 (Seraph Machina: _Menara Penembus Bumi: Sisi Dalam_) = ±155.000",
    "- Kulit Sintetis Rusak x20 (Lyark Brawler: _Sekitar Alun-Alun Droma_) = ±38.000",
    "- Cawat Pengeksekusi x20 (Volo: _Sekitar Alun-Alun Droma Area 2_) = ±68.000",
    "",
    "◻️*81-82*",
    "- Potongan Baju K. Kecil x4 (Venena: _Istana Ultimea: Takhta_) = ±98.000",
    "- Pecahan Zirah Keras x20 (High Tigris: _Istana Ultimea Gudang Demi Machina_) = ±100.000",
    "- Kulit Ular x20 (Ular Kolam: _Reservoir Copia_) = ±110.000",
    "",
    "◻️*82-83*",
    "- Spina x100.000",
    "",
    "◻️*83-84*",
    "- Kulit Mama Fluck x4 (Mama Fluck: _Gua Pelupa_) = ±36.000",
    "- Daun Besar Colon x20 (Leedle Colon: _Dataran Rokoko_) = ±31.000",
    "- Bulu Garis Vertikal x20 (Rakun Tambun: _Hutan Curonne_) = ±146.000",
    "",
    "◻️*84-85*",
    "- Kain Rohani Mardula x4 (Mardula: _Serambi Dewa Berkah_) = ±180.000",
    "- Kain Berkilau Misterius x20 (Malaikat Gelembung: _Koridor Heresi/Kuil Para Dewa/Serambi Dewa Pembangunan/Serambi Dewa Istimewa_) = ±9.000",
    "- Bulu Kelabu x20 (Haliabubo: _Reruntuhan G. Mithurna: Koridor Atas_) = 107.000",
    "",
    "◻️*85-86*",
    "- Mantel Carbuncle x4 (Carbuncle: _Serambi Dewa Pembangunan_) = ±61.000",
    "- Kain Rajut x20 (Malaikat Gelembung: _Koridor Heresi/Kuil Para Dewa/Serambi Dewa Pembangunan/Serambi Dewa Istimewa_) = ±51.000",
    "- Ekor Beruang Berkantong x20 (Oddy: _Kuil Para Dewa: Area 4/Serambi Dewa Pembangunan_) = ±41.000",
    "",
    "◻️*86-87*",
    "- Bulu Raja Piton x4 (Raja Piton: _Pegunungan Elf: Kuil_) = ±988.000",
    "- Bulu Putih Lebat x20 (Bandot: _Taman Es &Salju_) = ±203.000",
    "- Bulu Abu Kaku x20 (Silveria: _Pegunungan Elf_) = ±51.000",
    "",
    "◻️*87-88*",
    "- Ingot Kuno x4 (Golem Preman: _Kuil Naga Kegelapan: Tengah_) = ±28.000",
    "- Taring Serigala Es x20 (Corloup: _Pegunungan Elf_) = ±300.000",
    "- Kain Gelap x20 (Soul Reaper: _Kuil Naga Kegelapan_) = ±101.000",
    "",
    "◻️*88-89*",
    "- Spina x200.000",
    "",
    "◻️*89-90*",
    "- Taring Tuscog x4 (Tuscog: _Jalan Eryldan: Sekitar Hutan Ein_) = ±350.000",
    "- Sutra Ulat x20 (Tikus Lumut: _Hutan Ein_) = ±278.000",
    "- Bulu Manusia Serigala x20 (Wolfret: _Jalan Eryldan_) = ±185.000",
    "",
    "◻️*90-91*",
    "- Serpihan Kayu Kuzto x5 (Kuzto; _Distrik Labilans: Alun-Alun_) = ±10.000",
    "- Bulu Cerpelai x20 (Satwal; _Distrik Fabriska_) = ±223.000",
    "- Sabuk Pinggang Misterius x30 (Moculus; _Distrik Fractum: Area 1_) = ±270.000",
    "",
    "◻️*91-92*",
    "- Kantong Kristal x5 (Nemopirania; _Distrik Racetacula: Area 1_) = ±309.000",
    "- Ekor Lembut x20 (Alpoca; _Distrik Labilans_) = ±100.000",
    "- Papula Kuat x30 (Toksinaria; _Distrik Racetacula: Area 1_) = ±105.000",
    "",
    "◻️*92-93*",
    "- Sayap Repthon x5 (Repthon; _Zona Riset Delzton: Area Terdalam_) = 1.545.000",
    "- Kancing Polong x20 (Colon Marquis; _Reruntuhan Mansion Lufenas Tua_) = ±108.000",
    "- Kain Perca Jas Panjang x30 (Gulingkar; _Zona Riset Delzton: Area 1_) = ±154.000",
    "",
    "◻️*93-94*",
    "- Rambut Kaisar Siluman x5 (Venena Metacoenubia; _Neo Plastida_) = ±488.000",
    "- Kain Merah Sobek x20 (Potum Bandit Gurun; Gurun Pasir Geist: Area 1) = ±80.000",
    "- Kulit Karatan x30 (Jasman; _Reruntuhan Elban Urban_) = ±34.000",
    "",
    "◻️*94-95*",
    "- Spina x300.000",
    "",
    "◻️*95-96*",
    "- Tulang Pisteus x5 (Pisteus; _Pesisir Ducia: Area Terdalam_) = ±231.000",
    "- Kain Fantom x20 (Flooray; _Dasar Tebing Lunagent_) = ±90.000",
    "- Bulu Berang-Berang Laut x30 (Lutris; _Pesisir Ducia: Area 3_) = ±343.000",
    "",
    "◻️*96-97*",
    "- Sayap Arachnidemon x5 (Arachnidemon; _Lembah Arche: Area Terdalam_) = ±13.000",
    "- Belenggu Logam x20 (Besy; _Lembah Arche_) = ±17.000",
    "- Kulit Ular Aneh x30 (Coofer; _Reruntuhan Kota Rokoko_) = ±34.000",
    "",
    "◻️*97-98*",
    "- Jangat Berlendir x5 (Datuk Nezim; _Lahan Basah Nezim_) = ±257.000",
    "- Kain Enty x20 (Enty; _Rimba Penyihir_) = ±102.000",
    "- Poros Kokoh x30 (Orang2an Sawah Seram; _Rimba Penyihir: Area 2_) = ±465.000",
    "",
    "◻️*98-99*",
    "- Perca Gendam Geni x5 (Hexter; _Rimba Penyihir: Area Terdalam_) = ±222.000",
    "- Piring Kappa x20 (Kappadon; _Lahan Basah Nezim_) = ±139.000",
    "- Bulu Gagak x30 (Orang2an Sawah Seram; _Rimba Penyihir: Area 2_) = ±62.000",
    "",
    "◻️*99-100*",
    "- Inti Latebra Menggeliat x5 (Trocostida; _Nov Diela: Area 1_) = ±2.150.000",
    "- Cairan Lekat x20 (Juvestida; _Nov Diela: Area 1_) = ±9.000",
    "- Kulit Pelik x30 (Mata Jahat; _Padang Morga: Area 1_) = ±102.000",
    "",
    "Total biaya: 17.851.500 + 727.000 = 18.578.500",
    "",
    divider,
  ].join("\n"),
  "#6": [
    divider,
    "Leveling Char By Hsans",
    divider,
    "",
    "Leveling Char Sambil MQ",
    "",
    "- Tanpa Adv Book",
    "- Exp tambahan dari MQ",
    "- Spot Farming",
    "- Nostalgia jadi babu",
    "- Langkah-langkah di buat untuk menyesuaikan Lv, Lv Boss, dan exp dari Quest",
    "",
    '"Membuat Char baru > mulai dari awal untuk mode MQ"',
    "",
    "• MQ dari Bab 1 > Gunung Nisel",
    "",
    "• 1 > 37 : Shell Mask > Gunung Nisel",
    "",
    "• MQ > Brutal Dragon Decel > Gunung Nisel",
    "",
    "• 37 > 57 : Bone Dragon > Makam Ratu",
    "",
    "• MQ > Lereng Merapi",
    "",
    "• 57 > 62 : Flare Volg Hard > Lereng Merapi",
    "",
    "• 62 > 74 : Flare Volg NM > Lereng Merapi",
    "",
    "• MQ > Gurun Akuku",
    "",
    "• 74 > 87 : Metal Stinger > Gurun Akuku",
    "",
    "• MQ > Elscaro",
    "",
    "• 87 > 96 : Flare Volg Ulti > Lereng Merapi",
    "",
    "• 96 > 104 : Don Yeti > Lembah Es Polde (atau >113 dan skip Masked)",
    "",
    "• 104 > 114 : Masked Warior Ulti > Lahan Pertanian",
    "",
    "• MQ > Mata Air Kelahiran",
    "",
    "• 114 > 124 : Cerberus NM > Mata Air Kelahiran",
    "",
    "• MQ > Sungai Kegelapan",
    "",
    "• 124 > 133 : Lapin The Necromancer > Sungai Kegelapan",
    "",
    '• MQ > Bab 6 "Duo Technista"',
    "",
    "• 134 > 144 : Cerberus Ulti > Mata Air Kelahiran",
    "",
    "• MQ > Pabrik Demi Machina Besar",
    "",
    "• 144 > 150 : Odelon Machina (Bisa di skip) > Pabrik Demi Machina Besar",
    "",
    "• MQ > Hutan Monster",
    "",
    "• 144 > 157 : Super Death Mushroom > Hutan Monster",
    "",
    "• MQ > Mansion Lufenas",
    "",
    "• 157 > 162 : Commander Golem > Mansion Lufenas",
    "",
    "• MQ > Istana Ultimea : Tahta",
    "",
    "• 162 > 179 : Venena NM > Istana Ultimea : Tahta",
    "",
    "• 179 > 182 : Altoblepas > Dataran Rakoko",
    "",
    "• 182 > 199 : Venena Ulti > Istana Ultimea : Tahta",
    "",
    "• MQ > Kuil Naga Kegelapan",
    "",
    "• 199 > 210 : Finstern The Dark Dragon > Kuil Naga Kegelapan",
    "",
    "• MQ > Distrik Labilans",
    "",
    "• 210 > 227 : Kuzto Ulti > Distrik Labilan",
    "",
    "• 227 > 230 : Mini Boss Espectro > Lembah Arche",
    "",
    "• MQ > Lembah Arche",
    "",
    "• 230 > 241 : Arachnidemon Ulti > Lembah Arche",
    "",
    "• MQ > Hutan Lindung",
    "",
    "• 243 > 250 : Ferzen The Rock Dragon > Hutan Lindung",
    "",
    "• MQ > Zona Kemudi",
    "",
    "• 255 > 265 : Trickster Dragon Mimyugon NM > Zona Kemudi",
    "",
    "• MQ > Aquacity",
    "",
    "• 270 > 287 : Trickster Dragon Mimyugon Ulti > Zona Kemudi",
    "",
    "• MQ > Mulgoon > Dataran Menabra",
    "",
    "• 291 > 303 : Mulgoon NM > Dataran Menabra / 291 > 296 : Capo Profundo > Kawasan Terlantar",
    "",
    "• 296 > 309 : Wiltileaf > Reruntuhan Desa Eumano",
    "",
    "• 309 > 323 : Mulgoon Ulti > Dataran Menabra",
    "",
    "*Note :*",
    "",
    "> Tingkat kesulitan Tinggi (harap minta bantuan teman / guild)",
    "> Exp sistem > Selisih lv > Exp modifier",
    "",
    "0 > 1100%",
    "1 > 1000%",
    "2 > 900%",
    "3 > 700%",
    "4 > 300%",
    "5-9 > 100%",
    "10-19 > -1%/lv.",
    "",
    "Sumber : Coryn Club",
    "V 0.1.3",
    "",
    divider,
  ].join("\n"),
  "#7": [
    divider,
    "Tips Refine",
    divider,
    "",
    "1) Spam Refine menggunakan bijih mithril dengan Char Full Luk sampai +S",
    "",
    "2) Refine terstruktur",
    "- 1) Refine menggunakan bijih mithril dengan Char Full Luk sampai pity 1,5k",
    "- 2) Jika belum +S, lanjutkan refine dengan Char BS Full Tec menggunakan bijih mithril sampai +C (opsional menggunakan Orichalcum + Andeg dari +E sampai +B)",
    "- 3) Lanjutkan refine dengan Char Full Luk menggunakan Bijih Mithril sampai +S (opsional menggunakan Andeg dari +A sampai +S)",
    "",
    "*NB:*",
    "- Refine adalah proses menempa perlengkapan hingga +S",
    "- Refine digunakan untuk memperkuat perlengkapan",
    "- 150pt = +1% Success Rate",
    "",
    "By: Master-A",
    "",
    divider,
  ].join("\n"),
  "#8": [
    divider,
    "STAT BLACKSMITH",
    divider,
    "",
    "Stat Karakter Lvl Cap 320",
    "- Armor :",
    "  Vit 510 Tec 255",
    "- Bow/Bwg/Ohs :",
    "  Dex 510 Str 312",
    "- Ths/Ohs/Bow :",
    "  Str 510 Dex 312",
    "- Knuk/Ktn :",
    "  Agi 510 Dex 312",
    "- Ktn/Bwg :",
    "  Dex 510 Agi 312",
    "- Staff :",
    "  Int 510 Str 200 Tec 113",
    "- Hb/Ths :",
    "  Str 510 Agi 270 Tec 43",
    "- Md/Staff :",
    "  Int 510 Agi 140 Tec 173",
    "",
    "Equipment (All xtal Dex 8 + 7)",
    "- Weapon",
    "  Dex10%Str10%Dex30Str20+",
    "- Armor",
    "  Dex10%Str10%Dex30Str20+",
    "- Add",
    "  Anniv hat/ribbon; Add 100k sub all stat 10%",
    "- Ring",
    "  Dex talisman VI",
    "",
    "*Notes :*",
    "1) Jika lvl cap naik maka tinggal naikan Secondary Stat (bukan Tec)",
    "Contoh:",
    "Bs hb/ths dan naik cap, maka naikan stat Agi",
    "",
    "2) Jika ingin Sr lebih tinggi tanpa equipment, silahkan kurangi Secondary Stat lalu tambahkan TEC",
    "Contoh:",
    "Bs hb/ths stat Str 510 Agi 270 Tec 43.",
    "Jika tidak mau memakai equip maka turunkan Agi dengan kelipatan 20 (karena hb berkelipatan 20) lalu pindahkan ke Tec.",
    "Misal menjadi Str 510 Agi 250 Tec 63",
    "",
    divider,
  ].join("\n"),
  "#9": [
    divider,
    "LEVELING PROF/KEMAHIRAN TEMPA",
    divider,
    "",
    "*Char No Dex Tec 43-113 / Dex 312*",
    "Prof lvl 0-10",
    "- Adventurer Garb",
    "",
    "Prof lvl 10-50",
    "- Hard Knuckle",
    "",
    "Prof lvl 50-90",
    "- Indigo Sword",
    "",
    "Prof lvl 90-120",
    "- Diomedea Suit (bisa skip kalau diff sdh mencapai 140)",
    "",
    "Prof lvl 90-140",
    "- Lightning Bolt Spear",
    "",
    "Prof lvl 140-170",
    "- Red Spider Lily",
    "- Jade Lance",
    "",
    "Prof lvl 170-200",
    "- Arachnid Sword",
    "- Arachnid Claws",
    "",
    "Prof lvl 200-220",
    "- Rock Dragon Bracers - 210",
    "- Vermio Bow",
    "- Vegitos Bowgun",
    "- Sharp Baghnaks",
    "",
    "Prof lvl 220-260",
    "- Starry Robe",
    "",
    "*Char Tec 255/Dex 510*",
    "Prof lvl 0-10",
    "- Adventurer Garb",
    "",
    "Prof lvl 10-140",
    "- Lightning Bolt Spear",
    "",
    "Prof lvl 140-260",
    "- Starry Robe",
    "",
    "Untuk prof lvl 260+ cari aja bahan yg paling murah antara :",
    "- Abyssal Katana/Greatsword - 280",
    "- Humida Barrel/Wings - 280",
    "- Gloomy Flower Staff - 280",
    "- Mulgoon Robe - 280",
    "- Anguish Sword/Knuckle - 280",
    "- Raden Pearl Knuck/Staff - 290",
    "- Seedling Bow/Md - 300",
    "",
    divider,
  ].join("\n"),
  "#10": [
    divider,
    "POTENSIAL EQUIPMENT",
    divider,
    "",
    "STR",
    "- Setiap 10 stat STR menambah 1 potential untuk Pedang 2 Tangan",
    "- Setiap 20 stat STR menambah 1 potential untuk Pedang 1 Tangan, Busur, dan Tombak",
    "",
    "INT",
    "- Setiap 10 stat INT menambah 1 potential untuk Tongkat",
    "- Setiap 20 stat INT menambah 1 potential untuk Sayap Sihir",
    "",
    "VIT",
    "- Setiap 10 stat VIT menambah 1 potential untuk Armor",
    "",
    "AGI",
    "- Setiap 10 stat AGI menambah 1 potential untuk Sarung Tinju",
    "- Setiap 20 stat AGI menambah 1 potential untuk Tombak, Sayap Sihir, dan Katana",
    "",
    "DEX",
    "- Setiap 10 stat DEX menambah 1 potential untuk Bowgun",
    "- Setiap 20 stat DEX menambah 1 potential untuk Pedang 1 Tangan, Busur, dan Katana",
    "",
    "Sumber: Xixy bot @2023",
    "",
    divider,
  ].join("\n"),
  "#11": [
    divider,
    "LEVELING PROF/KEMAHIRAN PADU",
    divider,
    "",
    "Char Full Tec",
    "Skill Padu Item Level 10",
    "Siapkan: Madu Enak 6-10 stk",
    "",
    "*Simple:*",
    "1) Lvl 1-15 craft save point",
    "2) Madu Enak 1 stak > Nektar > Revita III",
    "3) Madu Enak 1 stak > Nektar > Revita IV",
    "4) Madu Enak 1 stak > Nektar > Revita V",
    "5) Madu Enak 1 stak > Nektar > Sirup Nektar > Revita VII",
    "6) Madu Enak 1 stak > Nektar > Sirup Nektar > Revita VII",
    "7) Madu Enak 1 stak > Nektar > Sirup Nektar > Revita VII",
    "",
    "*Detail:*",
    "Lvl 1-15",
    "Save point",
    "Bahan: Mats Mana",
    "",
    "Lvl 15-28",
    "Nektar",
    "Bahan: Madu Enak 1 stak",
    "",
    "Lvl 28-40",
    "Revita III",
    "Bahan: Nektar",
    "",
    "Lvl 40-53",
    "Nektar",
    "Bahan: Madu Enak 1 stak",
    "",
    "Lvl 53-65",
    "Revita IV",
    "Bahan: Nektar",
    "",
    "Lvl 65-78",
    "Nektar",
    "Bahan: Madu Enak 1 stak",
    "",
    "Lvl 78-85",
    "Revita V",
    "Bahan: Nektar",
    "",
    "Lvl 85-98",
    "Nektar",
    "Bahan: Madu Enak 1 stak",
    "",
    "Lvl 98-104",
    "Sirup Nektar",
    "Bahan: Nektar",
    "",
    "Lvl 104-107",
    "Revita VII",
    "Bahan: Sirup Nektar",
    "",
    "Lvl 107-120",
    "Nektar",
    "Bahan: Madu Enak 1 stak",
    "",
    "Lvl 120-126",
    "Sirup Nektar",
    "Bahan: Nektar",
    "",
    "Lvl 126-129",
    "Revita VII",
    "Bahan: Sirup Nektar",
    "",
    "Lvl 129-142",
    "Nektar",
    "Bahan: Madu Enak 1 stak",
    "",
    "Lvl 142-148",
    "Sirup Nektar",
    "Bahan: Nektar",
    "",
    "Lvl 148-150",
    "Revita VII",
    "Bahan: Sirup Nektar",
    "",
    "By: Master-A",
    "",
    divider,
  ].join("\n"),
  "#12": [
    divider,
    "Xtall Master",
    divider,
    "",
    "Peminjaman Up Xtall: Lapor di Discord.",
    "Waktu Peminjaman: Menyesuaikan waktu luang Master-A",
    "",
    "Xtall Weap",
    "- Megiston Sang Juara - VII -> (Megiston Sang Juara VIII)",
    "- Armasit -> (Kadal Bunga)",
    "- Zahhak Machina - Penyihir Besi Bercakar -> (Ratu Rosemee)",
    "- Ganglef -> (Kepiting Bulan Besar)",
    "- Dango Iblis -> (Fubbit)",
    "- Armasit -> (Diark)",
    "- Putri Natal Berbaju Hitam -> (Gusti Ilusi Melodi)",
    "- Zega - IX -> (Zega X)",
    "- Metasrigala - Cakar Kucing Kissatpam -> (Neo Magi Filecia)",
    "- Zolban - Repthon - Naga Trompet Reguita -> (Doreminador)",
    "- Pedang Neo Maton -> (Pedrio)",
    "- Mbah Dukun Usasama -> (Mbah Dukun Usasama II)",
    "- Potum Pahlawan - III -> (Potum Pahlawan IV)",
    "- Pomie Chan - II -> (Pomie Chan III)",
    "---",
    "- Ksatria Buruk Dusta - Gwaimol - Hexter - Don Profundo -> (Doy)",
    "- Ganglef - Machina Tiran - Vulture - Mimyugon -> (Bakuzan)",
    "- Golem Pillar - Machina Ultima - Vlam si Naga Api -> (Supreme Evil Crystal Beast)",
    "- Iblis Kristal Jahanam - Shampy - Irestida -> (Vatudo)",
    "- Pedang Sihir Iblis -> (Kristal Berlumur Darah)",
    "- Imitacia - Finstern - Oculasignio -> (Menti)",
    "- Imitator - Mardula - Velum -> (Deformis)",
    "---",
    "- Gerbang Iblis > Mozto Machina > Pisteus - Naga Jahat Fazzino -> (Rondine)",
    "- Arbogazella -> (Doridodi)",
    "- Zahhak Machina - Penyihir Besi Bercakar -> (Naga Meraung Bovinari)",
    "- Zolban - Repthon - Naga Trompet Reguita -> (Goudvis)",
    "- Golem Galian - Builder Golem -> (Meduso)",
    "- Dukun Lapin -> (Momok Gelembung)",
    "",
    "Xtall Armor",
    "- Pilz Erosi -> (Tulin Max)",
    "- Gopherga -> (Yuveria)",
    "- Usakichi - Usami -> (Usamochi)",
    "- Sibylares -> (Bemoz)",
    "- Noeliel - Noeliel si Patung Es Suci - Kucing Yule -> (Gegner)",
    "- Sosok Jahat - Velly Hitam -> (Glocke)",
    "- Kruztor -> (Kruztor II)",
    "- Cerabes - Mimesia - Sakura Merah Jelita - Baavgai -> (Bajinja / Ninja Persik Hitam)",
    "- Permaisuri Besi -> (Merzehal)",
    "- Dr. Leonardo -> (Dr. Leonardo II)",
    "- DX Fighter -> (DX Fighter II)",
    "---",
    "- Arachnidemon - Zapo -> (Puiet)",
    "- Cerberus - Pyxtica - Gemma -> (Meteora)",
    "- Nemopirania -> (Skelerow)",
    "---",
    "- Pilz Erosi - Filrocas -> (Mari)",
    "- Bos Roga - Iconos - Ornlarf - Roga Safir - Ferzen -> (Walican)",
    "- Ifrid - Mama Fluck - Gordel -> (Biskyva)",
    "- Forestia -> (Glaucius)",
    "- Quassar Jahanam -> (Mata Jahanam)",
    "- Tortuga - Daddy Finpen - Capo Profundo -> (Landak Penggali Gelap)",
    "- Golem Preman -> (Naga Langkisau)",
    "- Colon Komandan -> (Goleps)",
    "- Elang Zamrud - Jamur Super Mampus -> (Dandolion)",
    "",
    "Xtall Add",
    "- Naga Sabana Yelb - Roda Kelana -> (Roda Kelana Neo)",
    "- Adaro -> (Monster Dasar Laut)",
    "- Tengkorak Emas - Solopy -> (Potum Hiu)",
    "- Pumpking - Jeila - Zoe - Zarth - Neewollah -> (Eripmav)",
    "- Naga Senja - Baphomela -> (Bayangan Biru Tafakur)",
    "- Potum Surya -> (Potum Bintang Top)",
    "- Biskuit Buatan Tangan - Alfenix -> (Zucotto Goblin)",
    "- Eidenliebe -> (Garnache)",
    "- Candela - II -> (Amargon)",
    "- Chocolate Ooze & II -> (Soldner)",
    "- Iconos Emas - Kodok Riang - Gem Mas -> (Goldian)",
    "- Gespenst II -> (Stellar Ooze)",
    "- Ratu Kuno -> (Ratu Kuno II)",
    "- Raja Kerbau - Paduka Raja Kerbau -> (Paduka Raja Kerbau II)",
    "- Raja Kerbau - (Pillow Kitagawa) -> (Pillow Kitagawa II)",
    "- Jibril - II -> (Jibril III)",
    "- Ayah Yashiro Azuki -> (Raja Kegelapan)",
    "- Narumi Hina -> (Ibu Yashiro Azuki II)",
    "---",
    "- Naga Sabana Yelb - Roda Kelana -> (Gordo)",
    "- Dusk Machina -> (Trocostida)",
    "- Zyvio -> (Gula)",
    "- Altoblepas -> (Jiva)",
    "---",
    "- Grylle - Fantica -> (Obsia)",
    "- Celeng Raksasa -> (Mega Alpoca)",
    "- Warmonger - Proto Leon - Raja Piton -> (Naga Membara Igneus)",
    "- Seltirio -> (Tardigrademon)",
    "- Kapten Karatan -> (Exdocus)",
    "",
    "Xtall Ring",
    "- Kristal Jahat -> (Kristal Misterius)",
    "- Violangkara -> (Violangkara G)",
    "- Zeagrysta -> (Monster Kristal Abisal)",
    "- Seele Zauga -> (Seele Zauga II)",
    "- Dark Mushroom -> (Teertocrit)",
    "- Viscum - Deniala - Amalgam - Crysmort -> (Breeta)",
    "- Kristal Jahat - Tapir - Patissia -> (Sicanokami)",
    "- Volgagon -> (Etoise)",
    "- Potumotter -> (Potumotter)",
    "---",
    "- Ooze - Lalvada -> (Dominaredor)",
    "- Venena - II -> (Humida)",
    "- Bexiz - Zelbuse -> (Naga Milisi Turba)",
    "---",
    "- Tentara Batu -> (Memecoleous)",
    "- Baron Bling-Bling -> (Roh Orang Mati)",
    "- Violaccoon - Ketua Bandit Gurun -> (Arpoon)",
    "",
    "Xtall Umum",
    "- Bos Colon -> (Kijimu Agung)",
    "- Goblin Bos -> (Colon Bos)",
    "- Lobalawar - Melancia -> (Chiromina)",
    "- Lynx Mithurna -> (Kuffania)",
    "- Shawle -> (Dutannen)",
    "- Nurethoth -> (Nuthoreth)",
    "- Potum Raja - Potum Platina -> (Potum Kue)",
    "- Gerumi -> (Gerumi Kuat)",
    "---",
    "- Metal Stinger - Kapten Lyark Spesialis - Ageladanios -> (Wiltileaf)",
    "- Odelon Machina - Pret -> (Lilicarolla)",
    "- Gravicep - Naga Abu Merah Rudis -> (Gioco)",
    "- Minotaur - Rhinosaurus -> (Wild Beast Lixi)",
    "- Naga Beringas Decel - York - Tuscog - Bayangan Hitam -> (Torexesa)",
    "- Nurethoth - Guignol - Golem Satpam -> (Piscruva)",
    "- Coryn Besar - Seraph Machina -> (Limacina)",
    "- Flare Volg -> (Charugon)",
    "---",
    "- Gespenst - Salamander -> (Bullamius)",
    "- Ksatriaja - Volotur -> (Brassozard)",
    "- Crimsosh -> (Amoeba Machina)",
    "- Aranea - Blazingur -> (Brahma)",
    "- Bos Petapa Kadal -> (Orictoceras)",
    "- Caspy -> (Vevela)",
    "",
    divider,
  ].join("\n"),
  "#13": [
    divider,
    "List Xtall Event",
    divider,
    "",
    "Xtall Event Anniv",
    "1. Sang Juara Megiston - VIII",
    "2. Roda Kelana Neo",
    "3. Kadal Bunga",
    "4. Kristal Misterius",
    "5. Violangkara G",
    "6. Ratu Rosemee",
    "7. Tulin Max",
    "8. Kijimu Agung",
    "9. Colon Boss",
    "10. Potum Ultra",
    "---",
    "Xtall Event Summer",
    "1. Titeres",
    "2. Gopherga > Yuveria",
    "3. Adaro > Monster Dasar Laut",
    "4. Kapten Amiya",
    "5. Gurita Raksasa",
    "6. Semangat Musim Panas",
    "7. Fallburrow",
    "8. Zegrysta > Monster Kristal Abisal",
    "9. Stormun",
    "10. Potum Hiu",
    "---",
    "Xtall Event Otsukimi",
    "1. Usakichi > Usami > Usamochi",
    "2. Kepiting Bulan",
    "3. Dango Iblis > Fubbit",
    "---",
    "Xtall Event Persimmon Coryn",
    "1. Auvio",
    "2. Auberkasa",
    "---",
    "Xtall Event Halloween",
    "1. Pumpking > Jeila > Zoe > Zarth > Neewollah > Eripmav",
    "2. Penyihir Naga",
    "3. Gagak Penyihir Hebat",
    "4. Badut Tukang Sandiwara",
    "5. Phantom Wisp",
    "6. Tikus Kecil Ajaib",
    "7. Serigala Merah Mata Satu",
    "8. Teertocrit",
    "9. Sibylares > Bemoz",
    "10. Syaman Hitam Hutan Hantu",
    "11. Melancia > Chiromina",
    "12. Sinar Rembulan Purba",
    "13. Kuffania",
    "14. Jejak Bayang Nan Jauh",
    "15. Olobaid",
    "16. Bayangan Iblis Mayat Ksatria",
    "---",
    "Xtall Event Natal",
    "1. Naga Senja > Baphomela > Bayangan Biru Tafakur > Shawle Terlarang",
    "2. Noeliel > Noeliel si Patung Es Suci > Kucing Yule > Gegner",
    "3. Shawle > Dutannen",
    "4. Sosok Jahat > Velly Hitam > Glocke",
    "5. Putri Natal Berbaju Hitam > Gusti Ilusi Melodi",
    "6. Iluminator",
    "7. Bayangan Jeritan",
    "8. Diark",
    "9. Granpromus",
    "10. Potum Bintang Top",
    "---",
    "Xtall Event Megiston Road",
    "1. Zega - IX",
    "2. Felien > Neo Lefina Jahat",
    "3. Metasrigala > Cakar Kucing Kissatpam > Neo Magi Filecia",
    "4. Kapten Sihir & si B",
    "5. Doreminador",
    "6. Seele Zauga II",
    "7. Dango Sakura",
    "8. Sakura Musim Semi",
    "---",
    "Xtall Event Otoshidama",
    "1. Grand Pojo (Ayam)",
    "2. Perro (Anjing)",
    "3. Kohaku Lil Boar (Babi)",
    "4. Omochi (Tikus)",
    "5. Bovinio (Kerbau)",
    "6. Purro (Macan)",
    "7. Lunadore (Kelinci)",
    "8. Dratone (Naga)",
    "9. Ophy (Ular)",
    "10. Ponier (Kuda)",
    "---",
    "Xtall Event Valentine",
    "1. Chocolate Ooze - II > Soldner",
    "2. Eidenliebe > Garnache > Erkuch",
    "3. Jeandoux",
    "4. Mieli",
    "5. Goblin Makelar > Velcaroy",
    "6. Amargon",
    "7. Sicanokami",
    "8. Pelulu Raksasa",
    "---",
    "Xtall Event White Day",
    "1. Candela - II",
    "2. Biskuit Buatan Tangan > Alfenix > Zucotto Goblin",
    "3. Mercy",
    "4. Kruztor - II",
    "5. Lefina Jahat > Sanburmon",
    "6. Magi Filecia",
    "7. Bangrudom",
    "---",
    "Xtall Event Hanami",
    "1. Viscum > Deniala > Amalgam > Crysmort > Breeta",
    "2. Marchitar",
    "3. Super Night Mushroom",
    "4. Cerabes > Mimesia > Sakura Merah Jelita > Baavgai > Bajinja / Ninja Persik Hitam",
    "5. Oni Api Gaib",
    "---",
    "Xtall Event Golden Week",
    "1. Iconos Emas > Kodok Riang > Gem Mas > Goldian > Auporter",
    "---",
    "Xtall Event Hdb",
    "1. Raja Kerbau > Paduka Raja Kerbau - II",
    "2. Raja Kerbau > Pillow Kitagawa - II",
    "3. P. Ava",
    "4. Ratu Kuno II",
    "5. Permaisuri Besi > Merzehal",
    "6. Gespenst II > Stellar Ooze",
    "7. Pedang Neo Maton > Pedrio",
    "8. Patissia",
    "9. Volgagon > Etoise",
    "10. Altadar",
    "11. Castilia",
    "12. Mbah Dukun Usasama - II",
    "13. Stellar Ooze II",
    "---",
    "Xtall Event Download",
    "1. Potum Pahlawan - IV",
    "2. Potum Platina > Potum Kue",
    "3. Pomie-chan - III",
    "4. Doktor Pom Pom",
    "5. Potumotter - III",
    "---",
    "Xtall Collab",
    "1. Gerumi > Gerumi Kuat",
    "2. Yashiro Azuki",
    "3. Ibu Yashiro Azuki",
    "4. Ayah Yashiro Azuki > Raja Kegelapan",
    "5. Narumi Hina > Ibu Yashiro Azuki II",
    "6. Dr. Leonardo - II",
    "7. Dx Fighter - II",
    "8. Jibril - III",
    "9. Dewa Mesin Maple",
    "",
    divider,
  ].join("\n"),
  "#14": [
    divider,
    "Info Seputar Pet",
    divider,
    "",
    "Masuk gc pet aja",
    "",
    "*Tips build pet singkat:*",
    "1. Cari pet sampai dapet weapon/type/sifat yg pas.",
    "2. Keluarin kandang.",
    "3. Kasih makan 3k.",
    "4. Latih skill, misal belok buang, misal dapet tapi lvl 3 kebawah buang.",
    "5. Ulangi dari langkah 1 jika blm dapet skill lv4/lv5. Kalau dah dapet lanjut.",
    "6. Kasih makan lagi tiap 4 jam sampai dapet bonus latih 50%.",
    "*No 6 dengan no 4 boleh dibalik*",
    "7. Lanjut latih potensinya (mode Hard) sesuai job petnya sampai 100% terlatih.",
    "8. Lanjut leveling level dan leveling skill sampai max.",
    "9. Padu dengan pet lain dengan syarat yang sama seperti no 1-8.",
    "10. Kalau butuh lock dye, padu lagi sampai sesuai target yang diinginkan.",
    "11. Lanjut latih skill, potensi, dan leveling sampai cap.",
    "12. Done, pet anda sudah jadi.",
    "",
    "Sumber: Pet Toram Online Indo",
    "",
    divider,
  ].join("\n"),
  "#15": [
    divider,
    "Tips Raid",
    divider,
    "",
    "*Growler Bison (Raid Biru)*",
    "Posisi bagus: samping bossnya",
    "- Kalau tank mulai dengan stun, jangan kelamaan deket-deket soalnya ada shockwave",
    '- Pakai regis "Pyrexia" kalau kena hit',
    "",
    "Pattern berbahaya:",
    "1) Boss lari dari tank",
    "2) Boss nembak bola ke player dengan jarak paling jauh",
    "3) AoE gede",
    "",
    "*Demonic Skull Dragon (Raid Ungu)*",
    "Posisi bagus: barat lautnya boss atau belakang",
    "",
    "Pattern berbahaya:",
    "1) 3 AoE biru lurus atau nabok pakai 2 tangan, yang mana pattern 3 hiu melingkar. Kalau gak di-interrupt (flinch, tumble, stun), kepalanya bakal nengok ke lutut kiri 1 detik sebelum hiunya keluar",
    "2) Boss lari dari tank",
    "3) AoE merah donat (kalau bisa interrupt sih)",
    "",
    "*Roaring Thruma (Raid Hijau)*",
    "Posisi bagus: belakang",
    "",
    "Pattern berbahaya:",
    "1) Boss lari dari tank",
    "2) Animasi pedang ke serong kanan serong kiri, yang ngeluarin 5 hiu x 2",
    "3) Nancapin 1 pedang ke tanah dan nembak bola (300k+ fatal attack ke tank)",
    "4) AoE merah lari ke arah tank, yang mana bakal ngeluarin hiu gede ke depannya",
    "",
    "*Mighty Chimera (Raid Kuning)*",
    "Posisi bagus: di samping atau di belakang (lebih aman kalau berjarak 0 meter)",
    "",
    "Pattern berbahaya:",
    "1) AoE biru 1 arena, ngasih ailment petrify / kaku",
    "2) Mundur dari tank, yang mana ngeluarin banyak hiu lurus dan serong hanya jika banyak yang berada dalam jangkauan",
    "3) AoE merah di samping kalau ada banyak yang di sana (kalau 0 meter tetap aman)",
    "4) AoE biru kecil yang ngeluarin badai, kalau udah berkali-kali lawannya",
    "",
    "*Blazing Celdyte (Raid Merah)*",
    "Raid boss Api",
    "- Posisi paling aman ada di sebelah kanan arah boss (di sebelah kiri arah player)",
    "- Jika terlalu banyak spam skill boss otomatis akan mengeluarkan meteor mini tanpa targeting aoe",
    "- Boss tidak bisa di stun tapi masih bisa di gedik atau pakai skill impact",
    "- Setelah ngeluarin aoe biru dari sebelah kiri boss jangan di dekatnya karena boss pasti memberikan damage di sekitar menggunakan ekor",
    '- Ada circle biru dari "Fireguard Schnee" untuk menjadi tempat aman saat raid. Jika keluar circle, maka akan kena damage per detik dengan ailment Terbakar. Jangan bunuh Fireguard Schnee atau semua player akan kena damage tersebut sebanyak 10 hit selama 10 detik',
    "- Hati-hati dengan pattern hiu lurus ke segala arah karena nanti bossnya nyerang tanpa aoe. Cara menghindarnya tinggal menjauh",
    "",
    divider,
  ].join("\n"),
  "#16": [
    divider,
    "EFEK STATUS POIN",
    divider,
    "",
    "Pengaruh Status Karakter",
    "",
    "Tongkat",
    "STR : ATK+3 , Stab+0.05",
    "INT : ATK+1 , MATK+4 , ASPD+0.2",
    "AGI : ASPD+1.8",
    "DEX : MATK+1 , CSPD+2.94 , Acc+1",
    "",
    "Busur",
    "STR : ATK+1 , Stab+0.05",
    "INT : MATK+3",
    "AGI : ASPD+3.1",
    "DEX : ATK+3 , MATK+1 , Stab+0.05 , ASPD+0.2 , CSPD+2.94 , Acc+1",
    "",
    "Katana",
    "STR : ATK+1.5 , Stab+0.075 , Aspd+0.3",
    "INT : MATK+2",
    "AGI : MATK+1 , ASPD+3.9",
    "DEX : ATK+2.5 , MATK+1 , Stab+0.025 , CSPD+2.94 , Acc+1",
    "",
    "Sayap Sihir",
    "INT : ATK+2 , MATK+4 , ASPD+0.2",
    "AGI : ATK+2 , ASPD+4.6",
    "DEX : MATK+1 , Stab+0.1 , CSPD+2.94 , Acc+1",
    "",
    "Pedang 1 Tangan",
    "STR : ATK+2 , Stab+0.025 , ASPD+0.2",
    "INT : MATK+3",
    "AGI : ASPD+4.2",
    "DEX : ATK+2 , MATK+1 , Stab+0.075 , CSPD+2.94 , Acc+1",
    "",
    "Pedang 2 Tangan",
    "STR : ATK+3 , ASPD+0.2",
    "INT : MATK+3",
    "AGI : ASPD+2.1",
    "DEX : ATK+1 , MATK+1 , Stab+0.1 , CSPD+2.94 , Acc+1",
    "",
    "Pedang Ganda",
    "STR : ATK+1 , SubATK+1 , Stab+0.025 , SubStab+0.06 , Aspd+0.2",
    "INT : MATK+3",
    "AGI : ATK+1 , SubATK+3 , SubStab+0.04 , Aspd+4.2",
    "DEX : ATK+2 , MATK+1 , Stab+0.075 , CSPD+2.94 , Acc+1",
    "",
    "Bowgun",
    "STR : Stab+0.05",
    "INT : MATK+3",
    "AGI : ASPD+2.2",
    "DEX : ATK+4 , MATK+1 , ASPD+0.2 , CSPD+2.94 , Acc+1",
    "",
    "Sarung Tinju",
    "STR : ASPD+0.1",
    "INT : MATK+4",
    "AGI : ATK+2 , ASPD+4.6",
    "DEX : ATK+0.5 , MATK+1 , Stab+0.025 , ASPD+0.1 , CSPD+2.94 , Acc+1",
    "",
    "Tombak",
    "STR : ATK+2.5 , Stab+0.05 , Aspd+0.2",
    "INT : MATK+2",
    "AGI : ATK+1.5 , MATK+1 , Aspd+3.5",
    "DEX : MATK+1 , Stab+0.05 , CSPD+2.94 , Acc+1",
    "",
    "Tangan Kosong / tanpa Senjata",
    "STR : ATK+1",
    "INT : MATK+3",
    "AGI : ASPD+9.6",
    "DEX : MATK+1 , CSPD+2.94 , Acc+1",
    "",
    "Semua Job/Senjata",
    "STR : jika Str > Agi = str/5 , jika Agi > str = Agi+str/10",
    "INT : MP+0.1 , MDEF+1xn > (nilai n jika Arm diperberat=2, Arm diperingan=0.25)",
    "VIT : Max HP x 0.33 x Lvchar , DEF+1xn > (nilai n jika Arm diperberat=2, Arm diperingan=0.25)",
    "AGI : if Agi > str = 0.1 cd , CSPD+1.16 , Flee+1xn (nilai n jika Arm diperberat=0.75 , Arm Diperingan=1.75)",
    "CRT : cr+0.29412 (3.4 CRT=1cr , 255CRT=75cr)",
    "LUCK: Droprate+0.1% , Mengurangi degradasi 95% dengan Anti degradasi",
    "TEC : MP+1",
    "MTL : Ailment+0.29412 (3.4 MTL=1 Ailment , 255MTL=75 Ailment)",
    "",
    "Sumber: Xixy bot @2023",
    "",
    divider,
  ].join("\n"),
  "#17": [
    divider,
    "AILMENT & INTERRUPT",
    divider,
    "",
    "1) Flinch (Bergidik)",
    "- Ke Boss atau Mobs",
    "  Interupsi aksinya sejenak (Singkat)",
    "- Ke Pemain",
    "  Interupsi tindakan mereka sejenak (Singkat)",
    "",
    "2) Tumble (Jatuh)",
    "- Ke Boss atau Mobs",
    "  Interupsi aksinya sejenak (Sedang)",
    "- Ke Pemain",
    "  Interupsi tindakan mereka sejenak (Sedang)",
    "",
    "3) Stun (Pingsan)",
    "- Ke Boss atau Mobs",
    "  Interupsi aksinya sejenak (Lama)",
    "- Ke Pemain",
    "  Interupsi tindakan mereka sejenak (Lama)",
    "",
    "4) Knock Back (Terpelanting)",
    "- Ke Boss atau Mobs",
    "  Interupsi aksinya sejenak, terpelanting ke belakang untuk beberapa jarak",
    "- Ke Pemain",
    "  Interupsi aksinya sejenak, terpelanting ke belakang untuk beberapa jarak",
    "",
    "5) Poison (Keracunan)",
    "- Ke Boss atau Mobs",
    "  Menimbulkan beberapa kerusakan untuk setiap tindakan selama 10 detik",
    "- Ke Pemain",
    "  Menimbulkan kerusakan sebesar 5% dari sisa HP pada setiap tindakan, kerusakan ini tidak dapat membunuh pemain",
    "",
    "6) Ignite (Terbakar)",
    "- Ke Boss atau Mobs",
    "  Menimbulkan beberapa kerusakan untuk setiap 1 detik (3 detik) selama 10 detik",
    "- Ke Pemain",
    "  Menimbulkan kerusakan sebesar 15% dari sisa HP terkini, kerusakan ini tidak dapat membunuh pemain",
    "",
    "7) Freeze (Beku)",
    "- Ke Boss atau Mobs",
    "  Mengurangi kecepatan gerak hingga 50%, berlangsung selama 10 detik. Dapat digunakan kembali saat durasi berakhir",
    "- Ke Pemain",
    "  Mengurangi 50% kecepatan gerak (moontion speed) dan Ayunan Dewa (Godspeed Wield), memiliki durasi 10 detik",
    "",
    "8) Slow (Lambat)",
    "- Ke Boss atau Mobs",
    "  Mengurangi kecepatan gerakan target sebesar 50% (25% untuk boss). Memiliki durasi 10 detik",
    "- Ke Pemain",
    "  Menurunkan 50% kecepatan berjalan (movement speed), durasi efek 10 detik. Evasion, Evasion recharge, dan Shukuchi dinonaktifkan",
    "",
    "9) Stop (Berhenti)",
    "- Ke Boss atau Mobs",
    "  Mengikat musuh ke posisinya saat ini selama 10 detik, memiliki cooldown 60 detik. Kurang efektif melawan bos karena hanya mengurangi kecepatan gerakan bos sebesar 50% (tidak mengikat bos). Lebih efektif untuk monster dan bos mini. Pola serangan seperti garis lurus atau serangan rapalan dapat digunakan saat mendapatkan debuff berhenti",
    "- Ke Pemain",
    "  Tidak dapat berpindah tempat atau berjalan, durasi 10 detik. Masih bisa menggunakan skill gerak (motion) dan rapalan seperti slash dapat digunakan saat mendapatkan debuff berhenti",
    "  Tidak dapat Evasion, Evasion recharge, dan Shukuchi terhenti",
    "",
    "10) Dizzy (Pening)",
    "- Ke Boss atau Mobs",
    "  Menurunkan tingkat guard dan evasion sebesar 100% (Boss 50%)",
    "- Ke Pemain",
    "  Menonaktifkan Evasion dan Guard recharge",
    "",
    "11) Dazzled (Silau)",
    "- Ke Boss atau Mobs",
    "  Flee -50%",
    "- Ke Pemain",
    "",
    "12) Paralysis (Lumpuh)",
    "- Ke Boss atau Mobs",
    "  Tingkatkan penundaan tindakan",
    "- Ke Pemain",
    "  Mengurangi 50% ASPD (Attack Speed/Kecepatan Serangan)",
    "",
    "13) Blind (Buta)",
    "- Ke Boss atau Mobs",
    "  Mengurangi akurasi 50%",
    "- Ke Pemain",
    "  Penurunan Akurasi sebesar 20% untuk serangan dalam jarak 7m, dan 40% untuk 8m ke atas",
    "",
    "14) Fear (Takut)",
    "- Ke Boss atau Mobs",
    "  30% kemungkinan untuk membatalkan tindakan",
    "- Ke Pemain",
    "  30% peluang gagal mengeluarkan skill",
    "",
    "15) Lethargy (Lesu)",
    "- Ke Boss atau Mobs",
    "  Output kerusakan berkurang 30%",
    "- Ke Pemain",
    "  Output kerusakan berkurang 30%",
    "",
    "16) Weaken (Lemah)",
    "- Ke Boss atau Mobs",
    "  Mengurangi MDEF target sebesar 25%",
    "- Ke Pemain",
    "  Menambah biaya konsumsi MP untuk semua keterampilan +100",
    "",
    "17) Bleed (Berdarah)",
    "- Ke Pemain",
    "  Tidak dapat menggunakan skill fisik",
    "",
    "18) Silence (Bisu)",
    "- Ke Pemain",
    "  Tidak dapat menggunakan skill sihir",
    "",
    "19) Confused",
    "- Ke Pemain",
    "  Tidak diketahui",
    "",
    "20) Armor Break (Pecah Zirah)",
    "- Ke Boss atau Mobs",
    "  DEF & MDEF -50%",
    "- Ke Pemain",
    "  Mengurangi kekebalan fisik dan sihir hingga 50%, tidak dapat menggunakan Guard",
    "",
    "21) Fatigue (Lelah)",
    "- Ke Boss atau Mobs",
    "  Mengurangi stabilitas 50%, pada serangan durasi terakhir akan mengalami graze",
    "- Ke Pemain",
    "  Mengurangi stabilitas 50%, pada serangan durasi terakhir akan mengalami graze",
    "",
    "22) Sleep (Tidur)",
    "- Ke Boss atau Mobs",
    "  Melumpuhkan untuk waktu yang lama, bangun saat menerima serangan, Bos memulihkan 3% dari HP maksimal saat bangun",
    "- Ke Pemain",
    "  Melumpuhkan untuk waktu yang lama, bangun saat menerima serangan, mengaktifkan regenerasi alami",
    "",
    "23) Mana Explosion (Ledakan Mana)",
    "- Ke Pemain",
    "  Setelah durasi berakhir, konsumsi semua mp menjadi 0 dan memberikan damage sama dengan konsumsi mp x10",
    "",
    "24) Sick (Sakit)",
    "- Ke Pemain",
    "  Menurunkan resistensi status buruk sebesar -50% (masih dapat terkena bahkan jika Anda memiliki resistensi status buruk 100%)",
    "",
    "25) Curse (Terkutuk)",
    "- Ke Pemain",
    "  Menurunkan CRT damage pemain sebesar -50%",
    "",
    "26) Item Disable",
    "- Ke Pemain",
    "  Tidak dapat menggunakan barang",
    "",
    "27) Overdrive (Lari)",
    "- Ke Pemain",
    "  Mengkonsumsi HP saat MP tidak mencukupi untuk melakukan skill, juga menerapkan tenacity (Gigih) ke semua skill dalam kombo (tidak mengganti tag yang ada)",
    "",
    "28) Suction (Pengisapan)",
    "- Ke Boss atau Mobs",
    "  Menarik ke pusat serangan, 50% peluang tarik untuk Bos",
    "- Ke Pemain",
    "  Menarik ke pusat serangan, saat terkena menonaktifkan evasion dan Guard selama 1 detik",
    "",
    "29) Petrified (Kaku)",
    "- Ke Pemain",
    "  Menghindar Mutlak +100%, dan menghapus aggro saat ini sebesar 99%",
    "",
    "30) Inversion",
    "- Ke Pemain",
    "  Mengganti HP% dan MP% Anda saat ini",
    "",
    "Sumber: Xixy bot @2023",
    "",
    divider,
  ].join("\n"),
  "#98": [
    "🎼Aku mah masih pemula",
    "Ajarin donk puh sepuh",
    "Puh sepuh ajarin donk",
    "Masih pemula aku",
    "Puh sepuh",
    "Tingkiwingki dipsi lala puh sepuh",
    "Ajarin donk",
    "Puhhhh sepuhhhh",
  ].join("\n"),
  "#99": ["Tes Kehokian"].join("\n"),
};

function normalizeTopicKey(value) {
  return (value || "").trim().toLowerCase();
}

module.exports = {
  name: "help",
  description: "Menampilkan bantuan penggunaan bot.",
  topicReplies,
  normalizeTopicKey,
  execute: async ({ sock, message, args = [] }) => {
    const normalizedArg = normalizeTopicKey(args[0]);
    const topicReply = topicReplies[normalizedArg];
    const text =
      normalizedArg === "#99"
        ? normalizeSpacing(topicReply || "")
        : normalizedArg === "#1"
          ? formatTopicMessage(topicReply || "", "guild")
          : normalizedArg === "#2"
            ? formatTopicMessage(topicReply || "", "newbie", {
                useReadMore: false,
              })
            : normalizedArg === "#3"
              ? formatTopicMessage(topicReply || "", "buff")
              : normalizedArg === "#4"
                ? formatTopicMessage(topicReply || "", "mq")
                : normalizedArg === "#5"
                  ? formatTopicMessage(topicReply || "", "bag")
                  : normalizedArg === "#6"
                    ? formatTopicMessage(topicReply || "", "leveling")
                    : normalizedArg === "#7"
                      ? formatTopicMessage(topicReply || "", "refine")
                      : normalizedArg === "#8"
                        ? formatTopicMessage(topicReply || "", "blacksmith")
                        : normalizedArg === "#9"
                          ? formatTopicMessage(topicReply || "", "smithProf")
                          : normalizedArg === "#10"
                            ? formatTopicMessage(topicReply || "", "potential")
                            : normalizedArg === "#11"
                              ? formatTopicMessage(
                                  topicReply || "",
                                  "synthesisProf",
                                )
                              : normalizedArg === "#12"
                                ? formatTopicMessage(
                                    topicReply || "",
                                    "xtallMaster",
                                  )
                                : normalizedArg === "#13"
                                  ? formatTopicMessage(
                                      topicReply || "",
                                      "xtallEvent",
                                    )
                                  : normalizedArg === "#14"
                                    ? formatTopicMessage(
                                        topicReply || "",
                                        "pet",
                                      )
                                    : normalizedArg === "#15"
                                      ? formatTopicMessage(
                                          topicReply || "",
                                          "raid",
                                        )
                                      : normalizedArg === "#16"
                                        ? formatTopicMessage(
                                            topicReply || "",
                                            "statusPoint",
                                          )
                                        : normalizedArg === "#17"
                                          ? formatTopicMessage(
                                              topicReply || "",
                                              "ailment",
                                            )
                                          : normalizedArg === "#98"
                                            ? normalizeSpacing(topicReply || "")
                                            : formatHelpMessage(
                                                helpMenuText,
                                                "menu",
                                              );

    if (normalizedArg === "#98") {
      await sock.sendMessage(
        message.key.remoteJid,
        {
          text,
        },
        {
          quoted: message,
        },
      );

      await sock.sendMessage(
        message.key.remoteJid,
        {
          audio: sepuhAudio,
          mimetype: "audio/ogg; codecs=opus",
          ptt: true,
        },
        {
          quoted: message,
        },
      );

      return;
    }

    if (normalizedArg === "#99") {
      const { percentage, response, opener } = getRandomLuckResult();

      await sock.sendMessage(
        message.key.remoteJid,
        {
          text: [
            opener,
            "",
            `Tes kehokian yaa~ (≧◡≦)`,
            `Hasil hoki hari ini: *${percentage}%* (๑˃ᴗ˂)ﻭ`,
            "",
            response,
          ].join("\n"),
        },
        {
          quoted: message,
        },
      );

      return;
    }

    await sock.sendMessage(
      message.key.remoteJid,
      {
        text,
      },
      {
        quoted: message,
      },
    );
  },
};
